
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CalendarEvent` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model CalendarEvent
 * A dated market event. Ticker is null for market-wide entries such as a rate decision.
 */
export type CalendarEventModel = runtime.Types.Result.DefaultSelection<Prisma.$CalendarEventPayload>

export type AggregateCalendarEvent = {
  _count: CalendarEventCountAggregateOutputType | null
  _min: CalendarEventMinAggregateOutputType | null
  _max: CalendarEventMaxAggregateOutputType | null
}

export type CalendarEventMinAggregateOutputType = {
  id: string | null
  ticker: string | null
  title: string | null
  kind: $Enums.CalendarEventKind | null
  detail: string | null
  eventDate: Date | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
}

export type CalendarEventMaxAggregateOutputType = {
  id: string | null
  ticker: string | null
  title: string | null
  kind: $Enums.CalendarEventKind | null
  detail: string | null
  eventDate: Date | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
}

export type CalendarEventCountAggregateOutputType = {
  id: number
  ticker: number
  title: number
  kind: number
  detail: number
  eventDate: number
  createdAt: number
  updatedAt: number
  deletedAt: number
  _all: number
}


export type CalendarEventMinAggregateInputType = {
  id?: true
  ticker?: true
  title?: true
  kind?: true
  detail?: true
  eventDate?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
}

export type CalendarEventMaxAggregateInputType = {
  id?: true
  ticker?: true
  title?: true
  kind?: true
  detail?: true
  eventDate?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
}

export type CalendarEventCountAggregateInputType = {
  id?: true
  ticker?: true
  title?: true
  kind?: true
  detail?: true
  eventDate?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
  _all?: true
}

export type CalendarEventAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CalendarEvent to aggregate.
   */
  where?: Prisma.CalendarEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CalendarEvents to fetch.
   */
  orderBy?: Prisma.CalendarEventOrderByWithRelationInput | Prisma.CalendarEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CalendarEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CalendarEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CalendarEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CalendarEvents
  **/
  _count?: true | CalendarEventCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CalendarEventMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CalendarEventMaxAggregateInputType
}

export type GetCalendarEventAggregateType<T extends CalendarEventAggregateArgs> = {
      [P in keyof T & keyof AggregateCalendarEvent]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCalendarEvent[P]>
    : Prisma.GetScalarType<T[P], AggregateCalendarEvent[P]>
}




export type CalendarEventGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CalendarEventWhereInput
  orderBy?: Prisma.CalendarEventOrderByWithAggregationInput | Prisma.CalendarEventOrderByWithAggregationInput[]
  by: Prisma.CalendarEventScalarFieldEnum[] | Prisma.CalendarEventScalarFieldEnum
  having?: Prisma.CalendarEventScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CalendarEventCountAggregateInputType | true
  _min?: CalendarEventMinAggregateInputType
  _max?: CalendarEventMaxAggregateInputType
}

export type CalendarEventGroupByOutputType = {
  id: string
  ticker: string | null
  title: string
  kind: $Enums.CalendarEventKind
  detail: string | null
  eventDate: Date
  createdAt: Date
  updatedAt: Date
  deletedAt: Date | null
  _count: CalendarEventCountAggregateOutputType | null
  _min: CalendarEventMinAggregateOutputType | null
  _max: CalendarEventMaxAggregateOutputType | null
}

export type GetCalendarEventGroupByPayload<T extends CalendarEventGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CalendarEventGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CalendarEventGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CalendarEventGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CalendarEventGroupByOutputType[P]>
      }
    >
  >



export type CalendarEventWhereInput = {
  AND?: Prisma.CalendarEventWhereInput | Prisma.CalendarEventWhereInput[]
  OR?: Prisma.CalendarEventWhereInput[]
  NOT?: Prisma.CalendarEventWhereInput | Prisma.CalendarEventWhereInput[]
  id?: Prisma.StringFilter<"CalendarEvent"> | string
  ticker?: Prisma.StringNullableFilter<"CalendarEvent"> | string | null
  title?: Prisma.StringFilter<"CalendarEvent"> | string
  kind?: Prisma.EnumCalendarEventKindFilter<"CalendarEvent"> | $Enums.CalendarEventKind
  detail?: Prisma.StringNullableFilter<"CalendarEvent"> | string | null
  eventDate?: Prisma.DateTimeFilter<"CalendarEvent"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"CalendarEvent"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CalendarEvent"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"CalendarEvent"> | Date | string | null
}

export type CalendarEventOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  ticker?: Prisma.SortOrderInput | Prisma.SortOrder
  title?: Prisma.SortOrder
  kind?: Prisma.SortOrder
  detail?: Prisma.SortOrderInput | Prisma.SortOrder
  eventDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
}

export type CalendarEventWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.CalendarEventWhereInput | Prisma.CalendarEventWhereInput[]
  OR?: Prisma.CalendarEventWhereInput[]
  NOT?: Prisma.CalendarEventWhereInput | Prisma.CalendarEventWhereInput[]
  ticker?: Prisma.StringNullableFilter<"CalendarEvent"> | string | null
  title?: Prisma.StringFilter<"CalendarEvent"> | string
  kind?: Prisma.EnumCalendarEventKindFilter<"CalendarEvent"> | $Enums.CalendarEventKind
  detail?: Prisma.StringNullableFilter<"CalendarEvent"> | string | null
  eventDate?: Prisma.DateTimeFilter<"CalendarEvent"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"CalendarEvent"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CalendarEvent"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"CalendarEvent"> | Date | string | null
}, "id">

export type CalendarEventOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  ticker?: Prisma.SortOrderInput | Prisma.SortOrder
  title?: Prisma.SortOrder
  kind?: Prisma.SortOrder
  detail?: Prisma.SortOrderInput | Prisma.SortOrder
  eventDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.CalendarEventCountOrderByAggregateInput
  _max?: Prisma.CalendarEventMaxOrderByAggregateInput
  _min?: Prisma.CalendarEventMinOrderByAggregateInput
}

export type CalendarEventScalarWhereWithAggregatesInput = {
  AND?: Prisma.CalendarEventScalarWhereWithAggregatesInput | Prisma.CalendarEventScalarWhereWithAggregatesInput[]
  OR?: Prisma.CalendarEventScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CalendarEventScalarWhereWithAggregatesInput | Prisma.CalendarEventScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"CalendarEvent"> | string
  ticker?: Prisma.StringNullableWithAggregatesFilter<"CalendarEvent"> | string | null
  title?: Prisma.StringWithAggregatesFilter<"CalendarEvent"> | string
  kind?: Prisma.EnumCalendarEventKindWithAggregatesFilter<"CalendarEvent"> | $Enums.CalendarEventKind
  detail?: Prisma.StringNullableWithAggregatesFilter<"CalendarEvent"> | string | null
  eventDate?: Prisma.DateTimeWithAggregatesFilter<"CalendarEvent"> | Date | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"CalendarEvent"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"CalendarEvent"> | Date | string
  deletedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"CalendarEvent"> | Date | string | null
}

export type CalendarEventCreateInput = {
  id?: string
  ticker?: string | null
  title: string
  kind: $Enums.CalendarEventKind
  detail?: string | null
  eventDate: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type CalendarEventUncheckedCreateInput = {
  id?: string
  ticker?: string | null
  title: string
  kind: $Enums.CalendarEventKind
  detail?: string | null
  eventDate: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type CalendarEventUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  ticker?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumCalendarEventKindFieldUpdateOperationsInput | $Enums.CalendarEventKind
  detail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  eventDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type CalendarEventUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  ticker?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumCalendarEventKindFieldUpdateOperationsInput | $Enums.CalendarEventKind
  detail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  eventDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type CalendarEventCreateManyInput = {
  id?: string
  ticker?: string | null
  title: string
  kind: $Enums.CalendarEventKind
  detail?: string | null
  eventDate: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type CalendarEventUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  ticker?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumCalendarEventKindFieldUpdateOperationsInput | $Enums.CalendarEventKind
  detail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  eventDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type CalendarEventUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  ticker?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumCalendarEventKindFieldUpdateOperationsInput | $Enums.CalendarEventKind
  detail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  eventDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type CalendarEventCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  ticker?: Prisma.SortOrder
  title?: Prisma.SortOrder
  kind?: Prisma.SortOrder
  detail?: Prisma.SortOrder
  eventDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type CalendarEventMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  ticker?: Prisma.SortOrder
  title?: Prisma.SortOrder
  kind?: Prisma.SortOrder
  detail?: Prisma.SortOrder
  eventDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type CalendarEventMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  ticker?: Prisma.SortOrder
  title?: Prisma.SortOrder
  kind?: Prisma.SortOrder
  detail?: Prisma.SortOrder
  eventDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type EnumCalendarEventKindFieldUpdateOperationsInput = {
  set?: $Enums.CalendarEventKind
}



export type CalendarEventSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  ticker?: boolean
  title?: boolean
  kind?: boolean
  detail?: boolean
  eventDate?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
}, ExtArgs["result"]["calendarEvent"]>

export type CalendarEventSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  ticker?: boolean
  title?: boolean
  kind?: boolean
  detail?: boolean
  eventDate?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
}, ExtArgs["result"]["calendarEvent"]>

export type CalendarEventSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  ticker?: boolean
  title?: boolean
  kind?: boolean
  detail?: boolean
  eventDate?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
}, ExtArgs["result"]["calendarEvent"]>

export type CalendarEventSelectScalar = {
  id?: boolean
  ticker?: boolean
  title?: boolean
  kind?: boolean
  detail?: boolean
  eventDate?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
}

export type CalendarEventOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "ticker" | "title" | "kind" | "detail" | "eventDate" | "createdAt" | "updatedAt" | "deletedAt", ExtArgs["result"]["calendarEvent"]>

export type $CalendarEventPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CalendarEvent"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    ticker: string | null
    title: string
    kind: $Enums.CalendarEventKind
    detail: string | null
    eventDate: Date
    createdAt: Date
    updatedAt: Date
    deletedAt: Date | null
  }, ExtArgs["result"]["calendarEvent"]>
  composites: {}
}

export type CalendarEventGetPayload<S extends boolean | null | undefined | CalendarEventDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CalendarEventPayload, S>

export type CalendarEventCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CalendarEventFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CalendarEventCountAggregateInputType | true
  }

export interface CalendarEventDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CalendarEvent'], meta: { name: 'CalendarEvent' } }
  /**
   * Find zero or one CalendarEvent that matches the filter.
   * @param {CalendarEventFindUniqueArgs} args - Arguments to find a CalendarEvent
   * @example
   * // Get one CalendarEvent
   * const calendarEvent = await prisma.calendarEvent.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CalendarEventFindUniqueArgs>(args: Prisma.SelectSubset<T, CalendarEventFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CalendarEventClient<runtime.Types.Result.GetResult<Prisma.$CalendarEventPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CalendarEvent that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CalendarEventFindUniqueOrThrowArgs} args - Arguments to find a CalendarEvent
   * @example
   * // Get one CalendarEvent
   * const calendarEvent = await prisma.calendarEvent.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CalendarEventFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CalendarEventFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CalendarEventClient<runtime.Types.Result.GetResult<Prisma.$CalendarEventPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CalendarEvent that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CalendarEventFindFirstArgs} args - Arguments to find a CalendarEvent
   * @example
   * // Get one CalendarEvent
   * const calendarEvent = await prisma.calendarEvent.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CalendarEventFindFirstArgs>(args?: Prisma.SelectSubset<T, CalendarEventFindFirstArgs<ExtArgs>>): Prisma.Prisma__CalendarEventClient<runtime.Types.Result.GetResult<Prisma.$CalendarEventPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CalendarEvent that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CalendarEventFindFirstOrThrowArgs} args - Arguments to find a CalendarEvent
   * @example
   * // Get one CalendarEvent
   * const calendarEvent = await prisma.calendarEvent.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CalendarEventFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CalendarEventFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CalendarEventClient<runtime.Types.Result.GetResult<Prisma.$CalendarEventPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CalendarEvents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CalendarEventFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CalendarEvents
   * const calendarEvents = await prisma.calendarEvent.findMany()
   * 
   * // Get first 10 CalendarEvents
   * const calendarEvents = await prisma.calendarEvent.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const calendarEventWithIdOnly = await prisma.calendarEvent.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CalendarEventFindManyArgs>(args?: Prisma.SelectSubset<T, CalendarEventFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CalendarEventPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CalendarEvent.
   * @param {CalendarEventCreateArgs} args - Arguments to create a CalendarEvent.
   * @example
   * // Create one CalendarEvent
   * const CalendarEvent = await prisma.calendarEvent.create({
   *   data: {
   *     // ... data to create a CalendarEvent
   *   }
   * })
   * 
   */
  create<T extends CalendarEventCreateArgs>(args: Prisma.SelectSubset<T, CalendarEventCreateArgs<ExtArgs>>): Prisma.Prisma__CalendarEventClient<runtime.Types.Result.GetResult<Prisma.$CalendarEventPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CalendarEvents.
   * @param {CalendarEventCreateManyArgs} args - Arguments to create many CalendarEvents.
   * @example
   * // Create many CalendarEvents
   * const calendarEvent = await prisma.calendarEvent.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CalendarEventCreateManyArgs>(args?: Prisma.SelectSubset<T, CalendarEventCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CalendarEvents and returns the data saved in the database.
   * @param {CalendarEventCreateManyAndReturnArgs} args - Arguments to create many CalendarEvents.
   * @example
   * // Create many CalendarEvents
   * const calendarEvent = await prisma.calendarEvent.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CalendarEvents and only return the `id`
   * const calendarEventWithIdOnly = await prisma.calendarEvent.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CalendarEventCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CalendarEventCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CalendarEventPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CalendarEvent.
   * @param {CalendarEventDeleteArgs} args - Arguments to delete one CalendarEvent.
   * @example
   * // Delete one CalendarEvent
   * const CalendarEvent = await prisma.calendarEvent.delete({
   *   where: {
   *     // ... filter to delete one CalendarEvent
   *   }
   * })
   * 
   */
  delete<T extends CalendarEventDeleteArgs>(args: Prisma.SelectSubset<T, CalendarEventDeleteArgs<ExtArgs>>): Prisma.Prisma__CalendarEventClient<runtime.Types.Result.GetResult<Prisma.$CalendarEventPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CalendarEvent.
   * @param {CalendarEventUpdateArgs} args - Arguments to update one CalendarEvent.
   * @example
   * // Update one CalendarEvent
   * const calendarEvent = await prisma.calendarEvent.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CalendarEventUpdateArgs>(args: Prisma.SelectSubset<T, CalendarEventUpdateArgs<ExtArgs>>): Prisma.Prisma__CalendarEventClient<runtime.Types.Result.GetResult<Prisma.$CalendarEventPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CalendarEvents.
   * @param {CalendarEventDeleteManyArgs} args - Arguments to filter CalendarEvents to delete.
   * @example
   * // Delete a few CalendarEvents
   * const { count } = await prisma.calendarEvent.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CalendarEventDeleteManyArgs>(args?: Prisma.SelectSubset<T, CalendarEventDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CalendarEvents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CalendarEventUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CalendarEvents
   * const calendarEvent = await prisma.calendarEvent.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CalendarEventUpdateManyArgs>(args: Prisma.SelectSubset<T, CalendarEventUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CalendarEvents and returns the data updated in the database.
   * @param {CalendarEventUpdateManyAndReturnArgs} args - Arguments to update many CalendarEvents.
   * @example
   * // Update many CalendarEvents
   * const calendarEvent = await prisma.calendarEvent.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CalendarEvents and only return the `id`
   * const calendarEventWithIdOnly = await prisma.calendarEvent.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CalendarEventUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CalendarEventUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CalendarEventPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CalendarEvent.
   * @param {CalendarEventUpsertArgs} args - Arguments to update or create a CalendarEvent.
   * @example
   * // Update or create a CalendarEvent
   * const calendarEvent = await prisma.calendarEvent.upsert({
   *   create: {
   *     // ... data to create a CalendarEvent
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CalendarEvent we want to update
   *   }
   * })
   */
  upsert<T extends CalendarEventUpsertArgs>(args: Prisma.SelectSubset<T, CalendarEventUpsertArgs<ExtArgs>>): Prisma.Prisma__CalendarEventClient<runtime.Types.Result.GetResult<Prisma.$CalendarEventPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CalendarEvents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CalendarEventCountArgs} args - Arguments to filter CalendarEvents to count.
   * @example
   * // Count the number of CalendarEvents
   * const count = await prisma.calendarEvent.count({
   *   where: {
   *     // ... the filter for the CalendarEvents we want to count
   *   }
   * })
  **/
  count<T extends CalendarEventCountArgs>(
    args?: Prisma.Subset<T, CalendarEventCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CalendarEventCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CalendarEvent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CalendarEventAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CalendarEventAggregateArgs>(args: Prisma.Subset<T, CalendarEventAggregateArgs>): Prisma.PrismaPromise<GetCalendarEventAggregateType<T>>

  /**
   * Group by CalendarEvent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CalendarEventGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CalendarEventGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CalendarEventGroupByArgs['orderBy'] }
      : { orderBy?: CalendarEventGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CalendarEventGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCalendarEventGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CalendarEvent model
 */
readonly fields: CalendarEventFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CalendarEvent.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CalendarEventClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CalendarEvent model
 */
export interface CalendarEventFieldRefs {
  readonly id: Prisma.FieldRef<"CalendarEvent", 'String'>
  readonly ticker: Prisma.FieldRef<"CalendarEvent", 'String'>
  readonly title: Prisma.FieldRef<"CalendarEvent", 'String'>
  readonly kind: Prisma.FieldRef<"CalendarEvent", 'CalendarEventKind'>
  readonly detail: Prisma.FieldRef<"CalendarEvent", 'String'>
  readonly eventDate: Prisma.FieldRef<"CalendarEvent", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"CalendarEvent", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"CalendarEvent", 'DateTime'>
  readonly deletedAt: Prisma.FieldRef<"CalendarEvent", 'DateTime'>
}
    

// Custom InputTypes
/**
 * CalendarEvent findUnique
 */
export type CalendarEventFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CalendarEvent
   */
  select?: Prisma.CalendarEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CalendarEvent
   */
  omit?: Prisma.CalendarEventOmit<ExtArgs> | null
  /**
   * Filter, which CalendarEvent to fetch.
   */
  where: Prisma.CalendarEventWhereUniqueInput
}

/**
 * CalendarEvent findUniqueOrThrow
 */
export type CalendarEventFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CalendarEvent
   */
  select?: Prisma.CalendarEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CalendarEvent
   */
  omit?: Prisma.CalendarEventOmit<ExtArgs> | null
  /**
   * Filter, which CalendarEvent to fetch.
   */
  where: Prisma.CalendarEventWhereUniqueInput
}

/**
 * CalendarEvent findFirst
 */
export type CalendarEventFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CalendarEvent
   */
  select?: Prisma.CalendarEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CalendarEvent
   */
  omit?: Prisma.CalendarEventOmit<ExtArgs> | null
  /**
   * Filter, which CalendarEvent to fetch.
   */
  where?: Prisma.CalendarEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CalendarEvents to fetch.
   */
  orderBy?: Prisma.CalendarEventOrderByWithRelationInput | Prisma.CalendarEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CalendarEvents.
   */
  cursor?: Prisma.CalendarEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CalendarEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CalendarEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CalendarEvents.
   */
  distinct?: Prisma.CalendarEventScalarFieldEnum | Prisma.CalendarEventScalarFieldEnum[]
}

/**
 * CalendarEvent findFirstOrThrow
 */
export type CalendarEventFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CalendarEvent
   */
  select?: Prisma.CalendarEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CalendarEvent
   */
  omit?: Prisma.CalendarEventOmit<ExtArgs> | null
  /**
   * Filter, which CalendarEvent to fetch.
   */
  where?: Prisma.CalendarEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CalendarEvents to fetch.
   */
  orderBy?: Prisma.CalendarEventOrderByWithRelationInput | Prisma.CalendarEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CalendarEvents.
   */
  cursor?: Prisma.CalendarEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CalendarEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CalendarEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CalendarEvents.
   */
  distinct?: Prisma.CalendarEventScalarFieldEnum | Prisma.CalendarEventScalarFieldEnum[]
}

/**
 * CalendarEvent findMany
 */
export type CalendarEventFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CalendarEvent
   */
  select?: Prisma.CalendarEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CalendarEvent
   */
  omit?: Prisma.CalendarEventOmit<ExtArgs> | null
  /**
   * Filter, which CalendarEvents to fetch.
   */
  where?: Prisma.CalendarEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CalendarEvents to fetch.
   */
  orderBy?: Prisma.CalendarEventOrderByWithRelationInput | Prisma.CalendarEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CalendarEvents.
   */
  cursor?: Prisma.CalendarEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CalendarEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CalendarEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CalendarEvents.
   */
  distinct?: Prisma.CalendarEventScalarFieldEnum | Prisma.CalendarEventScalarFieldEnum[]
}

/**
 * CalendarEvent create
 */
export type CalendarEventCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CalendarEvent
   */
  select?: Prisma.CalendarEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CalendarEvent
   */
  omit?: Prisma.CalendarEventOmit<ExtArgs> | null
  /**
   * The data needed to create a CalendarEvent.
   */
  data: Prisma.XOR<Prisma.CalendarEventCreateInput, Prisma.CalendarEventUncheckedCreateInput>
}

/**
 * CalendarEvent createMany
 */
export type CalendarEventCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CalendarEvents.
   */
  data: Prisma.CalendarEventCreateManyInput | Prisma.CalendarEventCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * CalendarEvent createManyAndReturn
 */
export type CalendarEventCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CalendarEvent
   */
  select?: Prisma.CalendarEventSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CalendarEvent
   */
  omit?: Prisma.CalendarEventOmit<ExtArgs> | null
  /**
   * The data used to create many CalendarEvents.
   */
  data: Prisma.CalendarEventCreateManyInput | Prisma.CalendarEventCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * CalendarEvent update
 */
export type CalendarEventUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CalendarEvent
   */
  select?: Prisma.CalendarEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CalendarEvent
   */
  omit?: Prisma.CalendarEventOmit<ExtArgs> | null
  /**
   * The data needed to update a CalendarEvent.
   */
  data: Prisma.XOR<Prisma.CalendarEventUpdateInput, Prisma.CalendarEventUncheckedUpdateInput>
  /**
   * Choose, which CalendarEvent to update.
   */
  where: Prisma.CalendarEventWhereUniqueInput
}

/**
 * CalendarEvent updateMany
 */
export type CalendarEventUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CalendarEvents.
   */
  data: Prisma.XOR<Prisma.CalendarEventUpdateManyMutationInput, Prisma.CalendarEventUncheckedUpdateManyInput>
  /**
   * Filter which CalendarEvents to update
   */
  where?: Prisma.CalendarEventWhereInput
  /**
   * Limit how many CalendarEvents to update.
   */
  limit?: number
}

/**
 * CalendarEvent updateManyAndReturn
 */
export type CalendarEventUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CalendarEvent
   */
  select?: Prisma.CalendarEventSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CalendarEvent
   */
  omit?: Prisma.CalendarEventOmit<ExtArgs> | null
  /**
   * The data used to update CalendarEvents.
   */
  data: Prisma.XOR<Prisma.CalendarEventUpdateManyMutationInput, Prisma.CalendarEventUncheckedUpdateManyInput>
  /**
   * Filter which CalendarEvents to update
   */
  where?: Prisma.CalendarEventWhereInput
  /**
   * Limit how many CalendarEvents to update.
   */
  limit?: number
}

/**
 * CalendarEvent upsert
 */
export type CalendarEventUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CalendarEvent
   */
  select?: Prisma.CalendarEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CalendarEvent
   */
  omit?: Prisma.CalendarEventOmit<ExtArgs> | null
  /**
   * The filter to search for the CalendarEvent to update in case it exists.
   */
  where: Prisma.CalendarEventWhereUniqueInput
  /**
   * In case the CalendarEvent found by the `where` argument doesn't exist, create a new CalendarEvent with this data.
   */
  create: Prisma.XOR<Prisma.CalendarEventCreateInput, Prisma.CalendarEventUncheckedCreateInput>
  /**
   * In case the CalendarEvent was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CalendarEventUpdateInput, Prisma.CalendarEventUncheckedUpdateInput>
}

/**
 * CalendarEvent delete
 */
export type CalendarEventDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CalendarEvent
   */
  select?: Prisma.CalendarEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CalendarEvent
   */
  omit?: Prisma.CalendarEventOmit<ExtArgs> | null
  /**
   * Filter which CalendarEvent to delete.
   */
  where: Prisma.CalendarEventWhereUniqueInput
}

/**
 * CalendarEvent deleteMany
 */
export type CalendarEventDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CalendarEvents to delete
   */
  where?: Prisma.CalendarEventWhereInput
  /**
   * Limit how many CalendarEvents to delete.
   */
  limit?: number
}

/**
 * CalendarEvent without action
 */
export type CalendarEventDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CalendarEvent
   */
  select?: Prisma.CalendarEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CalendarEvent
   */
  omit?: Prisma.CalendarEventOmit<ExtArgs> | null
}
