
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `DiscussionReply` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model DiscussionReply
 * 
 */
export type DiscussionReplyModel = runtime.Types.Result.DefaultSelection<Prisma.$DiscussionReplyPayload>

export type AggregateDiscussionReply = {
  _count: DiscussionReplyCountAggregateOutputType | null
  _min: DiscussionReplyMinAggregateOutputType | null
  _max: DiscussionReplyMaxAggregateOutputType | null
}

export type DiscussionReplyMinAggregateOutputType = {
  id: string | null
  threadId: string | null
  authorId: string | null
  body: string | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
}

export type DiscussionReplyMaxAggregateOutputType = {
  id: string | null
  threadId: string | null
  authorId: string | null
  body: string | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
}

export type DiscussionReplyCountAggregateOutputType = {
  id: number
  threadId: number
  authorId: number
  body: number
  createdAt: number
  updatedAt: number
  deletedAt: number
  _all: number
}


export type DiscussionReplyMinAggregateInputType = {
  id?: true
  threadId?: true
  authorId?: true
  body?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
}

export type DiscussionReplyMaxAggregateInputType = {
  id?: true
  threadId?: true
  authorId?: true
  body?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
}

export type DiscussionReplyCountAggregateInputType = {
  id?: true
  threadId?: true
  authorId?: true
  body?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
  _all?: true
}

export type DiscussionReplyAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DiscussionReply to aggregate.
   */
  where?: Prisma.DiscussionReplyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DiscussionReplies to fetch.
   */
  orderBy?: Prisma.DiscussionReplyOrderByWithRelationInput | Prisma.DiscussionReplyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DiscussionReplyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DiscussionReplies from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DiscussionReplies.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned DiscussionReplies
  **/
  _count?: true | DiscussionReplyCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DiscussionReplyMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DiscussionReplyMaxAggregateInputType
}

export type GetDiscussionReplyAggregateType<T extends DiscussionReplyAggregateArgs> = {
      [P in keyof T & keyof AggregateDiscussionReply]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDiscussionReply[P]>
    : Prisma.GetScalarType<T[P], AggregateDiscussionReply[P]>
}




export type DiscussionReplyGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DiscussionReplyWhereInput
  orderBy?: Prisma.DiscussionReplyOrderByWithAggregationInput | Prisma.DiscussionReplyOrderByWithAggregationInput[]
  by: Prisma.DiscussionReplyScalarFieldEnum[] | Prisma.DiscussionReplyScalarFieldEnum
  having?: Prisma.DiscussionReplyScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DiscussionReplyCountAggregateInputType | true
  _min?: DiscussionReplyMinAggregateInputType
  _max?: DiscussionReplyMaxAggregateInputType
}

export type DiscussionReplyGroupByOutputType = {
  id: string
  threadId: string
  authorId: string
  body: string
  createdAt: Date
  updatedAt: Date
  deletedAt: Date | null
  _count: DiscussionReplyCountAggregateOutputType | null
  _min: DiscussionReplyMinAggregateOutputType | null
  _max: DiscussionReplyMaxAggregateOutputType | null
}

export type GetDiscussionReplyGroupByPayload<T extends DiscussionReplyGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DiscussionReplyGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DiscussionReplyGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DiscussionReplyGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DiscussionReplyGroupByOutputType[P]>
      }
    >
  >



export type DiscussionReplyWhereInput = {
  AND?: Prisma.DiscussionReplyWhereInput | Prisma.DiscussionReplyWhereInput[]
  OR?: Prisma.DiscussionReplyWhereInput[]
  NOT?: Prisma.DiscussionReplyWhereInput | Prisma.DiscussionReplyWhereInput[]
  id?: Prisma.StringFilter<"DiscussionReply"> | string
  threadId?: Prisma.StringFilter<"DiscussionReply"> | string
  authorId?: Prisma.StringFilter<"DiscussionReply"> | string
  body?: Prisma.StringFilter<"DiscussionReply"> | string
  createdAt?: Prisma.DateTimeFilter<"DiscussionReply"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"DiscussionReply"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"DiscussionReply"> | Date | string | null
  thread?: Prisma.XOR<Prisma.DiscussionThreadScalarRelationFilter, Prisma.DiscussionThreadWhereInput>
  author?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type DiscussionReplyOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  threadId?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  body?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  thread?: Prisma.DiscussionThreadOrderByWithRelationInput
  author?: Prisma.UserOrderByWithRelationInput
}

export type DiscussionReplyWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.DiscussionReplyWhereInput | Prisma.DiscussionReplyWhereInput[]
  OR?: Prisma.DiscussionReplyWhereInput[]
  NOT?: Prisma.DiscussionReplyWhereInput | Prisma.DiscussionReplyWhereInput[]
  threadId?: Prisma.StringFilter<"DiscussionReply"> | string
  authorId?: Prisma.StringFilter<"DiscussionReply"> | string
  body?: Prisma.StringFilter<"DiscussionReply"> | string
  createdAt?: Prisma.DateTimeFilter<"DiscussionReply"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"DiscussionReply"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"DiscussionReply"> | Date | string | null
  thread?: Prisma.XOR<Prisma.DiscussionThreadScalarRelationFilter, Prisma.DiscussionThreadWhereInput>
  author?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type DiscussionReplyOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  threadId?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  body?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.DiscussionReplyCountOrderByAggregateInput
  _max?: Prisma.DiscussionReplyMaxOrderByAggregateInput
  _min?: Prisma.DiscussionReplyMinOrderByAggregateInput
}

export type DiscussionReplyScalarWhereWithAggregatesInput = {
  AND?: Prisma.DiscussionReplyScalarWhereWithAggregatesInput | Prisma.DiscussionReplyScalarWhereWithAggregatesInput[]
  OR?: Prisma.DiscussionReplyScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DiscussionReplyScalarWhereWithAggregatesInput | Prisma.DiscussionReplyScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"DiscussionReply"> | string
  threadId?: Prisma.StringWithAggregatesFilter<"DiscussionReply"> | string
  authorId?: Prisma.StringWithAggregatesFilter<"DiscussionReply"> | string
  body?: Prisma.StringWithAggregatesFilter<"DiscussionReply"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"DiscussionReply"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"DiscussionReply"> | Date | string
  deletedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"DiscussionReply"> | Date | string | null
}

export type DiscussionReplyCreateInput = {
  id?: string
  body: string
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  thread: Prisma.DiscussionThreadCreateNestedOneWithoutReplyInput
  author: Prisma.UserCreateNestedOneWithoutDiscussionReplyInput
}

export type DiscussionReplyUncheckedCreateInput = {
  id?: string
  threadId: string
  authorId: string
  body: string
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type DiscussionReplyUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  body?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  thread?: Prisma.DiscussionThreadUpdateOneRequiredWithoutReplyNestedInput
  author?: Prisma.UserUpdateOneRequiredWithoutDiscussionReplyNestedInput
}

export type DiscussionReplyUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  threadId?: Prisma.StringFieldUpdateOperationsInput | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  body?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type DiscussionReplyCreateManyInput = {
  id?: string
  threadId: string
  authorId: string
  body: string
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type DiscussionReplyUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  body?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type DiscussionReplyUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  threadId?: Prisma.StringFieldUpdateOperationsInput | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  body?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type DiscussionReplyListRelationFilter = {
  every?: Prisma.DiscussionReplyWhereInput
  some?: Prisma.DiscussionReplyWhereInput
  none?: Prisma.DiscussionReplyWhereInput
}

export type DiscussionReplyOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type DiscussionReplyCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  threadId?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  body?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type DiscussionReplyMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  threadId?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  body?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type DiscussionReplyMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  threadId?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  body?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type DiscussionReplyCreateNestedManyWithoutAuthorInput = {
  create?: Prisma.XOR<Prisma.DiscussionReplyCreateWithoutAuthorInput, Prisma.DiscussionReplyUncheckedCreateWithoutAuthorInput> | Prisma.DiscussionReplyCreateWithoutAuthorInput[] | Prisma.DiscussionReplyUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?: Prisma.DiscussionReplyCreateOrConnectWithoutAuthorInput | Prisma.DiscussionReplyCreateOrConnectWithoutAuthorInput[]
  createMany?: Prisma.DiscussionReplyCreateManyAuthorInputEnvelope
  connect?: Prisma.DiscussionReplyWhereUniqueInput | Prisma.DiscussionReplyWhereUniqueInput[]
}

export type DiscussionReplyUncheckedCreateNestedManyWithoutAuthorInput = {
  create?: Prisma.XOR<Prisma.DiscussionReplyCreateWithoutAuthorInput, Prisma.DiscussionReplyUncheckedCreateWithoutAuthorInput> | Prisma.DiscussionReplyCreateWithoutAuthorInput[] | Prisma.DiscussionReplyUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?: Prisma.DiscussionReplyCreateOrConnectWithoutAuthorInput | Prisma.DiscussionReplyCreateOrConnectWithoutAuthorInput[]
  createMany?: Prisma.DiscussionReplyCreateManyAuthorInputEnvelope
  connect?: Prisma.DiscussionReplyWhereUniqueInput | Prisma.DiscussionReplyWhereUniqueInput[]
}

export type DiscussionReplyUpdateManyWithoutAuthorNestedInput = {
  create?: Prisma.XOR<Prisma.DiscussionReplyCreateWithoutAuthorInput, Prisma.DiscussionReplyUncheckedCreateWithoutAuthorInput> | Prisma.DiscussionReplyCreateWithoutAuthorInput[] | Prisma.DiscussionReplyUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?: Prisma.DiscussionReplyCreateOrConnectWithoutAuthorInput | Prisma.DiscussionReplyCreateOrConnectWithoutAuthorInput[]
  upsert?: Prisma.DiscussionReplyUpsertWithWhereUniqueWithoutAuthorInput | Prisma.DiscussionReplyUpsertWithWhereUniqueWithoutAuthorInput[]
  createMany?: Prisma.DiscussionReplyCreateManyAuthorInputEnvelope
  set?: Prisma.DiscussionReplyWhereUniqueInput | Prisma.DiscussionReplyWhereUniqueInput[]
  disconnect?: Prisma.DiscussionReplyWhereUniqueInput | Prisma.DiscussionReplyWhereUniqueInput[]
  delete?: Prisma.DiscussionReplyWhereUniqueInput | Prisma.DiscussionReplyWhereUniqueInput[]
  connect?: Prisma.DiscussionReplyWhereUniqueInput | Prisma.DiscussionReplyWhereUniqueInput[]
  update?: Prisma.DiscussionReplyUpdateWithWhereUniqueWithoutAuthorInput | Prisma.DiscussionReplyUpdateWithWhereUniqueWithoutAuthorInput[]
  updateMany?: Prisma.DiscussionReplyUpdateManyWithWhereWithoutAuthorInput | Prisma.DiscussionReplyUpdateManyWithWhereWithoutAuthorInput[]
  deleteMany?: Prisma.DiscussionReplyScalarWhereInput | Prisma.DiscussionReplyScalarWhereInput[]
}

export type DiscussionReplyUncheckedUpdateManyWithoutAuthorNestedInput = {
  create?: Prisma.XOR<Prisma.DiscussionReplyCreateWithoutAuthorInput, Prisma.DiscussionReplyUncheckedCreateWithoutAuthorInput> | Prisma.DiscussionReplyCreateWithoutAuthorInput[] | Prisma.DiscussionReplyUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?: Prisma.DiscussionReplyCreateOrConnectWithoutAuthorInput | Prisma.DiscussionReplyCreateOrConnectWithoutAuthorInput[]
  upsert?: Prisma.DiscussionReplyUpsertWithWhereUniqueWithoutAuthorInput | Prisma.DiscussionReplyUpsertWithWhereUniqueWithoutAuthorInput[]
  createMany?: Prisma.DiscussionReplyCreateManyAuthorInputEnvelope
  set?: Prisma.DiscussionReplyWhereUniqueInput | Prisma.DiscussionReplyWhereUniqueInput[]
  disconnect?: Prisma.DiscussionReplyWhereUniqueInput | Prisma.DiscussionReplyWhereUniqueInput[]
  delete?: Prisma.DiscussionReplyWhereUniqueInput | Prisma.DiscussionReplyWhereUniqueInput[]
  connect?: Prisma.DiscussionReplyWhereUniqueInput | Prisma.DiscussionReplyWhereUniqueInput[]
  update?: Prisma.DiscussionReplyUpdateWithWhereUniqueWithoutAuthorInput | Prisma.DiscussionReplyUpdateWithWhereUniqueWithoutAuthorInput[]
  updateMany?: Prisma.DiscussionReplyUpdateManyWithWhereWithoutAuthorInput | Prisma.DiscussionReplyUpdateManyWithWhereWithoutAuthorInput[]
  deleteMany?: Prisma.DiscussionReplyScalarWhereInput | Prisma.DiscussionReplyScalarWhereInput[]
}

export type DiscussionReplyCreateNestedManyWithoutThreadInput = {
  create?: Prisma.XOR<Prisma.DiscussionReplyCreateWithoutThreadInput, Prisma.DiscussionReplyUncheckedCreateWithoutThreadInput> | Prisma.DiscussionReplyCreateWithoutThreadInput[] | Prisma.DiscussionReplyUncheckedCreateWithoutThreadInput[]
  connectOrCreate?: Prisma.DiscussionReplyCreateOrConnectWithoutThreadInput | Prisma.DiscussionReplyCreateOrConnectWithoutThreadInput[]
  createMany?: Prisma.DiscussionReplyCreateManyThreadInputEnvelope
  connect?: Prisma.DiscussionReplyWhereUniqueInput | Prisma.DiscussionReplyWhereUniqueInput[]
}

export type DiscussionReplyUncheckedCreateNestedManyWithoutThreadInput = {
  create?: Prisma.XOR<Prisma.DiscussionReplyCreateWithoutThreadInput, Prisma.DiscussionReplyUncheckedCreateWithoutThreadInput> | Prisma.DiscussionReplyCreateWithoutThreadInput[] | Prisma.DiscussionReplyUncheckedCreateWithoutThreadInput[]
  connectOrCreate?: Prisma.DiscussionReplyCreateOrConnectWithoutThreadInput | Prisma.DiscussionReplyCreateOrConnectWithoutThreadInput[]
  createMany?: Prisma.DiscussionReplyCreateManyThreadInputEnvelope
  connect?: Prisma.DiscussionReplyWhereUniqueInput | Prisma.DiscussionReplyWhereUniqueInput[]
}

export type DiscussionReplyUpdateManyWithoutThreadNestedInput = {
  create?: Prisma.XOR<Prisma.DiscussionReplyCreateWithoutThreadInput, Prisma.DiscussionReplyUncheckedCreateWithoutThreadInput> | Prisma.DiscussionReplyCreateWithoutThreadInput[] | Prisma.DiscussionReplyUncheckedCreateWithoutThreadInput[]
  connectOrCreate?: Prisma.DiscussionReplyCreateOrConnectWithoutThreadInput | Prisma.DiscussionReplyCreateOrConnectWithoutThreadInput[]
  upsert?: Prisma.DiscussionReplyUpsertWithWhereUniqueWithoutThreadInput | Prisma.DiscussionReplyUpsertWithWhereUniqueWithoutThreadInput[]
  createMany?: Prisma.DiscussionReplyCreateManyThreadInputEnvelope
  set?: Prisma.DiscussionReplyWhereUniqueInput | Prisma.DiscussionReplyWhereUniqueInput[]
  disconnect?: Prisma.DiscussionReplyWhereUniqueInput | Prisma.DiscussionReplyWhereUniqueInput[]
  delete?: Prisma.DiscussionReplyWhereUniqueInput | Prisma.DiscussionReplyWhereUniqueInput[]
  connect?: Prisma.DiscussionReplyWhereUniqueInput | Prisma.DiscussionReplyWhereUniqueInput[]
  update?: Prisma.DiscussionReplyUpdateWithWhereUniqueWithoutThreadInput | Prisma.DiscussionReplyUpdateWithWhereUniqueWithoutThreadInput[]
  updateMany?: Prisma.DiscussionReplyUpdateManyWithWhereWithoutThreadInput | Prisma.DiscussionReplyUpdateManyWithWhereWithoutThreadInput[]
  deleteMany?: Prisma.DiscussionReplyScalarWhereInput | Prisma.DiscussionReplyScalarWhereInput[]
}

export type DiscussionReplyUncheckedUpdateManyWithoutThreadNestedInput = {
  create?: Prisma.XOR<Prisma.DiscussionReplyCreateWithoutThreadInput, Prisma.DiscussionReplyUncheckedCreateWithoutThreadInput> | Prisma.DiscussionReplyCreateWithoutThreadInput[] | Prisma.DiscussionReplyUncheckedCreateWithoutThreadInput[]
  connectOrCreate?: Prisma.DiscussionReplyCreateOrConnectWithoutThreadInput | Prisma.DiscussionReplyCreateOrConnectWithoutThreadInput[]
  upsert?: Prisma.DiscussionReplyUpsertWithWhereUniqueWithoutThreadInput | Prisma.DiscussionReplyUpsertWithWhereUniqueWithoutThreadInput[]
  createMany?: Prisma.DiscussionReplyCreateManyThreadInputEnvelope
  set?: Prisma.DiscussionReplyWhereUniqueInput | Prisma.DiscussionReplyWhereUniqueInput[]
  disconnect?: Prisma.DiscussionReplyWhereUniqueInput | Prisma.DiscussionReplyWhereUniqueInput[]
  delete?: Prisma.DiscussionReplyWhereUniqueInput | Prisma.DiscussionReplyWhereUniqueInput[]
  connect?: Prisma.DiscussionReplyWhereUniqueInput | Prisma.DiscussionReplyWhereUniqueInput[]
  update?: Prisma.DiscussionReplyUpdateWithWhereUniqueWithoutThreadInput | Prisma.DiscussionReplyUpdateWithWhereUniqueWithoutThreadInput[]
  updateMany?: Prisma.DiscussionReplyUpdateManyWithWhereWithoutThreadInput | Prisma.DiscussionReplyUpdateManyWithWhereWithoutThreadInput[]
  deleteMany?: Prisma.DiscussionReplyScalarWhereInput | Prisma.DiscussionReplyScalarWhereInput[]
}

export type DiscussionReplyCreateWithoutAuthorInput = {
  id?: string
  body: string
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  thread: Prisma.DiscussionThreadCreateNestedOneWithoutReplyInput
}

export type DiscussionReplyUncheckedCreateWithoutAuthorInput = {
  id?: string
  threadId: string
  body: string
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type DiscussionReplyCreateOrConnectWithoutAuthorInput = {
  where: Prisma.DiscussionReplyWhereUniqueInput
  create: Prisma.XOR<Prisma.DiscussionReplyCreateWithoutAuthorInput, Prisma.DiscussionReplyUncheckedCreateWithoutAuthorInput>
}

export type DiscussionReplyCreateManyAuthorInputEnvelope = {
  data: Prisma.DiscussionReplyCreateManyAuthorInput | Prisma.DiscussionReplyCreateManyAuthorInput[]
  skipDuplicates?: boolean
}

export type DiscussionReplyUpsertWithWhereUniqueWithoutAuthorInput = {
  where: Prisma.DiscussionReplyWhereUniqueInput
  update: Prisma.XOR<Prisma.DiscussionReplyUpdateWithoutAuthorInput, Prisma.DiscussionReplyUncheckedUpdateWithoutAuthorInput>
  create: Prisma.XOR<Prisma.DiscussionReplyCreateWithoutAuthorInput, Prisma.DiscussionReplyUncheckedCreateWithoutAuthorInput>
}

export type DiscussionReplyUpdateWithWhereUniqueWithoutAuthorInput = {
  where: Prisma.DiscussionReplyWhereUniqueInput
  data: Prisma.XOR<Prisma.DiscussionReplyUpdateWithoutAuthorInput, Prisma.DiscussionReplyUncheckedUpdateWithoutAuthorInput>
}

export type DiscussionReplyUpdateManyWithWhereWithoutAuthorInput = {
  where: Prisma.DiscussionReplyScalarWhereInput
  data: Prisma.XOR<Prisma.DiscussionReplyUpdateManyMutationInput, Prisma.DiscussionReplyUncheckedUpdateManyWithoutAuthorInput>
}

export type DiscussionReplyScalarWhereInput = {
  AND?: Prisma.DiscussionReplyScalarWhereInput | Prisma.DiscussionReplyScalarWhereInput[]
  OR?: Prisma.DiscussionReplyScalarWhereInput[]
  NOT?: Prisma.DiscussionReplyScalarWhereInput | Prisma.DiscussionReplyScalarWhereInput[]
  id?: Prisma.StringFilter<"DiscussionReply"> | string
  threadId?: Prisma.StringFilter<"DiscussionReply"> | string
  authorId?: Prisma.StringFilter<"DiscussionReply"> | string
  body?: Prisma.StringFilter<"DiscussionReply"> | string
  createdAt?: Prisma.DateTimeFilter<"DiscussionReply"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"DiscussionReply"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"DiscussionReply"> | Date | string | null
}

export type DiscussionReplyCreateWithoutThreadInput = {
  id?: string
  body: string
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  author: Prisma.UserCreateNestedOneWithoutDiscussionReplyInput
}

export type DiscussionReplyUncheckedCreateWithoutThreadInput = {
  id?: string
  authorId: string
  body: string
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type DiscussionReplyCreateOrConnectWithoutThreadInput = {
  where: Prisma.DiscussionReplyWhereUniqueInput
  create: Prisma.XOR<Prisma.DiscussionReplyCreateWithoutThreadInput, Prisma.DiscussionReplyUncheckedCreateWithoutThreadInput>
}

export type DiscussionReplyCreateManyThreadInputEnvelope = {
  data: Prisma.DiscussionReplyCreateManyThreadInput | Prisma.DiscussionReplyCreateManyThreadInput[]
  skipDuplicates?: boolean
}

export type DiscussionReplyUpsertWithWhereUniqueWithoutThreadInput = {
  where: Prisma.DiscussionReplyWhereUniqueInput
  update: Prisma.XOR<Prisma.DiscussionReplyUpdateWithoutThreadInput, Prisma.DiscussionReplyUncheckedUpdateWithoutThreadInput>
  create: Prisma.XOR<Prisma.DiscussionReplyCreateWithoutThreadInput, Prisma.DiscussionReplyUncheckedCreateWithoutThreadInput>
}

export type DiscussionReplyUpdateWithWhereUniqueWithoutThreadInput = {
  where: Prisma.DiscussionReplyWhereUniqueInput
  data: Prisma.XOR<Prisma.DiscussionReplyUpdateWithoutThreadInput, Prisma.DiscussionReplyUncheckedUpdateWithoutThreadInput>
}

export type DiscussionReplyUpdateManyWithWhereWithoutThreadInput = {
  where: Prisma.DiscussionReplyScalarWhereInput
  data: Prisma.XOR<Prisma.DiscussionReplyUpdateManyMutationInput, Prisma.DiscussionReplyUncheckedUpdateManyWithoutThreadInput>
}

export type DiscussionReplyCreateManyAuthorInput = {
  id?: string
  threadId: string
  body: string
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type DiscussionReplyUpdateWithoutAuthorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  body?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  thread?: Prisma.DiscussionThreadUpdateOneRequiredWithoutReplyNestedInput
}

export type DiscussionReplyUncheckedUpdateWithoutAuthorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  threadId?: Prisma.StringFieldUpdateOperationsInput | string
  body?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type DiscussionReplyUncheckedUpdateManyWithoutAuthorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  threadId?: Prisma.StringFieldUpdateOperationsInput | string
  body?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type DiscussionReplyCreateManyThreadInput = {
  id?: string
  authorId: string
  body: string
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type DiscussionReplyUpdateWithoutThreadInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  body?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  author?: Prisma.UserUpdateOneRequiredWithoutDiscussionReplyNestedInput
}

export type DiscussionReplyUncheckedUpdateWithoutThreadInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  body?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type DiscussionReplyUncheckedUpdateManyWithoutThreadInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  body?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type DiscussionReplySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  threadId?: boolean
  authorId?: boolean
  body?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  thread?: boolean | Prisma.DiscussionThreadDefaultArgs<ExtArgs>
  author?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["discussionReply"]>

export type DiscussionReplySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  threadId?: boolean
  authorId?: boolean
  body?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  thread?: boolean | Prisma.DiscussionThreadDefaultArgs<ExtArgs>
  author?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["discussionReply"]>

export type DiscussionReplySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  threadId?: boolean
  authorId?: boolean
  body?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  thread?: boolean | Prisma.DiscussionThreadDefaultArgs<ExtArgs>
  author?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["discussionReply"]>

export type DiscussionReplySelectScalar = {
  id?: boolean
  threadId?: boolean
  authorId?: boolean
  body?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
}

export type DiscussionReplyOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "threadId" | "authorId" | "body" | "createdAt" | "updatedAt" | "deletedAt", ExtArgs["result"]["discussionReply"]>
export type DiscussionReplyInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  thread?: boolean | Prisma.DiscussionThreadDefaultArgs<ExtArgs>
  author?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type DiscussionReplyIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  thread?: boolean | Prisma.DiscussionThreadDefaultArgs<ExtArgs>
  author?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type DiscussionReplyIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  thread?: boolean | Prisma.DiscussionThreadDefaultArgs<ExtArgs>
  author?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $DiscussionReplyPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "DiscussionReply"
  objects: {
    thread: Prisma.$DiscussionThreadPayload<ExtArgs>
    author: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    threadId: string
    authorId: string
    body: string
    createdAt: Date
    updatedAt: Date
    deletedAt: Date | null
  }, ExtArgs["result"]["discussionReply"]>
  composites: {}
}

export type DiscussionReplyGetPayload<S extends boolean | null | undefined | DiscussionReplyDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DiscussionReplyPayload, S>

export type DiscussionReplyCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DiscussionReplyFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DiscussionReplyCountAggregateInputType | true
  }

export interface DiscussionReplyDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['DiscussionReply'], meta: { name: 'DiscussionReply' } }
  /**
   * Find zero or one DiscussionReply that matches the filter.
   * @param {DiscussionReplyFindUniqueArgs} args - Arguments to find a DiscussionReply
   * @example
   * // Get one DiscussionReply
   * const discussionReply = await prisma.discussionReply.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DiscussionReplyFindUniqueArgs>(args: Prisma.SelectSubset<T, DiscussionReplyFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DiscussionReplyClient<runtime.Types.Result.GetResult<Prisma.$DiscussionReplyPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one DiscussionReply that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DiscussionReplyFindUniqueOrThrowArgs} args - Arguments to find a DiscussionReply
   * @example
   * // Get one DiscussionReply
   * const discussionReply = await prisma.discussionReply.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DiscussionReplyFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DiscussionReplyFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DiscussionReplyClient<runtime.Types.Result.GetResult<Prisma.$DiscussionReplyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DiscussionReply that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DiscussionReplyFindFirstArgs} args - Arguments to find a DiscussionReply
   * @example
   * // Get one DiscussionReply
   * const discussionReply = await prisma.discussionReply.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DiscussionReplyFindFirstArgs>(args?: Prisma.SelectSubset<T, DiscussionReplyFindFirstArgs<ExtArgs>>): Prisma.Prisma__DiscussionReplyClient<runtime.Types.Result.GetResult<Prisma.$DiscussionReplyPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DiscussionReply that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DiscussionReplyFindFirstOrThrowArgs} args - Arguments to find a DiscussionReply
   * @example
   * // Get one DiscussionReply
   * const discussionReply = await prisma.discussionReply.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DiscussionReplyFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DiscussionReplyFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DiscussionReplyClient<runtime.Types.Result.GetResult<Prisma.$DiscussionReplyPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more DiscussionReplies that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DiscussionReplyFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all DiscussionReplies
   * const discussionReplies = await prisma.discussionReply.findMany()
   * 
   * // Get first 10 DiscussionReplies
   * const discussionReplies = await prisma.discussionReply.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const discussionReplyWithIdOnly = await prisma.discussionReply.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DiscussionReplyFindManyArgs>(args?: Prisma.SelectSubset<T, DiscussionReplyFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DiscussionReplyPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a DiscussionReply.
   * @param {DiscussionReplyCreateArgs} args - Arguments to create a DiscussionReply.
   * @example
   * // Create one DiscussionReply
   * const DiscussionReply = await prisma.discussionReply.create({
   *   data: {
   *     // ... data to create a DiscussionReply
   *   }
   * })
   * 
   */
  create<T extends DiscussionReplyCreateArgs>(args: Prisma.SelectSubset<T, DiscussionReplyCreateArgs<ExtArgs>>): Prisma.Prisma__DiscussionReplyClient<runtime.Types.Result.GetResult<Prisma.$DiscussionReplyPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many DiscussionReplies.
   * @param {DiscussionReplyCreateManyArgs} args - Arguments to create many DiscussionReplies.
   * @example
   * // Create many DiscussionReplies
   * const discussionReply = await prisma.discussionReply.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DiscussionReplyCreateManyArgs>(args?: Prisma.SelectSubset<T, DiscussionReplyCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many DiscussionReplies and returns the data saved in the database.
   * @param {DiscussionReplyCreateManyAndReturnArgs} args - Arguments to create many DiscussionReplies.
   * @example
   * // Create many DiscussionReplies
   * const discussionReply = await prisma.discussionReply.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many DiscussionReplies and only return the `id`
   * const discussionReplyWithIdOnly = await prisma.discussionReply.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DiscussionReplyCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DiscussionReplyCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DiscussionReplyPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a DiscussionReply.
   * @param {DiscussionReplyDeleteArgs} args - Arguments to delete one DiscussionReply.
   * @example
   * // Delete one DiscussionReply
   * const DiscussionReply = await prisma.discussionReply.delete({
   *   where: {
   *     // ... filter to delete one DiscussionReply
   *   }
   * })
   * 
   */
  delete<T extends DiscussionReplyDeleteArgs>(args: Prisma.SelectSubset<T, DiscussionReplyDeleteArgs<ExtArgs>>): Prisma.Prisma__DiscussionReplyClient<runtime.Types.Result.GetResult<Prisma.$DiscussionReplyPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one DiscussionReply.
   * @param {DiscussionReplyUpdateArgs} args - Arguments to update one DiscussionReply.
   * @example
   * // Update one DiscussionReply
   * const discussionReply = await prisma.discussionReply.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DiscussionReplyUpdateArgs>(args: Prisma.SelectSubset<T, DiscussionReplyUpdateArgs<ExtArgs>>): Prisma.Prisma__DiscussionReplyClient<runtime.Types.Result.GetResult<Prisma.$DiscussionReplyPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more DiscussionReplies.
   * @param {DiscussionReplyDeleteManyArgs} args - Arguments to filter DiscussionReplies to delete.
   * @example
   * // Delete a few DiscussionReplies
   * const { count } = await prisma.discussionReply.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DiscussionReplyDeleteManyArgs>(args?: Prisma.SelectSubset<T, DiscussionReplyDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DiscussionReplies.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DiscussionReplyUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many DiscussionReplies
   * const discussionReply = await prisma.discussionReply.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DiscussionReplyUpdateManyArgs>(args: Prisma.SelectSubset<T, DiscussionReplyUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DiscussionReplies and returns the data updated in the database.
   * @param {DiscussionReplyUpdateManyAndReturnArgs} args - Arguments to update many DiscussionReplies.
   * @example
   * // Update many DiscussionReplies
   * const discussionReply = await prisma.discussionReply.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more DiscussionReplies and only return the `id`
   * const discussionReplyWithIdOnly = await prisma.discussionReply.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DiscussionReplyUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DiscussionReplyUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DiscussionReplyPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one DiscussionReply.
   * @param {DiscussionReplyUpsertArgs} args - Arguments to update or create a DiscussionReply.
   * @example
   * // Update or create a DiscussionReply
   * const discussionReply = await prisma.discussionReply.upsert({
   *   create: {
   *     // ... data to create a DiscussionReply
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the DiscussionReply we want to update
   *   }
   * })
   */
  upsert<T extends DiscussionReplyUpsertArgs>(args: Prisma.SelectSubset<T, DiscussionReplyUpsertArgs<ExtArgs>>): Prisma.Prisma__DiscussionReplyClient<runtime.Types.Result.GetResult<Prisma.$DiscussionReplyPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of DiscussionReplies.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DiscussionReplyCountArgs} args - Arguments to filter DiscussionReplies to count.
   * @example
   * // Count the number of DiscussionReplies
   * const count = await prisma.discussionReply.count({
   *   where: {
   *     // ... the filter for the DiscussionReplies we want to count
   *   }
   * })
  **/
  count<T extends DiscussionReplyCountArgs>(
    args?: Prisma.Subset<T, DiscussionReplyCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DiscussionReplyCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a DiscussionReply.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DiscussionReplyAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DiscussionReplyAggregateArgs>(args: Prisma.Subset<T, DiscussionReplyAggregateArgs>): Prisma.PrismaPromise<GetDiscussionReplyAggregateType<T>>

  /**
   * Group by DiscussionReply.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DiscussionReplyGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DiscussionReplyGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DiscussionReplyGroupByArgs['orderBy'] }
      : { orderBy?: DiscussionReplyGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DiscussionReplyGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDiscussionReplyGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the DiscussionReply model
 */
readonly fields: DiscussionReplyFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for DiscussionReply.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DiscussionReplyClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  thread<T extends Prisma.DiscussionThreadDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DiscussionThreadDefaultArgs<ExtArgs>>): Prisma.Prisma__DiscussionThreadClient<runtime.Types.Result.GetResult<Prisma.$DiscussionThreadPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  author<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the DiscussionReply model
 */
export interface DiscussionReplyFieldRefs {
  readonly id: Prisma.FieldRef<"DiscussionReply", 'String'>
  readonly threadId: Prisma.FieldRef<"DiscussionReply", 'String'>
  readonly authorId: Prisma.FieldRef<"DiscussionReply", 'String'>
  readonly body: Prisma.FieldRef<"DiscussionReply", 'String'>
  readonly createdAt: Prisma.FieldRef<"DiscussionReply", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"DiscussionReply", 'DateTime'>
  readonly deletedAt: Prisma.FieldRef<"DiscussionReply", 'DateTime'>
}
    

// Custom InputTypes
/**
 * DiscussionReply findUnique
 */
export type DiscussionReplyFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DiscussionReply
   */
  select?: Prisma.DiscussionReplySelect<ExtArgs> | null
  /**
   * Omit specific fields from the DiscussionReply
   */
  omit?: Prisma.DiscussionReplyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DiscussionReplyInclude<ExtArgs> | null
  /**
   * Filter, which DiscussionReply to fetch.
   */
  where: Prisma.DiscussionReplyWhereUniqueInput
}

/**
 * DiscussionReply findUniqueOrThrow
 */
export type DiscussionReplyFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DiscussionReply
   */
  select?: Prisma.DiscussionReplySelect<ExtArgs> | null
  /**
   * Omit specific fields from the DiscussionReply
   */
  omit?: Prisma.DiscussionReplyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DiscussionReplyInclude<ExtArgs> | null
  /**
   * Filter, which DiscussionReply to fetch.
   */
  where: Prisma.DiscussionReplyWhereUniqueInput
}

/**
 * DiscussionReply findFirst
 */
export type DiscussionReplyFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DiscussionReply
   */
  select?: Prisma.DiscussionReplySelect<ExtArgs> | null
  /**
   * Omit specific fields from the DiscussionReply
   */
  omit?: Prisma.DiscussionReplyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DiscussionReplyInclude<ExtArgs> | null
  /**
   * Filter, which DiscussionReply to fetch.
   */
  where?: Prisma.DiscussionReplyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DiscussionReplies to fetch.
   */
  orderBy?: Prisma.DiscussionReplyOrderByWithRelationInput | Prisma.DiscussionReplyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DiscussionReplies.
   */
  cursor?: Prisma.DiscussionReplyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DiscussionReplies from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DiscussionReplies.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DiscussionReplies.
   */
  distinct?: Prisma.DiscussionReplyScalarFieldEnum | Prisma.DiscussionReplyScalarFieldEnum[]
}

/**
 * DiscussionReply findFirstOrThrow
 */
export type DiscussionReplyFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DiscussionReply
   */
  select?: Prisma.DiscussionReplySelect<ExtArgs> | null
  /**
   * Omit specific fields from the DiscussionReply
   */
  omit?: Prisma.DiscussionReplyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DiscussionReplyInclude<ExtArgs> | null
  /**
   * Filter, which DiscussionReply to fetch.
   */
  where?: Prisma.DiscussionReplyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DiscussionReplies to fetch.
   */
  orderBy?: Prisma.DiscussionReplyOrderByWithRelationInput | Prisma.DiscussionReplyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DiscussionReplies.
   */
  cursor?: Prisma.DiscussionReplyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DiscussionReplies from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DiscussionReplies.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DiscussionReplies.
   */
  distinct?: Prisma.DiscussionReplyScalarFieldEnum | Prisma.DiscussionReplyScalarFieldEnum[]
}

/**
 * DiscussionReply findMany
 */
export type DiscussionReplyFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DiscussionReply
   */
  select?: Prisma.DiscussionReplySelect<ExtArgs> | null
  /**
   * Omit specific fields from the DiscussionReply
   */
  omit?: Prisma.DiscussionReplyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DiscussionReplyInclude<ExtArgs> | null
  /**
   * Filter, which DiscussionReplies to fetch.
   */
  where?: Prisma.DiscussionReplyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DiscussionReplies to fetch.
   */
  orderBy?: Prisma.DiscussionReplyOrderByWithRelationInput | Prisma.DiscussionReplyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing DiscussionReplies.
   */
  cursor?: Prisma.DiscussionReplyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DiscussionReplies from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DiscussionReplies.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DiscussionReplies.
   */
  distinct?: Prisma.DiscussionReplyScalarFieldEnum | Prisma.DiscussionReplyScalarFieldEnum[]
}

/**
 * DiscussionReply create
 */
export type DiscussionReplyCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DiscussionReply
   */
  select?: Prisma.DiscussionReplySelect<ExtArgs> | null
  /**
   * Omit specific fields from the DiscussionReply
   */
  omit?: Prisma.DiscussionReplyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DiscussionReplyInclude<ExtArgs> | null
  /**
   * The data needed to create a DiscussionReply.
   */
  data: Prisma.XOR<Prisma.DiscussionReplyCreateInput, Prisma.DiscussionReplyUncheckedCreateInput>
}

/**
 * DiscussionReply createMany
 */
export type DiscussionReplyCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many DiscussionReplies.
   */
  data: Prisma.DiscussionReplyCreateManyInput | Prisma.DiscussionReplyCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * DiscussionReply createManyAndReturn
 */
export type DiscussionReplyCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DiscussionReply
   */
  select?: Prisma.DiscussionReplySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DiscussionReply
   */
  omit?: Prisma.DiscussionReplyOmit<ExtArgs> | null
  /**
   * The data used to create many DiscussionReplies.
   */
  data: Prisma.DiscussionReplyCreateManyInput | Prisma.DiscussionReplyCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DiscussionReplyIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * DiscussionReply update
 */
export type DiscussionReplyUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DiscussionReply
   */
  select?: Prisma.DiscussionReplySelect<ExtArgs> | null
  /**
   * Omit specific fields from the DiscussionReply
   */
  omit?: Prisma.DiscussionReplyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DiscussionReplyInclude<ExtArgs> | null
  /**
   * The data needed to update a DiscussionReply.
   */
  data: Prisma.XOR<Prisma.DiscussionReplyUpdateInput, Prisma.DiscussionReplyUncheckedUpdateInput>
  /**
   * Choose, which DiscussionReply to update.
   */
  where: Prisma.DiscussionReplyWhereUniqueInput
}

/**
 * DiscussionReply updateMany
 */
export type DiscussionReplyUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update DiscussionReplies.
   */
  data: Prisma.XOR<Prisma.DiscussionReplyUpdateManyMutationInput, Prisma.DiscussionReplyUncheckedUpdateManyInput>
  /**
   * Filter which DiscussionReplies to update
   */
  where?: Prisma.DiscussionReplyWhereInput
  /**
   * Limit how many DiscussionReplies to update.
   */
  limit?: number
}

/**
 * DiscussionReply updateManyAndReturn
 */
export type DiscussionReplyUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DiscussionReply
   */
  select?: Prisma.DiscussionReplySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DiscussionReply
   */
  omit?: Prisma.DiscussionReplyOmit<ExtArgs> | null
  /**
   * The data used to update DiscussionReplies.
   */
  data: Prisma.XOR<Prisma.DiscussionReplyUpdateManyMutationInput, Prisma.DiscussionReplyUncheckedUpdateManyInput>
  /**
   * Filter which DiscussionReplies to update
   */
  where?: Prisma.DiscussionReplyWhereInput
  /**
   * Limit how many DiscussionReplies to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DiscussionReplyIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * DiscussionReply upsert
 */
export type DiscussionReplyUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DiscussionReply
   */
  select?: Prisma.DiscussionReplySelect<ExtArgs> | null
  /**
   * Omit specific fields from the DiscussionReply
   */
  omit?: Prisma.DiscussionReplyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DiscussionReplyInclude<ExtArgs> | null
  /**
   * The filter to search for the DiscussionReply to update in case it exists.
   */
  where: Prisma.DiscussionReplyWhereUniqueInput
  /**
   * In case the DiscussionReply found by the `where` argument doesn't exist, create a new DiscussionReply with this data.
   */
  create: Prisma.XOR<Prisma.DiscussionReplyCreateInput, Prisma.DiscussionReplyUncheckedCreateInput>
  /**
   * In case the DiscussionReply was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DiscussionReplyUpdateInput, Prisma.DiscussionReplyUncheckedUpdateInput>
}

/**
 * DiscussionReply delete
 */
export type DiscussionReplyDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DiscussionReply
   */
  select?: Prisma.DiscussionReplySelect<ExtArgs> | null
  /**
   * Omit specific fields from the DiscussionReply
   */
  omit?: Prisma.DiscussionReplyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DiscussionReplyInclude<ExtArgs> | null
  /**
   * Filter which DiscussionReply to delete.
   */
  where: Prisma.DiscussionReplyWhereUniqueInput
}

/**
 * DiscussionReply deleteMany
 */
export type DiscussionReplyDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DiscussionReplies to delete
   */
  where?: Prisma.DiscussionReplyWhereInput
  /**
   * Limit how many DiscussionReplies to delete.
   */
  limit?: number
}

/**
 * DiscussionReply without action
 */
export type DiscussionReplyDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DiscussionReply
   */
  select?: Prisma.DiscussionReplySelect<ExtArgs> | null
  /**
   * Omit specific fields from the DiscussionReply
   */
  omit?: Prisma.DiscussionReplyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DiscussionReplyInclude<ExtArgs> | null
}
