
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Ebook` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Ebook
 * A document in the member library: broker research, articles, guides.
 * The file itself lives in the upload store and is served only through an
 * authenticated route, so a link alone does not hand out the document.
 */
export type EbookModel = runtime.Types.Result.DefaultSelection<Prisma.$EbookPayload>

export type AggregateEbook = {
  _count: EbookCountAggregateOutputType | null
  _avg: EbookAvgAggregateOutputType | null
  _sum: EbookSumAggregateOutputType | null
  _min: EbookMinAggregateOutputType | null
  _max: EbookMaxAggregateOutputType | null
}

export type EbookAvgAggregateOutputType = {
  fileSizeBytes: number | null
}

export type EbookSumAggregateOutputType = {
  fileSizeBytes: number | null
}

export type EbookMinAggregateOutputType = {
  id: string | null
  title: string | null
  tag: $Enums.EbookTagKind | null
  summary: string | null
  source: string | null
  author: string | null
  publishedAt: Date | null
  fileName: string | null
  fileSizeBytes: number | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
}

export type EbookMaxAggregateOutputType = {
  id: string | null
  title: string | null
  tag: $Enums.EbookTagKind | null
  summary: string | null
  source: string | null
  author: string | null
  publishedAt: Date | null
  fileName: string | null
  fileSizeBytes: number | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
}

export type EbookCountAggregateOutputType = {
  id: number
  title: number
  tag: number
  summary: number
  source: number
  author: number
  tickers: number
  publishedAt: number
  fileName: number
  fileSizeBytes: number
  createdAt: number
  updatedAt: number
  deletedAt: number
  _all: number
}


export type EbookAvgAggregateInputType = {
  fileSizeBytes?: true
}

export type EbookSumAggregateInputType = {
  fileSizeBytes?: true
}

export type EbookMinAggregateInputType = {
  id?: true
  title?: true
  tag?: true
  summary?: true
  source?: true
  author?: true
  publishedAt?: true
  fileName?: true
  fileSizeBytes?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
}

export type EbookMaxAggregateInputType = {
  id?: true
  title?: true
  tag?: true
  summary?: true
  source?: true
  author?: true
  publishedAt?: true
  fileName?: true
  fileSizeBytes?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
}

export type EbookCountAggregateInputType = {
  id?: true
  title?: true
  tag?: true
  summary?: true
  source?: true
  author?: true
  tickers?: true
  publishedAt?: true
  fileName?: true
  fileSizeBytes?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
  _all?: true
}

export type EbookAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Ebook to aggregate.
   */
  where?: Prisma.EbookWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Ebooks to fetch.
   */
  orderBy?: Prisma.EbookOrderByWithRelationInput | Prisma.EbookOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.EbookWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Ebooks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Ebooks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Ebooks
  **/
  _count?: true | EbookCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: EbookAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: EbookSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: EbookMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: EbookMaxAggregateInputType
}

export type GetEbookAggregateType<T extends EbookAggregateArgs> = {
      [P in keyof T & keyof AggregateEbook]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEbook[P]>
    : Prisma.GetScalarType<T[P], AggregateEbook[P]>
}




export type EbookGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EbookWhereInput
  orderBy?: Prisma.EbookOrderByWithAggregationInput | Prisma.EbookOrderByWithAggregationInput[]
  by: Prisma.EbookScalarFieldEnum[] | Prisma.EbookScalarFieldEnum
  having?: Prisma.EbookScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: EbookCountAggregateInputType | true
  _avg?: EbookAvgAggregateInputType
  _sum?: EbookSumAggregateInputType
  _min?: EbookMinAggregateInputType
  _max?: EbookMaxAggregateInputType
}

export type EbookGroupByOutputType = {
  id: string
  title: string
  tag: $Enums.EbookTagKind
  summary: string | null
  source: string
  author: string | null
  tickers: string[]
  publishedAt: Date
  fileName: string
  fileSizeBytes: number
  createdAt: Date
  updatedAt: Date
  deletedAt: Date | null
  _count: EbookCountAggregateOutputType | null
  _avg: EbookAvgAggregateOutputType | null
  _sum: EbookSumAggregateOutputType | null
  _min: EbookMinAggregateOutputType | null
  _max: EbookMaxAggregateOutputType | null
}

export type GetEbookGroupByPayload<T extends EbookGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<EbookGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof EbookGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], EbookGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], EbookGroupByOutputType[P]>
      }
    >
  >



export type EbookWhereInput = {
  AND?: Prisma.EbookWhereInput | Prisma.EbookWhereInput[]
  OR?: Prisma.EbookWhereInput[]
  NOT?: Prisma.EbookWhereInput | Prisma.EbookWhereInput[]
  id?: Prisma.StringFilter<"Ebook"> | string
  title?: Prisma.StringFilter<"Ebook"> | string
  tag?: Prisma.EnumEbookTagKindFilter<"Ebook"> | $Enums.EbookTagKind
  summary?: Prisma.StringNullableFilter<"Ebook"> | string | null
  source?: Prisma.StringFilter<"Ebook"> | string
  author?: Prisma.StringNullableFilter<"Ebook"> | string | null
  tickers?: Prisma.StringNullableListFilter<"Ebook">
  publishedAt?: Prisma.DateTimeFilter<"Ebook"> | Date | string
  fileName?: Prisma.StringFilter<"Ebook"> | string
  fileSizeBytes?: Prisma.IntFilter<"Ebook"> | number
  createdAt?: Prisma.DateTimeFilter<"Ebook"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Ebook"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"Ebook"> | Date | string | null
}

export type EbookOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  tag?: Prisma.SortOrder
  summary?: Prisma.SortOrderInput | Prisma.SortOrder
  source?: Prisma.SortOrder
  author?: Prisma.SortOrderInput | Prisma.SortOrder
  tickers?: Prisma.SortOrder
  publishedAt?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  fileSizeBytes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
}

export type EbookWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.EbookWhereInput | Prisma.EbookWhereInput[]
  OR?: Prisma.EbookWhereInput[]
  NOT?: Prisma.EbookWhereInput | Prisma.EbookWhereInput[]
  title?: Prisma.StringFilter<"Ebook"> | string
  tag?: Prisma.EnumEbookTagKindFilter<"Ebook"> | $Enums.EbookTagKind
  summary?: Prisma.StringNullableFilter<"Ebook"> | string | null
  source?: Prisma.StringFilter<"Ebook"> | string
  author?: Prisma.StringNullableFilter<"Ebook"> | string | null
  tickers?: Prisma.StringNullableListFilter<"Ebook">
  publishedAt?: Prisma.DateTimeFilter<"Ebook"> | Date | string
  fileName?: Prisma.StringFilter<"Ebook"> | string
  fileSizeBytes?: Prisma.IntFilter<"Ebook"> | number
  createdAt?: Prisma.DateTimeFilter<"Ebook"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Ebook"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"Ebook"> | Date | string | null
}, "id">

export type EbookOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  tag?: Prisma.SortOrder
  summary?: Prisma.SortOrderInput | Prisma.SortOrder
  source?: Prisma.SortOrder
  author?: Prisma.SortOrderInput | Prisma.SortOrder
  tickers?: Prisma.SortOrder
  publishedAt?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  fileSizeBytes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.EbookCountOrderByAggregateInput
  _avg?: Prisma.EbookAvgOrderByAggregateInput
  _max?: Prisma.EbookMaxOrderByAggregateInput
  _min?: Prisma.EbookMinOrderByAggregateInput
  _sum?: Prisma.EbookSumOrderByAggregateInput
}

export type EbookScalarWhereWithAggregatesInput = {
  AND?: Prisma.EbookScalarWhereWithAggregatesInput | Prisma.EbookScalarWhereWithAggregatesInput[]
  OR?: Prisma.EbookScalarWhereWithAggregatesInput[]
  NOT?: Prisma.EbookScalarWhereWithAggregatesInput | Prisma.EbookScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Ebook"> | string
  title?: Prisma.StringWithAggregatesFilter<"Ebook"> | string
  tag?: Prisma.EnumEbookTagKindWithAggregatesFilter<"Ebook"> | $Enums.EbookTagKind
  summary?: Prisma.StringNullableWithAggregatesFilter<"Ebook"> | string | null
  source?: Prisma.StringWithAggregatesFilter<"Ebook"> | string
  author?: Prisma.StringNullableWithAggregatesFilter<"Ebook"> | string | null
  tickers?: Prisma.StringNullableListFilter<"Ebook">
  publishedAt?: Prisma.DateTimeWithAggregatesFilter<"Ebook"> | Date | string
  fileName?: Prisma.StringWithAggregatesFilter<"Ebook"> | string
  fileSizeBytes?: Prisma.IntWithAggregatesFilter<"Ebook"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Ebook"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Ebook"> | Date | string
  deletedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Ebook"> | Date | string | null
}

export type EbookCreateInput = {
  id?: string
  title: string
  tag: $Enums.EbookTagKind
  summary?: string | null
  source: string
  author?: string | null
  tickers?: Prisma.EbookCreatetickersInput | string[]
  publishedAt: Date | string
  fileName: string
  fileSizeBytes: number
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type EbookUncheckedCreateInput = {
  id?: string
  title: string
  tag: $Enums.EbookTagKind
  summary?: string | null
  source: string
  author?: string | null
  tickers?: Prisma.EbookCreatetickersInput | string[]
  publishedAt: Date | string
  fileName: string
  fileSizeBytes: number
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type EbookUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  tag?: Prisma.EnumEbookTagKindFieldUpdateOperationsInput | $Enums.EbookTagKind
  summary?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.StringFieldUpdateOperationsInput | string
  author?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tickers?: Prisma.EbookUpdatetickersInput | string[]
  publishedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileSizeBytes?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type EbookUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  tag?: Prisma.EnumEbookTagKindFieldUpdateOperationsInput | $Enums.EbookTagKind
  summary?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.StringFieldUpdateOperationsInput | string
  author?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tickers?: Prisma.EbookUpdatetickersInput | string[]
  publishedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileSizeBytes?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type EbookCreateManyInput = {
  id?: string
  title: string
  tag: $Enums.EbookTagKind
  summary?: string | null
  source: string
  author?: string | null
  tickers?: Prisma.EbookCreatetickersInput | string[]
  publishedAt: Date | string
  fileName: string
  fileSizeBytes: number
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type EbookUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  tag?: Prisma.EnumEbookTagKindFieldUpdateOperationsInput | $Enums.EbookTagKind
  summary?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.StringFieldUpdateOperationsInput | string
  author?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tickers?: Prisma.EbookUpdatetickersInput | string[]
  publishedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileSizeBytes?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type EbookUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  tag?: Prisma.EnumEbookTagKindFieldUpdateOperationsInput | $Enums.EbookTagKind
  summary?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.StringFieldUpdateOperationsInput | string
  author?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tickers?: Prisma.EbookUpdatetickersInput | string[]
  publishedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileSizeBytes?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type EbookCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  tag?: Prisma.SortOrder
  summary?: Prisma.SortOrder
  source?: Prisma.SortOrder
  author?: Prisma.SortOrder
  tickers?: Prisma.SortOrder
  publishedAt?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  fileSizeBytes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type EbookAvgOrderByAggregateInput = {
  fileSizeBytes?: Prisma.SortOrder
}

export type EbookMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  tag?: Prisma.SortOrder
  summary?: Prisma.SortOrder
  source?: Prisma.SortOrder
  author?: Prisma.SortOrder
  publishedAt?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  fileSizeBytes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type EbookMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  tag?: Prisma.SortOrder
  summary?: Prisma.SortOrder
  source?: Prisma.SortOrder
  author?: Prisma.SortOrder
  publishedAt?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  fileSizeBytes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type EbookSumOrderByAggregateInput = {
  fileSizeBytes?: Prisma.SortOrder
}

export type EbookCreatetickersInput = {
  set: string[]
}

export type EnumEbookTagKindFieldUpdateOperationsInput = {
  set?: $Enums.EbookTagKind
}

export type EbookUpdatetickersInput = {
  set?: string[]
  push?: string | string[]
}



export type EbookSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  tag?: boolean
  summary?: boolean
  source?: boolean
  author?: boolean
  tickers?: boolean
  publishedAt?: boolean
  fileName?: boolean
  fileSizeBytes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
}, ExtArgs["result"]["ebook"]>

export type EbookSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  tag?: boolean
  summary?: boolean
  source?: boolean
  author?: boolean
  tickers?: boolean
  publishedAt?: boolean
  fileName?: boolean
  fileSizeBytes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
}, ExtArgs["result"]["ebook"]>

export type EbookSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  tag?: boolean
  summary?: boolean
  source?: boolean
  author?: boolean
  tickers?: boolean
  publishedAt?: boolean
  fileName?: boolean
  fileSizeBytes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
}, ExtArgs["result"]["ebook"]>

export type EbookSelectScalar = {
  id?: boolean
  title?: boolean
  tag?: boolean
  summary?: boolean
  source?: boolean
  author?: boolean
  tickers?: boolean
  publishedAt?: boolean
  fileName?: boolean
  fileSizeBytes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
}

export type EbookOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "tag" | "summary" | "source" | "author" | "tickers" | "publishedAt" | "fileName" | "fileSizeBytes" | "createdAt" | "updatedAt" | "deletedAt", ExtArgs["result"]["ebook"]>

export type $EbookPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Ebook"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string
    tag: $Enums.EbookTagKind
    summary: string | null
    /**
     * Publisher or research house, shown with every entry so provenance travels
     * with the document.
     */
    source: string
    author: string | null
    /**
     * Tickers the document covers, for filtering alongside the tag.
     */
    tickers: string[]
    publishedAt: Date
    /**
     * Generated name in the upload store, never the uploaded filename.
     */
    fileName: string
    fileSizeBytes: number
    createdAt: Date
    updatedAt: Date
    deletedAt: Date | null
  }, ExtArgs["result"]["ebook"]>
  composites: {}
}

export type EbookGetPayload<S extends boolean | null | undefined | EbookDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$EbookPayload, S>

export type EbookCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<EbookFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: EbookCountAggregateInputType | true
  }

export interface EbookDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Ebook'], meta: { name: 'Ebook' } }
  /**
   * Find zero or one Ebook that matches the filter.
   * @param {EbookFindUniqueArgs} args - Arguments to find a Ebook
   * @example
   * // Get one Ebook
   * const ebook = await prisma.ebook.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends EbookFindUniqueArgs>(args: Prisma.SelectSubset<T, EbookFindUniqueArgs<ExtArgs>>): Prisma.Prisma__EbookClient<runtime.Types.Result.GetResult<Prisma.$EbookPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Ebook that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {EbookFindUniqueOrThrowArgs} args - Arguments to find a Ebook
   * @example
   * // Get one Ebook
   * const ebook = await prisma.ebook.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends EbookFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, EbookFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__EbookClient<runtime.Types.Result.GetResult<Prisma.$EbookPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Ebook that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EbookFindFirstArgs} args - Arguments to find a Ebook
   * @example
   * // Get one Ebook
   * const ebook = await prisma.ebook.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends EbookFindFirstArgs>(args?: Prisma.SelectSubset<T, EbookFindFirstArgs<ExtArgs>>): Prisma.Prisma__EbookClient<runtime.Types.Result.GetResult<Prisma.$EbookPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Ebook that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EbookFindFirstOrThrowArgs} args - Arguments to find a Ebook
   * @example
   * // Get one Ebook
   * const ebook = await prisma.ebook.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends EbookFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, EbookFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__EbookClient<runtime.Types.Result.GetResult<Prisma.$EbookPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Ebooks that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EbookFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Ebooks
   * const ebooks = await prisma.ebook.findMany()
   * 
   * // Get first 10 Ebooks
   * const ebooks = await prisma.ebook.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const ebookWithIdOnly = await prisma.ebook.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends EbookFindManyArgs>(args?: Prisma.SelectSubset<T, EbookFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EbookPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Ebook.
   * @param {EbookCreateArgs} args - Arguments to create a Ebook.
   * @example
   * // Create one Ebook
   * const Ebook = await prisma.ebook.create({
   *   data: {
   *     // ... data to create a Ebook
   *   }
   * })
   * 
   */
  create<T extends EbookCreateArgs>(args: Prisma.SelectSubset<T, EbookCreateArgs<ExtArgs>>): Prisma.Prisma__EbookClient<runtime.Types.Result.GetResult<Prisma.$EbookPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Ebooks.
   * @param {EbookCreateManyArgs} args - Arguments to create many Ebooks.
   * @example
   * // Create many Ebooks
   * const ebook = await prisma.ebook.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends EbookCreateManyArgs>(args?: Prisma.SelectSubset<T, EbookCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Ebooks and returns the data saved in the database.
   * @param {EbookCreateManyAndReturnArgs} args - Arguments to create many Ebooks.
   * @example
   * // Create many Ebooks
   * const ebook = await prisma.ebook.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Ebooks and only return the `id`
   * const ebookWithIdOnly = await prisma.ebook.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends EbookCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, EbookCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EbookPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Ebook.
   * @param {EbookDeleteArgs} args - Arguments to delete one Ebook.
   * @example
   * // Delete one Ebook
   * const Ebook = await prisma.ebook.delete({
   *   where: {
   *     // ... filter to delete one Ebook
   *   }
   * })
   * 
   */
  delete<T extends EbookDeleteArgs>(args: Prisma.SelectSubset<T, EbookDeleteArgs<ExtArgs>>): Prisma.Prisma__EbookClient<runtime.Types.Result.GetResult<Prisma.$EbookPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Ebook.
   * @param {EbookUpdateArgs} args - Arguments to update one Ebook.
   * @example
   * // Update one Ebook
   * const ebook = await prisma.ebook.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends EbookUpdateArgs>(args: Prisma.SelectSubset<T, EbookUpdateArgs<ExtArgs>>): Prisma.Prisma__EbookClient<runtime.Types.Result.GetResult<Prisma.$EbookPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Ebooks.
   * @param {EbookDeleteManyArgs} args - Arguments to filter Ebooks to delete.
   * @example
   * // Delete a few Ebooks
   * const { count } = await prisma.ebook.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends EbookDeleteManyArgs>(args?: Prisma.SelectSubset<T, EbookDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Ebooks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EbookUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Ebooks
   * const ebook = await prisma.ebook.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends EbookUpdateManyArgs>(args: Prisma.SelectSubset<T, EbookUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Ebooks and returns the data updated in the database.
   * @param {EbookUpdateManyAndReturnArgs} args - Arguments to update many Ebooks.
   * @example
   * // Update many Ebooks
   * const ebook = await prisma.ebook.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Ebooks and only return the `id`
   * const ebookWithIdOnly = await prisma.ebook.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends EbookUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, EbookUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EbookPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Ebook.
   * @param {EbookUpsertArgs} args - Arguments to update or create a Ebook.
   * @example
   * // Update or create a Ebook
   * const ebook = await prisma.ebook.upsert({
   *   create: {
   *     // ... data to create a Ebook
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Ebook we want to update
   *   }
   * })
   */
  upsert<T extends EbookUpsertArgs>(args: Prisma.SelectSubset<T, EbookUpsertArgs<ExtArgs>>): Prisma.Prisma__EbookClient<runtime.Types.Result.GetResult<Prisma.$EbookPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Ebooks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EbookCountArgs} args - Arguments to filter Ebooks to count.
   * @example
   * // Count the number of Ebooks
   * const count = await prisma.ebook.count({
   *   where: {
   *     // ... the filter for the Ebooks we want to count
   *   }
   * })
  **/
  count<T extends EbookCountArgs>(
    args?: Prisma.Subset<T, EbookCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], EbookCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Ebook.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EbookAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends EbookAggregateArgs>(args: Prisma.Subset<T, EbookAggregateArgs>): Prisma.PrismaPromise<GetEbookAggregateType<T>>

  /**
   * Group by Ebook.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EbookGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends EbookGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: EbookGroupByArgs['orderBy'] }
      : { orderBy?: EbookGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, EbookGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetEbookGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Ebook model
 */
readonly fields: EbookFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Ebook.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__EbookClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Ebook model
 */
export interface EbookFieldRefs {
  readonly id: Prisma.FieldRef<"Ebook", 'String'>
  readonly title: Prisma.FieldRef<"Ebook", 'String'>
  readonly tag: Prisma.FieldRef<"Ebook", 'EbookTagKind'>
  readonly summary: Prisma.FieldRef<"Ebook", 'String'>
  readonly source: Prisma.FieldRef<"Ebook", 'String'>
  readonly author: Prisma.FieldRef<"Ebook", 'String'>
  readonly tickers: Prisma.FieldRef<"Ebook", 'String[]'>
  readonly publishedAt: Prisma.FieldRef<"Ebook", 'DateTime'>
  readonly fileName: Prisma.FieldRef<"Ebook", 'String'>
  readonly fileSizeBytes: Prisma.FieldRef<"Ebook", 'Int'>
  readonly createdAt: Prisma.FieldRef<"Ebook", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Ebook", 'DateTime'>
  readonly deletedAt: Prisma.FieldRef<"Ebook", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Ebook findUnique
 */
export type EbookFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ebook
   */
  select?: Prisma.EbookSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ebook
   */
  omit?: Prisma.EbookOmit<ExtArgs> | null
  /**
   * Filter, which Ebook to fetch.
   */
  where: Prisma.EbookWhereUniqueInput
}

/**
 * Ebook findUniqueOrThrow
 */
export type EbookFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ebook
   */
  select?: Prisma.EbookSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ebook
   */
  omit?: Prisma.EbookOmit<ExtArgs> | null
  /**
   * Filter, which Ebook to fetch.
   */
  where: Prisma.EbookWhereUniqueInput
}

/**
 * Ebook findFirst
 */
export type EbookFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ebook
   */
  select?: Prisma.EbookSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ebook
   */
  omit?: Prisma.EbookOmit<ExtArgs> | null
  /**
   * Filter, which Ebook to fetch.
   */
  where?: Prisma.EbookWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Ebooks to fetch.
   */
  orderBy?: Prisma.EbookOrderByWithRelationInput | Prisma.EbookOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Ebooks.
   */
  cursor?: Prisma.EbookWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Ebooks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Ebooks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Ebooks.
   */
  distinct?: Prisma.EbookScalarFieldEnum | Prisma.EbookScalarFieldEnum[]
}

/**
 * Ebook findFirstOrThrow
 */
export type EbookFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ebook
   */
  select?: Prisma.EbookSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ebook
   */
  omit?: Prisma.EbookOmit<ExtArgs> | null
  /**
   * Filter, which Ebook to fetch.
   */
  where?: Prisma.EbookWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Ebooks to fetch.
   */
  orderBy?: Prisma.EbookOrderByWithRelationInput | Prisma.EbookOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Ebooks.
   */
  cursor?: Prisma.EbookWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Ebooks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Ebooks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Ebooks.
   */
  distinct?: Prisma.EbookScalarFieldEnum | Prisma.EbookScalarFieldEnum[]
}

/**
 * Ebook findMany
 */
export type EbookFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ebook
   */
  select?: Prisma.EbookSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ebook
   */
  omit?: Prisma.EbookOmit<ExtArgs> | null
  /**
   * Filter, which Ebooks to fetch.
   */
  where?: Prisma.EbookWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Ebooks to fetch.
   */
  orderBy?: Prisma.EbookOrderByWithRelationInput | Prisma.EbookOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Ebooks.
   */
  cursor?: Prisma.EbookWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Ebooks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Ebooks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Ebooks.
   */
  distinct?: Prisma.EbookScalarFieldEnum | Prisma.EbookScalarFieldEnum[]
}

/**
 * Ebook create
 */
export type EbookCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ebook
   */
  select?: Prisma.EbookSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ebook
   */
  omit?: Prisma.EbookOmit<ExtArgs> | null
  /**
   * The data needed to create a Ebook.
   */
  data: Prisma.XOR<Prisma.EbookCreateInput, Prisma.EbookUncheckedCreateInput>
}

/**
 * Ebook createMany
 */
export type EbookCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Ebooks.
   */
  data: Prisma.EbookCreateManyInput | Prisma.EbookCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Ebook createManyAndReturn
 */
export type EbookCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ebook
   */
  select?: Prisma.EbookSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Ebook
   */
  omit?: Prisma.EbookOmit<ExtArgs> | null
  /**
   * The data used to create many Ebooks.
   */
  data: Prisma.EbookCreateManyInput | Prisma.EbookCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Ebook update
 */
export type EbookUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ebook
   */
  select?: Prisma.EbookSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ebook
   */
  omit?: Prisma.EbookOmit<ExtArgs> | null
  /**
   * The data needed to update a Ebook.
   */
  data: Prisma.XOR<Prisma.EbookUpdateInput, Prisma.EbookUncheckedUpdateInput>
  /**
   * Choose, which Ebook to update.
   */
  where: Prisma.EbookWhereUniqueInput
}

/**
 * Ebook updateMany
 */
export type EbookUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Ebooks.
   */
  data: Prisma.XOR<Prisma.EbookUpdateManyMutationInput, Prisma.EbookUncheckedUpdateManyInput>
  /**
   * Filter which Ebooks to update
   */
  where?: Prisma.EbookWhereInput
  /**
   * Limit how many Ebooks to update.
   */
  limit?: number
}

/**
 * Ebook updateManyAndReturn
 */
export type EbookUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ebook
   */
  select?: Prisma.EbookSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Ebook
   */
  omit?: Prisma.EbookOmit<ExtArgs> | null
  /**
   * The data used to update Ebooks.
   */
  data: Prisma.XOR<Prisma.EbookUpdateManyMutationInput, Prisma.EbookUncheckedUpdateManyInput>
  /**
   * Filter which Ebooks to update
   */
  where?: Prisma.EbookWhereInput
  /**
   * Limit how many Ebooks to update.
   */
  limit?: number
}

/**
 * Ebook upsert
 */
export type EbookUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ebook
   */
  select?: Prisma.EbookSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ebook
   */
  omit?: Prisma.EbookOmit<ExtArgs> | null
  /**
   * The filter to search for the Ebook to update in case it exists.
   */
  where: Prisma.EbookWhereUniqueInput
  /**
   * In case the Ebook found by the `where` argument doesn't exist, create a new Ebook with this data.
   */
  create: Prisma.XOR<Prisma.EbookCreateInput, Prisma.EbookUncheckedCreateInput>
  /**
   * In case the Ebook was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.EbookUpdateInput, Prisma.EbookUncheckedUpdateInput>
}

/**
 * Ebook delete
 */
export type EbookDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ebook
   */
  select?: Prisma.EbookSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ebook
   */
  omit?: Prisma.EbookOmit<ExtArgs> | null
  /**
   * Filter which Ebook to delete.
   */
  where: Prisma.EbookWhereUniqueInput
}

/**
 * Ebook deleteMany
 */
export type EbookDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Ebooks to delete
   */
  where?: Prisma.EbookWhereInput
  /**
   * Limit how many Ebooks to delete.
   */
  limit?: number
}

/**
 * Ebook without action
 */
export type EbookDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ebook
   */
  select?: Prisma.EbookSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ebook
   */
  omit?: Prisma.EbookOmit<ExtArgs> | null
}
