
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `MarketIndexSnapshot` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model MarketIndexSnapshot
 * A dated snapshot of the exchange's headline numbers, posted by an admin.
 * The home page reads the most recent row; older rows are kept as history.
 */
export type MarketIndexSnapshotModel = runtime.Types.Result.DefaultSelection<Prisma.$MarketIndexSnapshotPayload>

export type AggregateMarketIndexSnapshot = {
  _count: MarketIndexSnapshotCountAggregateOutputType | null
  _avg: MarketIndexSnapshotAvgAggregateOutputType | null
  _sum: MarketIndexSnapshotSumAggregateOutputType | null
  _min: MarketIndexSnapshotMinAggregateOutputType | null
  _max: MarketIndexSnapshotMaxAggregateOutputType | null
}

export type MarketIndexSnapshotAvgAggregateOutputType = {
  value: runtime.Decimal | null
  changePercent: runtime.Decimal | null
  turnoverIdr: runtime.Decimal | null
  foreignFlowIdr: runtime.Decimal | null
  advancers: number | null
  decliners: number | null
}

export type MarketIndexSnapshotSumAggregateOutputType = {
  value: runtime.Decimal | null
  changePercent: runtime.Decimal | null
  turnoverIdr: runtime.Decimal | null
  foreignFlowIdr: runtime.Decimal | null
  advancers: number | null
  decliners: number | null
}

export type MarketIndexSnapshotMinAggregateOutputType = {
  id: string | null
  indexName: string | null
  value: runtime.Decimal | null
  changePercent: runtime.Decimal | null
  turnoverIdr: runtime.Decimal | null
  foreignFlowIdr: runtime.Decimal | null
  advancers: number | null
  decliners: number | null
  capturedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type MarketIndexSnapshotMaxAggregateOutputType = {
  id: string | null
  indexName: string | null
  value: runtime.Decimal | null
  changePercent: runtime.Decimal | null
  turnoverIdr: runtime.Decimal | null
  foreignFlowIdr: runtime.Decimal | null
  advancers: number | null
  decliners: number | null
  capturedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type MarketIndexSnapshotCountAggregateOutputType = {
  id: number
  indexName: number
  value: number
  changePercent: number
  turnoverIdr: number
  foreignFlowIdr: number
  advancers: number
  decliners: number
  capturedAt: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type MarketIndexSnapshotAvgAggregateInputType = {
  value?: true
  changePercent?: true
  turnoverIdr?: true
  foreignFlowIdr?: true
  advancers?: true
  decliners?: true
}

export type MarketIndexSnapshotSumAggregateInputType = {
  value?: true
  changePercent?: true
  turnoverIdr?: true
  foreignFlowIdr?: true
  advancers?: true
  decliners?: true
}

export type MarketIndexSnapshotMinAggregateInputType = {
  id?: true
  indexName?: true
  value?: true
  changePercent?: true
  turnoverIdr?: true
  foreignFlowIdr?: true
  advancers?: true
  decliners?: true
  capturedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type MarketIndexSnapshotMaxAggregateInputType = {
  id?: true
  indexName?: true
  value?: true
  changePercent?: true
  turnoverIdr?: true
  foreignFlowIdr?: true
  advancers?: true
  decliners?: true
  capturedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type MarketIndexSnapshotCountAggregateInputType = {
  id?: true
  indexName?: true
  value?: true
  changePercent?: true
  turnoverIdr?: true
  foreignFlowIdr?: true
  advancers?: true
  decliners?: true
  capturedAt?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type MarketIndexSnapshotAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MarketIndexSnapshot to aggregate.
   */
  where?: Prisma.MarketIndexSnapshotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MarketIndexSnapshots to fetch.
   */
  orderBy?: Prisma.MarketIndexSnapshotOrderByWithRelationInput | Prisma.MarketIndexSnapshotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MarketIndexSnapshotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MarketIndexSnapshots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MarketIndexSnapshots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned MarketIndexSnapshots
  **/
  _count?: true | MarketIndexSnapshotCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: MarketIndexSnapshotAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: MarketIndexSnapshotSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MarketIndexSnapshotMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MarketIndexSnapshotMaxAggregateInputType
}

export type GetMarketIndexSnapshotAggregateType<T extends MarketIndexSnapshotAggregateArgs> = {
      [P in keyof T & keyof AggregateMarketIndexSnapshot]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMarketIndexSnapshot[P]>
    : Prisma.GetScalarType<T[P], AggregateMarketIndexSnapshot[P]>
}




export type MarketIndexSnapshotGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MarketIndexSnapshotWhereInput
  orderBy?: Prisma.MarketIndexSnapshotOrderByWithAggregationInput | Prisma.MarketIndexSnapshotOrderByWithAggregationInput[]
  by: Prisma.MarketIndexSnapshotScalarFieldEnum[] | Prisma.MarketIndexSnapshotScalarFieldEnum
  having?: Prisma.MarketIndexSnapshotScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MarketIndexSnapshotCountAggregateInputType | true
  _avg?: MarketIndexSnapshotAvgAggregateInputType
  _sum?: MarketIndexSnapshotSumAggregateInputType
  _min?: MarketIndexSnapshotMinAggregateInputType
  _max?: MarketIndexSnapshotMaxAggregateInputType
}

export type MarketIndexSnapshotGroupByOutputType = {
  id: string
  indexName: string
  value: runtime.Decimal
  changePercent: runtime.Decimal
  turnoverIdr: runtime.Decimal
  foreignFlowIdr: runtime.Decimal
  advancers: number
  decliners: number
  capturedAt: Date
  createdAt: Date
  updatedAt: Date
  _count: MarketIndexSnapshotCountAggregateOutputType | null
  _avg: MarketIndexSnapshotAvgAggregateOutputType | null
  _sum: MarketIndexSnapshotSumAggregateOutputType | null
  _min: MarketIndexSnapshotMinAggregateOutputType | null
  _max: MarketIndexSnapshotMaxAggregateOutputType | null
}

export type GetMarketIndexSnapshotGroupByPayload<T extends MarketIndexSnapshotGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MarketIndexSnapshotGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MarketIndexSnapshotGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MarketIndexSnapshotGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MarketIndexSnapshotGroupByOutputType[P]>
      }
    >
  >



export type MarketIndexSnapshotWhereInput = {
  AND?: Prisma.MarketIndexSnapshotWhereInput | Prisma.MarketIndexSnapshotWhereInput[]
  OR?: Prisma.MarketIndexSnapshotWhereInput[]
  NOT?: Prisma.MarketIndexSnapshotWhereInput | Prisma.MarketIndexSnapshotWhereInput[]
  id?: Prisma.StringFilter<"MarketIndexSnapshot"> | string
  indexName?: Prisma.StringFilter<"MarketIndexSnapshot"> | string
  value?: Prisma.DecimalFilter<"MarketIndexSnapshot"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  changePercent?: Prisma.DecimalFilter<"MarketIndexSnapshot"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  turnoverIdr?: Prisma.DecimalFilter<"MarketIndexSnapshot"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  foreignFlowIdr?: Prisma.DecimalFilter<"MarketIndexSnapshot"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  advancers?: Prisma.IntFilter<"MarketIndexSnapshot"> | number
  decliners?: Prisma.IntFilter<"MarketIndexSnapshot"> | number
  capturedAt?: Prisma.DateTimeFilter<"MarketIndexSnapshot"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"MarketIndexSnapshot"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"MarketIndexSnapshot"> | Date | string
}

export type MarketIndexSnapshotOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  indexName?: Prisma.SortOrder
  value?: Prisma.SortOrder
  changePercent?: Prisma.SortOrder
  turnoverIdr?: Prisma.SortOrder
  foreignFlowIdr?: Prisma.SortOrder
  advancers?: Prisma.SortOrder
  decliners?: Prisma.SortOrder
  capturedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MarketIndexSnapshotWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.MarketIndexSnapshotWhereInput | Prisma.MarketIndexSnapshotWhereInput[]
  OR?: Prisma.MarketIndexSnapshotWhereInput[]
  NOT?: Prisma.MarketIndexSnapshotWhereInput | Prisma.MarketIndexSnapshotWhereInput[]
  indexName?: Prisma.StringFilter<"MarketIndexSnapshot"> | string
  value?: Prisma.DecimalFilter<"MarketIndexSnapshot"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  changePercent?: Prisma.DecimalFilter<"MarketIndexSnapshot"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  turnoverIdr?: Prisma.DecimalFilter<"MarketIndexSnapshot"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  foreignFlowIdr?: Prisma.DecimalFilter<"MarketIndexSnapshot"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  advancers?: Prisma.IntFilter<"MarketIndexSnapshot"> | number
  decliners?: Prisma.IntFilter<"MarketIndexSnapshot"> | number
  capturedAt?: Prisma.DateTimeFilter<"MarketIndexSnapshot"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"MarketIndexSnapshot"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"MarketIndexSnapshot"> | Date | string
}, "id">

export type MarketIndexSnapshotOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  indexName?: Prisma.SortOrder
  value?: Prisma.SortOrder
  changePercent?: Prisma.SortOrder
  turnoverIdr?: Prisma.SortOrder
  foreignFlowIdr?: Prisma.SortOrder
  advancers?: Prisma.SortOrder
  decliners?: Prisma.SortOrder
  capturedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.MarketIndexSnapshotCountOrderByAggregateInput
  _avg?: Prisma.MarketIndexSnapshotAvgOrderByAggregateInput
  _max?: Prisma.MarketIndexSnapshotMaxOrderByAggregateInput
  _min?: Prisma.MarketIndexSnapshotMinOrderByAggregateInput
  _sum?: Prisma.MarketIndexSnapshotSumOrderByAggregateInput
}

export type MarketIndexSnapshotScalarWhereWithAggregatesInput = {
  AND?: Prisma.MarketIndexSnapshotScalarWhereWithAggregatesInput | Prisma.MarketIndexSnapshotScalarWhereWithAggregatesInput[]
  OR?: Prisma.MarketIndexSnapshotScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MarketIndexSnapshotScalarWhereWithAggregatesInput | Prisma.MarketIndexSnapshotScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"MarketIndexSnapshot"> | string
  indexName?: Prisma.StringWithAggregatesFilter<"MarketIndexSnapshot"> | string
  value?: Prisma.DecimalWithAggregatesFilter<"MarketIndexSnapshot"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  changePercent?: Prisma.DecimalWithAggregatesFilter<"MarketIndexSnapshot"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  turnoverIdr?: Prisma.DecimalWithAggregatesFilter<"MarketIndexSnapshot"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  foreignFlowIdr?: Prisma.DecimalWithAggregatesFilter<"MarketIndexSnapshot"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  advancers?: Prisma.IntWithAggregatesFilter<"MarketIndexSnapshot"> | number
  decliners?: Prisma.IntWithAggregatesFilter<"MarketIndexSnapshot"> | number
  capturedAt?: Prisma.DateTimeWithAggregatesFilter<"MarketIndexSnapshot"> | Date | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"MarketIndexSnapshot"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"MarketIndexSnapshot"> | Date | string
}

export type MarketIndexSnapshotCreateInput = {
  id?: string
  indexName?: string
  value: runtime.Decimal | runtime.DecimalJsLike | number | string
  changePercent: runtime.Decimal | runtime.DecimalJsLike | number | string
  turnoverIdr: runtime.Decimal | runtime.DecimalJsLike | number | string
  foreignFlowIdr: runtime.Decimal | runtime.DecimalJsLike | number | string
  advancers: number
  decliners: number
  capturedAt: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MarketIndexSnapshotUncheckedCreateInput = {
  id?: string
  indexName?: string
  value: runtime.Decimal | runtime.DecimalJsLike | number | string
  changePercent: runtime.Decimal | runtime.DecimalJsLike | number | string
  turnoverIdr: runtime.Decimal | runtime.DecimalJsLike | number | string
  foreignFlowIdr: runtime.Decimal | runtime.DecimalJsLike | number | string
  advancers: number
  decliners: number
  capturedAt: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MarketIndexSnapshotUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  indexName?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  changePercent?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  turnoverIdr?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  foreignFlowIdr?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  advancers?: Prisma.IntFieldUpdateOperationsInput | number
  decliners?: Prisma.IntFieldUpdateOperationsInput | number
  capturedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MarketIndexSnapshotUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  indexName?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  changePercent?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  turnoverIdr?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  foreignFlowIdr?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  advancers?: Prisma.IntFieldUpdateOperationsInput | number
  decliners?: Prisma.IntFieldUpdateOperationsInput | number
  capturedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MarketIndexSnapshotCreateManyInput = {
  id?: string
  indexName?: string
  value: runtime.Decimal | runtime.DecimalJsLike | number | string
  changePercent: runtime.Decimal | runtime.DecimalJsLike | number | string
  turnoverIdr: runtime.Decimal | runtime.DecimalJsLike | number | string
  foreignFlowIdr: runtime.Decimal | runtime.DecimalJsLike | number | string
  advancers: number
  decliners: number
  capturedAt: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MarketIndexSnapshotUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  indexName?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  changePercent?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  turnoverIdr?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  foreignFlowIdr?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  advancers?: Prisma.IntFieldUpdateOperationsInput | number
  decliners?: Prisma.IntFieldUpdateOperationsInput | number
  capturedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MarketIndexSnapshotUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  indexName?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  changePercent?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  turnoverIdr?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  foreignFlowIdr?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  advancers?: Prisma.IntFieldUpdateOperationsInput | number
  decliners?: Prisma.IntFieldUpdateOperationsInput | number
  capturedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MarketIndexSnapshotCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  indexName?: Prisma.SortOrder
  value?: Prisma.SortOrder
  changePercent?: Prisma.SortOrder
  turnoverIdr?: Prisma.SortOrder
  foreignFlowIdr?: Prisma.SortOrder
  advancers?: Prisma.SortOrder
  decliners?: Prisma.SortOrder
  capturedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MarketIndexSnapshotAvgOrderByAggregateInput = {
  value?: Prisma.SortOrder
  changePercent?: Prisma.SortOrder
  turnoverIdr?: Prisma.SortOrder
  foreignFlowIdr?: Prisma.SortOrder
  advancers?: Prisma.SortOrder
  decliners?: Prisma.SortOrder
}

export type MarketIndexSnapshotMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  indexName?: Prisma.SortOrder
  value?: Prisma.SortOrder
  changePercent?: Prisma.SortOrder
  turnoverIdr?: Prisma.SortOrder
  foreignFlowIdr?: Prisma.SortOrder
  advancers?: Prisma.SortOrder
  decliners?: Prisma.SortOrder
  capturedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MarketIndexSnapshotMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  indexName?: Prisma.SortOrder
  value?: Prisma.SortOrder
  changePercent?: Prisma.SortOrder
  turnoverIdr?: Prisma.SortOrder
  foreignFlowIdr?: Prisma.SortOrder
  advancers?: Prisma.SortOrder
  decliners?: Prisma.SortOrder
  capturedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MarketIndexSnapshotSumOrderByAggregateInput = {
  value?: Prisma.SortOrder
  changePercent?: Prisma.SortOrder
  turnoverIdr?: Prisma.SortOrder
  foreignFlowIdr?: Prisma.SortOrder
  advancers?: Prisma.SortOrder
  decliners?: Prisma.SortOrder
}



export type MarketIndexSnapshotSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  indexName?: boolean
  value?: boolean
  changePercent?: boolean
  turnoverIdr?: boolean
  foreignFlowIdr?: boolean
  advancers?: boolean
  decliners?: boolean
  capturedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["marketIndexSnapshot"]>

export type MarketIndexSnapshotSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  indexName?: boolean
  value?: boolean
  changePercent?: boolean
  turnoverIdr?: boolean
  foreignFlowIdr?: boolean
  advancers?: boolean
  decliners?: boolean
  capturedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["marketIndexSnapshot"]>

export type MarketIndexSnapshotSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  indexName?: boolean
  value?: boolean
  changePercent?: boolean
  turnoverIdr?: boolean
  foreignFlowIdr?: boolean
  advancers?: boolean
  decliners?: boolean
  capturedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["marketIndexSnapshot"]>

export type MarketIndexSnapshotSelectScalar = {
  id?: boolean
  indexName?: boolean
  value?: boolean
  changePercent?: boolean
  turnoverIdr?: boolean
  foreignFlowIdr?: boolean
  advancers?: boolean
  decliners?: boolean
  capturedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type MarketIndexSnapshotOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "indexName" | "value" | "changePercent" | "turnoverIdr" | "foreignFlowIdr" | "advancers" | "decliners" | "capturedAt" | "createdAt" | "updatedAt", ExtArgs["result"]["marketIndexSnapshot"]>

export type $MarketIndexSnapshotPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "MarketIndexSnapshot"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    indexName: string
    /**
     * Index level, e.g. 7845.21.
     */
    value: runtime.Decimal
    changePercent: runtime.Decimal
    /**
     * Stored as whole rupiah, not a pre-formatted string, so the UI decides how
     * to abbreviate it. Foreign flow is negative on a net outflow.
     */
    turnoverIdr: runtime.Decimal
    foreignFlowIdr: runtime.Decimal
    advancers: number
    decliners: number
    /**
     * When the numbers were taken, which is what the page shows as "as of".
     */
    capturedAt: Date
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["marketIndexSnapshot"]>
  composites: {}
}

export type MarketIndexSnapshotGetPayload<S extends boolean | null | undefined | MarketIndexSnapshotDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MarketIndexSnapshotPayload, S>

export type MarketIndexSnapshotCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MarketIndexSnapshotFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MarketIndexSnapshotCountAggregateInputType | true
  }

export interface MarketIndexSnapshotDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['MarketIndexSnapshot'], meta: { name: 'MarketIndexSnapshot' } }
  /**
   * Find zero or one MarketIndexSnapshot that matches the filter.
   * @param {MarketIndexSnapshotFindUniqueArgs} args - Arguments to find a MarketIndexSnapshot
   * @example
   * // Get one MarketIndexSnapshot
   * const marketIndexSnapshot = await prisma.marketIndexSnapshot.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MarketIndexSnapshotFindUniqueArgs>(args: Prisma.SelectSubset<T, MarketIndexSnapshotFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MarketIndexSnapshotClient<runtime.Types.Result.GetResult<Prisma.$MarketIndexSnapshotPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one MarketIndexSnapshot that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MarketIndexSnapshotFindUniqueOrThrowArgs} args - Arguments to find a MarketIndexSnapshot
   * @example
   * // Get one MarketIndexSnapshot
   * const marketIndexSnapshot = await prisma.marketIndexSnapshot.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MarketIndexSnapshotFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MarketIndexSnapshotFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MarketIndexSnapshotClient<runtime.Types.Result.GetResult<Prisma.$MarketIndexSnapshotPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MarketIndexSnapshot that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MarketIndexSnapshotFindFirstArgs} args - Arguments to find a MarketIndexSnapshot
   * @example
   * // Get one MarketIndexSnapshot
   * const marketIndexSnapshot = await prisma.marketIndexSnapshot.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MarketIndexSnapshotFindFirstArgs>(args?: Prisma.SelectSubset<T, MarketIndexSnapshotFindFirstArgs<ExtArgs>>): Prisma.Prisma__MarketIndexSnapshotClient<runtime.Types.Result.GetResult<Prisma.$MarketIndexSnapshotPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MarketIndexSnapshot that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MarketIndexSnapshotFindFirstOrThrowArgs} args - Arguments to find a MarketIndexSnapshot
   * @example
   * // Get one MarketIndexSnapshot
   * const marketIndexSnapshot = await prisma.marketIndexSnapshot.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MarketIndexSnapshotFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MarketIndexSnapshotFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MarketIndexSnapshotClient<runtime.Types.Result.GetResult<Prisma.$MarketIndexSnapshotPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more MarketIndexSnapshots that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MarketIndexSnapshotFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all MarketIndexSnapshots
   * const marketIndexSnapshots = await prisma.marketIndexSnapshot.findMany()
   * 
   * // Get first 10 MarketIndexSnapshots
   * const marketIndexSnapshots = await prisma.marketIndexSnapshot.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const marketIndexSnapshotWithIdOnly = await prisma.marketIndexSnapshot.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MarketIndexSnapshotFindManyArgs>(args?: Prisma.SelectSubset<T, MarketIndexSnapshotFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MarketIndexSnapshotPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a MarketIndexSnapshot.
   * @param {MarketIndexSnapshotCreateArgs} args - Arguments to create a MarketIndexSnapshot.
   * @example
   * // Create one MarketIndexSnapshot
   * const MarketIndexSnapshot = await prisma.marketIndexSnapshot.create({
   *   data: {
   *     // ... data to create a MarketIndexSnapshot
   *   }
   * })
   * 
   */
  create<T extends MarketIndexSnapshotCreateArgs>(args: Prisma.SelectSubset<T, MarketIndexSnapshotCreateArgs<ExtArgs>>): Prisma.Prisma__MarketIndexSnapshotClient<runtime.Types.Result.GetResult<Prisma.$MarketIndexSnapshotPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many MarketIndexSnapshots.
   * @param {MarketIndexSnapshotCreateManyArgs} args - Arguments to create many MarketIndexSnapshots.
   * @example
   * // Create many MarketIndexSnapshots
   * const marketIndexSnapshot = await prisma.marketIndexSnapshot.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MarketIndexSnapshotCreateManyArgs>(args?: Prisma.SelectSubset<T, MarketIndexSnapshotCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many MarketIndexSnapshots and returns the data saved in the database.
   * @param {MarketIndexSnapshotCreateManyAndReturnArgs} args - Arguments to create many MarketIndexSnapshots.
   * @example
   * // Create many MarketIndexSnapshots
   * const marketIndexSnapshot = await prisma.marketIndexSnapshot.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many MarketIndexSnapshots and only return the `id`
   * const marketIndexSnapshotWithIdOnly = await prisma.marketIndexSnapshot.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MarketIndexSnapshotCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MarketIndexSnapshotCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MarketIndexSnapshotPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a MarketIndexSnapshot.
   * @param {MarketIndexSnapshotDeleteArgs} args - Arguments to delete one MarketIndexSnapshot.
   * @example
   * // Delete one MarketIndexSnapshot
   * const MarketIndexSnapshot = await prisma.marketIndexSnapshot.delete({
   *   where: {
   *     // ... filter to delete one MarketIndexSnapshot
   *   }
   * })
   * 
   */
  delete<T extends MarketIndexSnapshotDeleteArgs>(args: Prisma.SelectSubset<T, MarketIndexSnapshotDeleteArgs<ExtArgs>>): Prisma.Prisma__MarketIndexSnapshotClient<runtime.Types.Result.GetResult<Prisma.$MarketIndexSnapshotPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one MarketIndexSnapshot.
   * @param {MarketIndexSnapshotUpdateArgs} args - Arguments to update one MarketIndexSnapshot.
   * @example
   * // Update one MarketIndexSnapshot
   * const marketIndexSnapshot = await prisma.marketIndexSnapshot.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MarketIndexSnapshotUpdateArgs>(args: Prisma.SelectSubset<T, MarketIndexSnapshotUpdateArgs<ExtArgs>>): Prisma.Prisma__MarketIndexSnapshotClient<runtime.Types.Result.GetResult<Prisma.$MarketIndexSnapshotPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more MarketIndexSnapshots.
   * @param {MarketIndexSnapshotDeleteManyArgs} args - Arguments to filter MarketIndexSnapshots to delete.
   * @example
   * // Delete a few MarketIndexSnapshots
   * const { count } = await prisma.marketIndexSnapshot.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MarketIndexSnapshotDeleteManyArgs>(args?: Prisma.SelectSubset<T, MarketIndexSnapshotDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MarketIndexSnapshots.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MarketIndexSnapshotUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many MarketIndexSnapshots
   * const marketIndexSnapshot = await prisma.marketIndexSnapshot.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MarketIndexSnapshotUpdateManyArgs>(args: Prisma.SelectSubset<T, MarketIndexSnapshotUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MarketIndexSnapshots and returns the data updated in the database.
   * @param {MarketIndexSnapshotUpdateManyAndReturnArgs} args - Arguments to update many MarketIndexSnapshots.
   * @example
   * // Update many MarketIndexSnapshots
   * const marketIndexSnapshot = await prisma.marketIndexSnapshot.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more MarketIndexSnapshots and only return the `id`
   * const marketIndexSnapshotWithIdOnly = await prisma.marketIndexSnapshot.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MarketIndexSnapshotUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MarketIndexSnapshotUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MarketIndexSnapshotPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one MarketIndexSnapshot.
   * @param {MarketIndexSnapshotUpsertArgs} args - Arguments to update or create a MarketIndexSnapshot.
   * @example
   * // Update or create a MarketIndexSnapshot
   * const marketIndexSnapshot = await prisma.marketIndexSnapshot.upsert({
   *   create: {
   *     // ... data to create a MarketIndexSnapshot
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the MarketIndexSnapshot we want to update
   *   }
   * })
   */
  upsert<T extends MarketIndexSnapshotUpsertArgs>(args: Prisma.SelectSubset<T, MarketIndexSnapshotUpsertArgs<ExtArgs>>): Prisma.Prisma__MarketIndexSnapshotClient<runtime.Types.Result.GetResult<Prisma.$MarketIndexSnapshotPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of MarketIndexSnapshots.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MarketIndexSnapshotCountArgs} args - Arguments to filter MarketIndexSnapshots to count.
   * @example
   * // Count the number of MarketIndexSnapshots
   * const count = await prisma.marketIndexSnapshot.count({
   *   where: {
   *     // ... the filter for the MarketIndexSnapshots we want to count
   *   }
   * })
  **/
  count<T extends MarketIndexSnapshotCountArgs>(
    args?: Prisma.Subset<T, MarketIndexSnapshotCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MarketIndexSnapshotCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a MarketIndexSnapshot.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MarketIndexSnapshotAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MarketIndexSnapshotAggregateArgs>(args: Prisma.Subset<T, MarketIndexSnapshotAggregateArgs>): Prisma.PrismaPromise<GetMarketIndexSnapshotAggregateType<T>>

  /**
   * Group by MarketIndexSnapshot.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MarketIndexSnapshotGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MarketIndexSnapshotGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MarketIndexSnapshotGroupByArgs['orderBy'] }
      : { orderBy?: MarketIndexSnapshotGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MarketIndexSnapshotGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMarketIndexSnapshotGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the MarketIndexSnapshot model
 */
readonly fields: MarketIndexSnapshotFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for MarketIndexSnapshot.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MarketIndexSnapshotClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the MarketIndexSnapshot model
 */
export interface MarketIndexSnapshotFieldRefs {
  readonly id: Prisma.FieldRef<"MarketIndexSnapshot", 'String'>
  readonly indexName: Prisma.FieldRef<"MarketIndexSnapshot", 'String'>
  readonly value: Prisma.FieldRef<"MarketIndexSnapshot", 'Decimal'>
  readonly changePercent: Prisma.FieldRef<"MarketIndexSnapshot", 'Decimal'>
  readonly turnoverIdr: Prisma.FieldRef<"MarketIndexSnapshot", 'Decimal'>
  readonly foreignFlowIdr: Prisma.FieldRef<"MarketIndexSnapshot", 'Decimal'>
  readonly advancers: Prisma.FieldRef<"MarketIndexSnapshot", 'Int'>
  readonly decliners: Prisma.FieldRef<"MarketIndexSnapshot", 'Int'>
  readonly capturedAt: Prisma.FieldRef<"MarketIndexSnapshot", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"MarketIndexSnapshot", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"MarketIndexSnapshot", 'DateTime'>
}
    

// Custom InputTypes
/**
 * MarketIndexSnapshot findUnique
 */
export type MarketIndexSnapshotFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketIndexSnapshot
   */
  select?: Prisma.MarketIndexSnapshotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketIndexSnapshot
   */
  omit?: Prisma.MarketIndexSnapshotOmit<ExtArgs> | null
  /**
   * Filter, which MarketIndexSnapshot to fetch.
   */
  where: Prisma.MarketIndexSnapshotWhereUniqueInput
}

/**
 * MarketIndexSnapshot findUniqueOrThrow
 */
export type MarketIndexSnapshotFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketIndexSnapshot
   */
  select?: Prisma.MarketIndexSnapshotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketIndexSnapshot
   */
  omit?: Prisma.MarketIndexSnapshotOmit<ExtArgs> | null
  /**
   * Filter, which MarketIndexSnapshot to fetch.
   */
  where: Prisma.MarketIndexSnapshotWhereUniqueInput
}

/**
 * MarketIndexSnapshot findFirst
 */
export type MarketIndexSnapshotFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketIndexSnapshot
   */
  select?: Prisma.MarketIndexSnapshotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketIndexSnapshot
   */
  omit?: Prisma.MarketIndexSnapshotOmit<ExtArgs> | null
  /**
   * Filter, which MarketIndexSnapshot to fetch.
   */
  where?: Prisma.MarketIndexSnapshotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MarketIndexSnapshots to fetch.
   */
  orderBy?: Prisma.MarketIndexSnapshotOrderByWithRelationInput | Prisma.MarketIndexSnapshotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MarketIndexSnapshots.
   */
  cursor?: Prisma.MarketIndexSnapshotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MarketIndexSnapshots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MarketIndexSnapshots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MarketIndexSnapshots.
   */
  distinct?: Prisma.MarketIndexSnapshotScalarFieldEnum | Prisma.MarketIndexSnapshotScalarFieldEnum[]
}

/**
 * MarketIndexSnapshot findFirstOrThrow
 */
export type MarketIndexSnapshotFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketIndexSnapshot
   */
  select?: Prisma.MarketIndexSnapshotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketIndexSnapshot
   */
  omit?: Prisma.MarketIndexSnapshotOmit<ExtArgs> | null
  /**
   * Filter, which MarketIndexSnapshot to fetch.
   */
  where?: Prisma.MarketIndexSnapshotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MarketIndexSnapshots to fetch.
   */
  orderBy?: Prisma.MarketIndexSnapshotOrderByWithRelationInput | Prisma.MarketIndexSnapshotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MarketIndexSnapshots.
   */
  cursor?: Prisma.MarketIndexSnapshotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MarketIndexSnapshots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MarketIndexSnapshots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MarketIndexSnapshots.
   */
  distinct?: Prisma.MarketIndexSnapshotScalarFieldEnum | Prisma.MarketIndexSnapshotScalarFieldEnum[]
}

/**
 * MarketIndexSnapshot findMany
 */
export type MarketIndexSnapshotFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketIndexSnapshot
   */
  select?: Prisma.MarketIndexSnapshotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketIndexSnapshot
   */
  omit?: Prisma.MarketIndexSnapshotOmit<ExtArgs> | null
  /**
   * Filter, which MarketIndexSnapshots to fetch.
   */
  where?: Prisma.MarketIndexSnapshotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MarketIndexSnapshots to fetch.
   */
  orderBy?: Prisma.MarketIndexSnapshotOrderByWithRelationInput | Prisma.MarketIndexSnapshotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing MarketIndexSnapshots.
   */
  cursor?: Prisma.MarketIndexSnapshotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MarketIndexSnapshots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MarketIndexSnapshots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MarketIndexSnapshots.
   */
  distinct?: Prisma.MarketIndexSnapshotScalarFieldEnum | Prisma.MarketIndexSnapshotScalarFieldEnum[]
}

/**
 * MarketIndexSnapshot create
 */
export type MarketIndexSnapshotCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketIndexSnapshot
   */
  select?: Prisma.MarketIndexSnapshotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketIndexSnapshot
   */
  omit?: Prisma.MarketIndexSnapshotOmit<ExtArgs> | null
  /**
   * The data needed to create a MarketIndexSnapshot.
   */
  data: Prisma.XOR<Prisma.MarketIndexSnapshotCreateInput, Prisma.MarketIndexSnapshotUncheckedCreateInput>
}

/**
 * MarketIndexSnapshot createMany
 */
export type MarketIndexSnapshotCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many MarketIndexSnapshots.
   */
  data: Prisma.MarketIndexSnapshotCreateManyInput | Prisma.MarketIndexSnapshotCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * MarketIndexSnapshot createManyAndReturn
 */
export type MarketIndexSnapshotCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketIndexSnapshot
   */
  select?: Prisma.MarketIndexSnapshotSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MarketIndexSnapshot
   */
  omit?: Prisma.MarketIndexSnapshotOmit<ExtArgs> | null
  /**
   * The data used to create many MarketIndexSnapshots.
   */
  data: Prisma.MarketIndexSnapshotCreateManyInput | Prisma.MarketIndexSnapshotCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * MarketIndexSnapshot update
 */
export type MarketIndexSnapshotUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketIndexSnapshot
   */
  select?: Prisma.MarketIndexSnapshotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketIndexSnapshot
   */
  omit?: Prisma.MarketIndexSnapshotOmit<ExtArgs> | null
  /**
   * The data needed to update a MarketIndexSnapshot.
   */
  data: Prisma.XOR<Prisma.MarketIndexSnapshotUpdateInput, Prisma.MarketIndexSnapshotUncheckedUpdateInput>
  /**
   * Choose, which MarketIndexSnapshot to update.
   */
  where: Prisma.MarketIndexSnapshotWhereUniqueInput
}

/**
 * MarketIndexSnapshot updateMany
 */
export type MarketIndexSnapshotUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update MarketIndexSnapshots.
   */
  data: Prisma.XOR<Prisma.MarketIndexSnapshotUpdateManyMutationInput, Prisma.MarketIndexSnapshotUncheckedUpdateManyInput>
  /**
   * Filter which MarketIndexSnapshots to update
   */
  where?: Prisma.MarketIndexSnapshotWhereInput
  /**
   * Limit how many MarketIndexSnapshots to update.
   */
  limit?: number
}

/**
 * MarketIndexSnapshot updateManyAndReturn
 */
export type MarketIndexSnapshotUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketIndexSnapshot
   */
  select?: Prisma.MarketIndexSnapshotSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MarketIndexSnapshot
   */
  omit?: Prisma.MarketIndexSnapshotOmit<ExtArgs> | null
  /**
   * The data used to update MarketIndexSnapshots.
   */
  data: Prisma.XOR<Prisma.MarketIndexSnapshotUpdateManyMutationInput, Prisma.MarketIndexSnapshotUncheckedUpdateManyInput>
  /**
   * Filter which MarketIndexSnapshots to update
   */
  where?: Prisma.MarketIndexSnapshotWhereInput
  /**
   * Limit how many MarketIndexSnapshots to update.
   */
  limit?: number
}

/**
 * MarketIndexSnapshot upsert
 */
export type MarketIndexSnapshotUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketIndexSnapshot
   */
  select?: Prisma.MarketIndexSnapshotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketIndexSnapshot
   */
  omit?: Prisma.MarketIndexSnapshotOmit<ExtArgs> | null
  /**
   * The filter to search for the MarketIndexSnapshot to update in case it exists.
   */
  where: Prisma.MarketIndexSnapshotWhereUniqueInput
  /**
   * In case the MarketIndexSnapshot found by the `where` argument doesn't exist, create a new MarketIndexSnapshot with this data.
   */
  create: Prisma.XOR<Prisma.MarketIndexSnapshotCreateInput, Prisma.MarketIndexSnapshotUncheckedCreateInput>
  /**
   * In case the MarketIndexSnapshot was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MarketIndexSnapshotUpdateInput, Prisma.MarketIndexSnapshotUncheckedUpdateInput>
}

/**
 * MarketIndexSnapshot delete
 */
export type MarketIndexSnapshotDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketIndexSnapshot
   */
  select?: Prisma.MarketIndexSnapshotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketIndexSnapshot
   */
  omit?: Prisma.MarketIndexSnapshotOmit<ExtArgs> | null
  /**
   * Filter which MarketIndexSnapshot to delete.
   */
  where: Prisma.MarketIndexSnapshotWhereUniqueInput
}

/**
 * MarketIndexSnapshot deleteMany
 */
export type MarketIndexSnapshotDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MarketIndexSnapshots to delete
   */
  where?: Prisma.MarketIndexSnapshotWhereInput
  /**
   * Limit how many MarketIndexSnapshots to delete.
   */
  limit?: number
}

/**
 * MarketIndexSnapshot without action
 */
export type MarketIndexSnapshotDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketIndexSnapshot
   */
  select?: Prisma.MarketIndexSnapshotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketIndexSnapshot
   */
  omit?: Prisma.MarketIndexSnapshotOmit<ExtArgs> | null
}
