
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SignalWatchlistItem` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model SignalWatchlistItem
 * 
 */
export type SignalWatchlistItemModel = runtime.Types.Result.DefaultSelection<Prisma.$SignalWatchlistItemPayload>

export type AggregateSignalWatchlistItem = {
  _count: SignalWatchlistItemCountAggregateOutputType | null
  _min: SignalWatchlistItemMinAggregateOutputType | null
  _max: SignalWatchlistItemMaxAggregateOutputType | null
}

export type SignalWatchlistItemMinAggregateOutputType = {
  id: string | null
  userId: string | null
  signalId: string | null
  createdAt: Date | null
}

export type SignalWatchlistItemMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  signalId: string | null
  createdAt: Date | null
}

export type SignalWatchlistItemCountAggregateOutputType = {
  id: number
  userId: number
  signalId: number
  createdAt: number
  _all: number
}


export type SignalWatchlistItemMinAggregateInputType = {
  id?: true
  userId?: true
  signalId?: true
  createdAt?: true
}

export type SignalWatchlistItemMaxAggregateInputType = {
  id?: true
  userId?: true
  signalId?: true
  createdAt?: true
}

export type SignalWatchlistItemCountAggregateInputType = {
  id?: true
  userId?: true
  signalId?: true
  createdAt?: true
  _all?: true
}

export type SignalWatchlistItemAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SignalWatchlistItem to aggregate.
   */
  where?: Prisma.SignalWatchlistItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SignalWatchlistItems to fetch.
   */
  orderBy?: Prisma.SignalWatchlistItemOrderByWithRelationInput | Prisma.SignalWatchlistItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SignalWatchlistItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SignalWatchlistItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SignalWatchlistItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SignalWatchlistItems
  **/
  _count?: true | SignalWatchlistItemCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SignalWatchlistItemMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SignalWatchlistItemMaxAggregateInputType
}

export type GetSignalWatchlistItemAggregateType<T extends SignalWatchlistItemAggregateArgs> = {
      [P in keyof T & keyof AggregateSignalWatchlistItem]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSignalWatchlistItem[P]>
    : Prisma.GetScalarType<T[P], AggregateSignalWatchlistItem[P]>
}




export type SignalWatchlistItemGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SignalWatchlistItemWhereInput
  orderBy?: Prisma.SignalWatchlistItemOrderByWithAggregationInput | Prisma.SignalWatchlistItemOrderByWithAggregationInput[]
  by: Prisma.SignalWatchlistItemScalarFieldEnum[] | Prisma.SignalWatchlistItemScalarFieldEnum
  having?: Prisma.SignalWatchlistItemScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SignalWatchlistItemCountAggregateInputType | true
  _min?: SignalWatchlistItemMinAggregateInputType
  _max?: SignalWatchlistItemMaxAggregateInputType
}

export type SignalWatchlistItemGroupByOutputType = {
  id: string
  userId: string
  signalId: string
  createdAt: Date
  _count: SignalWatchlistItemCountAggregateOutputType | null
  _min: SignalWatchlistItemMinAggregateOutputType | null
  _max: SignalWatchlistItemMaxAggregateOutputType | null
}

export type GetSignalWatchlistItemGroupByPayload<T extends SignalWatchlistItemGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SignalWatchlistItemGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SignalWatchlistItemGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SignalWatchlistItemGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SignalWatchlistItemGroupByOutputType[P]>
      }
    >
  >



export type SignalWatchlistItemWhereInput = {
  AND?: Prisma.SignalWatchlistItemWhereInput | Prisma.SignalWatchlistItemWhereInput[]
  OR?: Prisma.SignalWatchlistItemWhereInput[]
  NOT?: Prisma.SignalWatchlistItemWhereInput | Prisma.SignalWatchlistItemWhereInput[]
  id?: Prisma.StringFilter<"SignalWatchlistItem"> | string
  userId?: Prisma.StringFilter<"SignalWatchlistItem"> | string
  signalId?: Prisma.StringFilter<"SignalWatchlistItem"> | string
  createdAt?: Prisma.DateTimeFilter<"SignalWatchlistItem"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  signal?: Prisma.XOR<Prisma.SignalScalarRelationFilter, Prisma.SignalWhereInput>
}

export type SignalWatchlistItemOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  signalId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  signal?: Prisma.SignalOrderByWithRelationInput
}

export type SignalWatchlistItemWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId_signalId?: Prisma.SignalWatchlistItemUserIdSignalIdCompoundUniqueInput
  AND?: Prisma.SignalWatchlistItemWhereInput | Prisma.SignalWatchlistItemWhereInput[]
  OR?: Prisma.SignalWatchlistItemWhereInput[]
  NOT?: Prisma.SignalWatchlistItemWhereInput | Prisma.SignalWatchlistItemWhereInput[]
  userId?: Prisma.StringFilter<"SignalWatchlistItem"> | string
  signalId?: Prisma.StringFilter<"SignalWatchlistItem"> | string
  createdAt?: Prisma.DateTimeFilter<"SignalWatchlistItem"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  signal?: Prisma.XOR<Prisma.SignalScalarRelationFilter, Prisma.SignalWhereInput>
}, "id" | "userId_signalId">

export type SignalWatchlistItemOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  signalId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.SignalWatchlistItemCountOrderByAggregateInput
  _max?: Prisma.SignalWatchlistItemMaxOrderByAggregateInput
  _min?: Prisma.SignalWatchlistItemMinOrderByAggregateInput
}

export type SignalWatchlistItemScalarWhereWithAggregatesInput = {
  AND?: Prisma.SignalWatchlistItemScalarWhereWithAggregatesInput | Prisma.SignalWatchlistItemScalarWhereWithAggregatesInput[]
  OR?: Prisma.SignalWatchlistItemScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SignalWatchlistItemScalarWhereWithAggregatesInput | Prisma.SignalWatchlistItemScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"SignalWatchlistItem"> | string
  userId?: Prisma.StringWithAggregatesFilter<"SignalWatchlistItem"> | string
  signalId?: Prisma.StringWithAggregatesFilter<"SignalWatchlistItem"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"SignalWatchlistItem"> | Date | string
}

export type SignalWatchlistItemCreateInput = {
  id?: string
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutSignalWatchlistInput
  signal: Prisma.SignalCreateNestedOneWithoutWatchlistItemInput
}

export type SignalWatchlistItemUncheckedCreateInput = {
  id?: string
  userId: string
  signalId: string
  createdAt?: Date | string
}

export type SignalWatchlistItemUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutSignalWatchlistNestedInput
  signal?: Prisma.SignalUpdateOneRequiredWithoutWatchlistItemNestedInput
}

export type SignalWatchlistItemUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  signalId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SignalWatchlistItemCreateManyInput = {
  id?: string
  userId: string
  signalId: string
  createdAt?: Date | string
}

export type SignalWatchlistItemUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SignalWatchlistItemUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  signalId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SignalWatchlistItemListRelationFilter = {
  every?: Prisma.SignalWatchlistItemWhereInput
  some?: Prisma.SignalWatchlistItemWhereInput
  none?: Prisma.SignalWatchlistItemWhereInput
}

export type SignalWatchlistItemOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SignalWatchlistItemUserIdSignalIdCompoundUniqueInput = {
  userId: string
  signalId: string
}

export type SignalWatchlistItemCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  signalId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type SignalWatchlistItemMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  signalId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type SignalWatchlistItemMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  signalId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type SignalWatchlistItemCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.SignalWatchlistItemCreateWithoutUserInput, Prisma.SignalWatchlistItemUncheckedCreateWithoutUserInput> | Prisma.SignalWatchlistItemCreateWithoutUserInput[] | Prisma.SignalWatchlistItemUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.SignalWatchlistItemCreateOrConnectWithoutUserInput | Prisma.SignalWatchlistItemCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.SignalWatchlistItemCreateManyUserInputEnvelope
  connect?: Prisma.SignalWatchlistItemWhereUniqueInput | Prisma.SignalWatchlistItemWhereUniqueInput[]
}

export type SignalWatchlistItemUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.SignalWatchlistItemCreateWithoutUserInput, Prisma.SignalWatchlistItemUncheckedCreateWithoutUserInput> | Prisma.SignalWatchlistItemCreateWithoutUserInput[] | Prisma.SignalWatchlistItemUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.SignalWatchlistItemCreateOrConnectWithoutUserInput | Prisma.SignalWatchlistItemCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.SignalWatchlistItemCreateManyUserInputEnvelope
  connect?: Prisma.SignalWatchlistItemWhereUniqueInput | Prisma.SignalWatchlistItemWhereUniqueInput[]
}

export type SignalWatchlistItemUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.SignalWatchlistItemCreateWithoutUserInput, Prisma.SignalWatchlistItemUncheckedCreateWithoutUserInput> | Prisma.SignalWatchlistItemCreateWithoutUserInput[] | Prisma.SignalWatchlistItemUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.SignalWatchlistItemCreateOrConnectWithoutUserInput | Prisma.SignalWatchlistItemCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.SignalWatchlistItemUpsertWithWhereUniqueWithoutUserInput | Prisma.SignalWatchlistItemUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.SignalWatchlistItemCreateManyUserInputEnvelope
  set?: Prisma.SignalWatchlistItemWhereUniqueInput | Prisma.SignalWatchlistItemWhereUniqueInput[]
  disconnect?: Prisma.SignalWatchlistItemWhereUniqueInput | Prisma.SignalWatchlistItemWhereUniqueInput[]
  delete?: Prisma.SignalWatchlistItemWhereUniqueInput | Prisma.SignalWatchlistItemWhereUniqueInput[]
  connect?: Prisma.SignalWatchlistItemWhereUniqueInput | Prisma.SignalWatchlistItemWhereUniqueInput[]
  update?: Prisma.SignalWatchlistItemUpdateWithWhereUniqueWithoutUserInput | Prisma.SignalWatchlistItemUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.SignalWatchlistItemUpdateManyWithWhereWithoutUserInput | Prisma.SignalWatchlistItemUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.SignalWatchlistItemScalarWhereInput | Prisma.SignalWatchlistItemScalarWhereInput[]
}

export type SignalWatchlistItemUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.SignalWatchlistItemCreateWithoutUserInput, Prisma.SignalWatchlistItemUncheckedCreateWithoutUserInput> | Prisma.SignalWatchlistItemCreateWithoutUserInput[] | Prisma.SignalWatchlistItemUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.SignalWatchlistItemCreateOrConnectWithoutUserInput | Prisma.SignalWatchlistItemCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.SignalWatchlistItemUpsertWithWhereUniqueWithoutUserInput | Prisma.SignalWatchlistItemUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.SignalWatchlistItemCreateManyUserInputEnvelope
  set?: Prisma.SignalWatchlistItemWhereUniqueInput | Prisma.SignalWatchlistItemWhereUniqueInput[]
  disconnect?: Prisma.SignalWatchlistItemWhereUniqueInput | Prisma.SignalWatchlistItemWhereUniqueInput[]
  delete?: Prisma.SignalWatchlistItemWhereUniqueInput | Prisma.SignalWatchlistItemWhereUniqueInput[]
  connect?: Prisma.SignalWatchlistItemWhereUniqueInput | Prisma.SignalWatchlistItemWhereUniqueInput[]
  update?: Prisma.SignalWatchlistItemUpdateWithWhereUniqueWithoutUserInput | Prisma.SignalWatchlistItemUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.SignalWatchlistItemUpdateManyWithWhereWithoutUserInput | Prisma.SignalWatchlistItemUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.SignalWatchlistItemScalarWhereInput | Prisma.SignalWatchlistItemScalarWhereInput[]
}

export type SignalWatchlistItemCreateNestedManyWithoutSignalInput = {
  create?: Prisma.XOR<Prisma.SignalWatchlistItemCreateWithoutSignalInput, Prisma.SignalWatchlistItemUncheckedCreateWithoutSignalInput> | Prisma.SignalWatchlistItemCreateWithoutSignalInput[] | Prisma.SignalWatchlistItemUncheckedCreateWithoutSignalInput[]
  connectOrCreate?: Prisma.SignalWatchlistItemCreateOrConnectWithoutSignalInput | Prisma.SignalWatchlistItemCreateOrConnectWithoutSignalInput[]
  createMany?: Prisma.SignalWatchlistItemCreateManySignalInputEnvelope
  connect?: Prisma.SignalWatchlistItemWhereUniqueInput | Prisma.SignalWatchlistItemWhereUniqueInput[]
}

export type SignalWatchlistItemUncheckedCreateNestedManyWithoutSignalInput = {
  create?: Prisma.XOR<Prisma.SignalWatchlistItemCreateWithoutSignalInput, Prisma.SignalWatchlistItemUncheckedCreateWithoutSignalInput> | Prisma.SignalWatchlistItemCreateWithoutSignalInput[] | Prisma.SignalWatchlistItemUncheckedCreateWithoutSignalInput[]
  connectOrCreate?: Prisma.SignalWatchlistItemCreateOrConnectWithoutSignalInput | Prisma.SignalWatchlistItemCreateOrConnectWithoutSignalInput[]
  createMany?: Prisma.SignalWatchlistItemCreateManySignalInputEnvelope
  connect?: Prisma.SignalWatchlistItemWhereUniqueInput | Prisma.SignalWatchlistItemWhereUniqueInput[]
}

export type SignalWatchlistItemUpdateManyWithoutSignalNestedInput = {
  create?: Prisma.XOR<Prisma.SignalWatchlistItemCreateWithoutSignalInput, Prisma.SignalWatchlistItemUncheckedCreateWithoutSignalInput> | Prisma.SignalWatchlistItemCreateWithoutSignalInput[] | Prisma.SignalWatchlistItemUncheckedCreateWithoutSignalInput[]
  connectOrCreate?: Prisma.SignalWatchlistItemCreateOrConnectWithoutSignalInput | Prisma.SignalWatchlistItemCreateOrConnectWithoutSignalInput[]
  upsert?: Prisma.SignalWatchlistItemUpsertWithWhereUniqueWithoutSignalInput | Prisma.SignalWatchlistItemUpsertWithWhereUniqueWithoutSignalInput[]
  createMany?: Prisma.SignalWatchlistItemCreateManySignalInputEnvelope
  set?: Prisma.SignalWatchlistItemWhereUniqueInput | Prisma.SignalWatchlistItemWhereUniqueInput[]
  disconnect?: Prisma.SignalWatchlistItemWhereUniqueInput | Prisma.SignalWatchlistItemWhereUniqueInput[]
  delete?: Prisma.SignalWatchlistItemWhereUniqueInput | Prisma.SignalWatchlistItemWhereUniqueInput[]
  connect?: Prisma.SignalWatchlistItemWhereUniqueInput | Prisma.SignalWatchlistItemWhereUniqueInput[]
  update?: Prisma.SignalWatchlistItemUpdateWithWhereUniqueWithoutSignalInput | Prisma.SignalWatchlistItemUpdateWithWhereUniqueWithoutSignalInput[]
  updateMany?: Prisma.SignalWatchlistItemUpdateManyWithWhereWithoutSignalInput | Prisma.SignalWatchlistItemUpdateManyWithWhereWithoutSignalInput[]
  deleteMany?: Prisma.SignalWatchlistItemScalarWhereInput | Prisma.SignalWatchlistItemScalarWhereInput[]
}

export type SignalWatchlistItemUncheckedUpdateManyWithoutSignalNestedInput = {
  create?: Prisma.XOR<Prisma.SignalWatchlistItemCreateWithoutSignalInput, Prisma.SignalWatchlistItemUncheckedCreateWithoutSignalInput> | Prisma.SignalWatchlistItemCreateWithoutSignalInput[] | Prisma.SignalWatchlistItemUncheckedCreateWithoutSignalInput[]
  connectOrCreate?: Prisma.SignalWatchlistItemCreateOrConnectWithoutSignalInput | Prisma.SignalWatchlistItemCreateOrConnectWithoutSignalInput[]
  upsert?: Prisma.SignalWatchlistItemUpsertWithWhereUniqueWithoutSignalInput | Prisma.SignalWatchlistItemUpsertWithWhereUniqueWithoutSignalInput[]
  createMany?: Prisma.SignalWatchlistItemCreateManySignalInputEnvelope
  set?: Prisma.SignalWatchlistItemWhereUniqueInput | Prisma.SignalWatchlistItemWhereUniqueInput[]
  disconnect?: Prisma.SignalWatchlistItemWhereUniqueInput | Prisma.SignalWatchlistItemWhereUniqueInput[]
  delete?: Prisma.SignalWatchlistItemWhereUniqueInput | Prisma.SignalWatchlistItemWhereUniqueInput[]
  connect?: Prisma.SignalWatchlistItemWhereUniqueInput | Prisma.SignalWatchlistItemWhereUniqueInput[]
  update?: Prisma.SignalWatchlistItemUpdateWithWhereUniqueWithoutSignalInput | Prisma.SignalWatchlistItemUpdateWithWhereUniqueWithoutSignalInput[]
  updateMany?: Prisma.SignalWatchlistItemUpdateManyWithWhereWithoutSignalInput | Prisma.SignalWatchlistItemUpdateManyWithWhereWithoutSignalInput[]
  deleteMany?: Prisma.SignalWatchlistItemScalarWhereInput | Prisma.SignalWatchlistItemScalarWhereInput[]
}

export type SignalWatchlistItemCreateWithoutUserInput = {
  id?: string
  createdAt?: Date | string
  signal: Prisma.SignalCreateNestedOneWithoutWatchlistItemInput
}

export type SignalWatchlistItemUncheckedCreateWithoutUserInput = {
  id?: string
  signalId: string
  createdAt?: Date | string
}

export type SignalWatchlistItemCreateOrConnectWithoutUserInput = {
  where: Prisma.SignalWatchlistItemWhereUniqueInput
  create: Prisma.XOR<Prisma.SignalWatchlistItemCreateWithoutUserInput, Prisma.SignalWatchlistItemUncheckedCreateWithoutUserInput>
}

export type SignalWatchlistItemCreateManyUserInputEnvelope = {
  data: Prisma.SignalWatchlistItemCreateManyUserInput | Prisma.SignalWatchlistItemCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type SignalWatchlistItemUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.SignalWatchlistItemWhereUniqueInput
  update: Prisma.XOR<Prisma.SignalWatchlistItemUpdateWithoutUserInput, Prisma.SignalWatchlistItemUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.SignalWatchlistItemCreateWithoutUserInput, Prisma.SignalWatchlistItemUncheckedCreateWithoutUserInput>
}

export type SignalWatchlistItemUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.SignalWatchlistItemWhereUniqueInput
  data: Prisma.XOR<Prisma.SignalWatchlistItemUpdateWithoutUserInput, Prisma.SignalWatchlistItemUncheckedUpdateWithoutUserInput>
}

export type SignalWatchlistItemUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.SignalWatchlistItemScalarWhereInput
  data: Prisma.XOR<Prisma.SignalWatchlistItemUpdateManyMutationInput, Prisma.SignalWatchlistItemUncheckedUpdateManyWithoutUserInput>
}

export type SignalWatchlistItemScalarWhereInput = {
  AND?: Prisma.SignalWatchlistItemScalarWhereInput | Prisma.SignalWatchlistItemScalarWhereInput[]
  OR?: Prisma.SignalWatchlistItemScalarWhereInput[]
  NOT?: Prisma.SignalWatchlistItemScalarWhereInput | Prisma.SignalWatchlistItemScalarWhereInput[]
  id?: Prisma.StringFilter<"SignalWatchlistItem"> | string
  userId?: Prisma.StringFilter<"SignalWatchlistItem"> | string
  signalId?: Prisma.StringFilter<"SignalWatchlistItem"> | string
  createdAt?: Prisma.DateTimeFilter<"SignalWatchlistItem"> | Date | string
}

export type SignalWatchlistItemCreateWithoutSignalInput = {
  id?: string
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutSignalWatchlistInput
}

export type SignalWatchlistItemUncheckedCreateWithoutSignalInput = {
  id?: string
  userId: string
  createdAt?: Date | string
}

export type SignalWatchlistItemCreateOrConnectWithoutSignalInput = {
  where: Prisma.SignalWatchlistItemWhereUniqueInput
  create: Prisma.XOR<Prisma.SignalWatchlistItemCreateWithoutSignalInput, Prisma.SignalWatchlistItemUncheckedCreateWithoutSignalInput>
}

export type SignalWatchlistItemCreateManySignalInputEnvelope = {
  data: Prisma.SignalWatchlistItemCreateManySignalInput | Prisma.SignalWatchlistItemCreateManySignalInput[]
  skipDuplicates?: boolean
}

export type SignalWatchlistItemUpsertWithWhereUniqueWithoutSignalInput = {
  where: Prisma.SignalWatchlistItemWhereUniqueInput
  update: Prisma.XOR<Prisma.SignalWatchlistItemUpdateWithoutSignalInput, Prisma.SignalWatchlistItemUncheckedUpdateWithoutSignalInput>
  create: Prisma.XOR<Prisma.SignalWatchlistItemCreateWithoutSignalInput, Prisma.SignalWatchlistItemUncheckedCreateWithoutSignalInput>
}

export type SignalWatchlistItemUpdateWithWhereUniqueWithoutSignalInput = {
  where: Prisma.SignalWatchlistItemWhereUniqueInput
  data: Prisma.XOR<Prisma.SignalWatchlistItemUpdateWithoutSignalInput, Prisma.SignalWatchlistItemUncheckedUpdateWithoutSignalInput>
}

export type SignalWatchlistItemUpdateManyWithWhereWithoutSignalInput = {
  where: Prisma.SignalWatchlistItemScalarWhereInput
  data: Prisma.XOR<Prisma.SignalWatchlistItemUpdateManyMutationInput, Prisma.SignalWatchlistItemUncheckedUpdateManyWithoutSignalInput>
}

export type SignalWatchlistItemCreateManyUserInput = {
  id?: string
  signalId: string
  createdAt?: Date | string
}

export type SignalWatchlistItemUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  signal?: Prisma.SignalUpdateOneRequiredWithoutWatchlistItemNestedInput
}

export type SignalWatchlistItemUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  signalId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SignalWatchlistItemUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  signalId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SignalWatchlistItemCreateManySignalInput = {
  id?: string
  userId: string
  createdAt?: Date | string
}

export type SignalWatchlistItemUpdateWithoutSignalInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutSignalWatchlistNestedInput
}

export type SignalWatchlistItemUncheckedUpdateWithoutSignalInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SignalWatchlistItemUncheckedUpdateManyWithoutSignalInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type SignalWatchlistItemSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  signalId?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  signal?: boolean | Prisma.SignalDefaultArgs<ExtArgs>
}, ExtArgs["result"]["signalWatchlistItem"]>

export type SignalWatchlistItemSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  signalId?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  signal?: boolean | Prisma.SignalDefaultArgs<ExtArgs>
}, ExtArgs["result"]["signalWatchlistItem"]>

export type SignalWatchlistItemSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  signalId?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  signal?: boolean | Prisma.SignalDefaultArgs<ExtArgs>
}, ExtArgs["result"]["signalWatchlistItem"]>

export type SignalWatchlistItemSelectScalar = {
  id?: boolean
  userId?: boolean
  signalId?: boolean
  createdAt?: boolean
}

export type SignalWatchlistItemOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "signalId" | "createdAt", ExtArgs["result"]["signalWatchlistItem"]>
export type SignalWatchlistItemInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  signal?: boolean | Prisma.SignalDefaultArgs<ExtArgs>
}
export type SignalWatchlistItemIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  signal?: boolean | Prisma.SignalDefaultArgs<ExtArgs>
}
export type SignalWatchlistItemIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  signal?: boolean | Prisma.SignalDefaultArgs<ExtArgs>
}

export type $SignalWatchlistItemPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SignalWatchlistItem"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    signal: Prisma.$SignalPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    signalId: string
    createdAt: Date
  }, ExtArgs["result"]["signalWatchlistItem"]>
  composites: {}
}

export type SignalWatchlistItemGetPayload<S extends boolean | null | undefined | SignalWatchlistItemDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SignalWatchlistItemPayload, S>

export type SignalWatchlistItemCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SignalWatchlistItemFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SignalWatchlistItemCountAggregateInputType | true
  }

export interface SignalWatchlistItemDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SignalWatchlistItem'], meta: { name: 'SignalWatchlistItem' } }
  /**
   * Find zero or one SignalWatchlistItem that matches the filter.
   * @param {SignalWatchlistItemFindUniqueArgs} args - Arguments to find a SignalWatchlistItem
   * @example
   * // Get one SignalWatchlistItem
   * const signalWatchlistItem = await prisma.signalWatchlistItem.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SignalWatchlistItemFindUniqueArgs>(args: Prisma.SelectSubset<T, SignalWatchlistItemFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SignalWatchlistItemClient<runtime.Types.Result.GetResult<Prisma.$SignalWatchlistItemPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SignalWatchlistItem that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SignalWatchlistItemFindUniqueOrThrowArgs} args - Arguments to find a SignalWatchlistItem
   * @example
   * // Get one SignalWatchlistItem
   * const signalWatchlistItem = await prisma.signalWatchlistItem.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SignalWatchlistItemFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SignalWatchlistItemFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SignalWatchlistItemClient<runtime.Types.Result.GetResult<Prisma.$SignalWatchlistItemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SignalWatchlistItem that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SignalWatchlistItemFindFirstArgs} args - Arguments to find a SignalWatchlistItem
   * @example
   * // Get one SignalWatchlistItem
   * const signalWatchlistItem = await prisma.signalWatchlistItem.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SignalWatchlistItemFindFirstArgs>(args?: Prisma.SelectSubset<T, SignalWatchlistItemFindFirstArgs<ExtArgs>>): Prisma.Prisma__SignalWatchlistItemClient<runtime.Types.Result.GetResult<Prisma.$SignalWatchlistItemPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SignalWatchlistItem that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SignalWatchlistItemFindFirstOrThrowArgs} args - Arguments to find a SignalWatchlistItem
   * @example
   * // Get one SignalWatchlistItem
   * const signalWatchlistItem = await prisma.signalWatchlistItem.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SignalWatchlistItemFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SignalWatchlistItemFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SignalWatchlistItemClient<runtime.Types.Result.GetResult<Prisma.$SignalWatchlistItemPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SignalWatchlistItems that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SignalWatchlistItemFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SignalWatchlistItems
   * const signalWatchlistItems = await prisma.signalWatchlistItem.findMany()
   * 
   * // Get first 10 SignalWatchlistItems
   * const signalWatchlistItems = await prisma.signalWatchlistItem.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const signalWatchlistItemWithIdOnly = await prisma.signalWatchlistItem.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SignalWatchlistItemFindManyArgs>(args?: Prisma.SelectSubset<T, SignalWatchlistItemFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SignalWatchlistItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SignalWatchlistItem.
   * @param {SignalWatchlistItemCreateArgs} args - Arguments to create a SignalWatchlistItem.
   * @example
   * // Create one SignalWatchlistItem
   * const SignalWatchlistItem = await prisma.signalWatchlistItem.create({
   *   data: {
   *     // ... data to create a SignalWatchlistItem
   *   }
   * })
   * 
   */
  create<T extends SignalWatchlistItemCreateArgs>(args: Prisma.SelectSubset<T, SignalWatchlistItemCreateArgs<ExtArgs>>): Prisma.Prisma__SignalWatchlistItemClient<runtime.Types.Result.GetResult<Prisma.$SignalWatchlistItemPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SignalWatchlistItems.
   * @param {SignalWatchlistItemCreateManyArgs} args - Arguments to create many SignalWatchlistItems.
   * @example
   * // Create many SignalWatchlistItems
   * const signalWatchlistItem = await prisma.signalWatchlistItem.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SignalWatchlistItemCreateManyArgs>(args?: Prisma.SelectSubset<T, SignalWatchlistItemCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SignalWatchlistItems and returns the data saved in the database.
   * @param {SignalWatchlistItemCreateManyAndReturnArgs} args - Arguments to create many SignalWatchlistItems.
   * @example
   * // Create many SignalWatchlistItems
   * const signalWatchlistItem = await prisma.signalWatchlistItem.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SignalWatchlistItems and only return the `id`
   * const signalWatchlistItemWithIdOnly = await prisma.signalWatchlistItem.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SignalWatchlistItemCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SignalWatchlistItemCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SignalWatchlistItemPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SignalWatchlistItem.
   * @param {SignalWatchlistItemDeleteArgs} args - Arguments to delete one SignalWatchlistItem.
   * @example
   * // Delete one SignalWatchlistItem
   * const SignalWatchlistItem = await prisma.signalWatchlistItem.delete({
   *   where: {
   *     // ... filter to delete one SignalWatchlistItem
   *   }
   * })
   * 
   */
  delete<T extends SignalWatchlistItemDeleteArgs>(args: Prisma.SelectSubset<T, SignalWatchlistItemDeleteArgs<ExtArgs>>): Prisma.Prisma__SignalWatchlistItemClient<runtime.Types.Result.GetResult<Prisma.$SignalWatchlistItemPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SignalWatchlistItem.
   * @param {SignalWatchlistItemUpdateArgs} args - Arguments to update one SignalWatchlistItem.
   * @example
   * // Update one SignalWatchlistItem
   * const signalWatchlistItem = await prisma.signalWatchlistItem.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SignalWatchlistItemUpdateArgs>(args: Prisma.SelectSubset<T, SignalWatchlistItemUpdateArgs<ExtArgs>>): Prisma.Prisma__SignalWatchlistItemClient<runtime.Types.Result.GetResult<Prisma.$SignalWatchlistItemPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SignalWatchlistItems.
   * @param {SignalWatchlistItemDeleteManyArgs} args - Arguments to filter SignalWatchlistItems to delete.
   * @example
   * // Delete a few SignalWatchlistItems
   * const { count } = await prisma.signalWatchlistItem.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SignalWatchlistItemDeleteManyArgs>(args?: Prisma.SelectSubset<T, SignalWatchlistItemDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SignalWatchlistItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SignalWatchlistItemUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SignalWatchlistItems
   * const signalWatchlistItem = await prisma.signalWatchlistItem.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SignalWatchlistItemUpdateManyArgs>(args: Prisma.SelectSubset<T, SignalWatchlistItemUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SignalWatchlistItems and returns the data updated in the database.
   * @param {SignalWatchlistItemUpdateManyAndReturnArgs} args - Arguments to update many SignalWatchlistItems.
   * @example
   * // Update many SignalWatchlistItems
   * const signalWatchlistItem = await prisma.signalWatchlistItem.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SignalWatchlistItems and only return the `id`
   * const signalWatchlistItemWithIdOnly = await prisma.signalWatchlistItem.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SignalWatchlistItemUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SignalWatchlistItemUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SignalWatchlistItemPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SignalWatchlistItem.
   * @param {SignalWatchlistItemUpsertArgs} args - Arguments to update or create a SignalWatchlistItem.
   * @example
   * // Update or create a SignalWatchlistItem
   * const signalWatchlistItem = await prisma.signalWatchlistItem.upsert({
   *   create: {
   *     // ... data to create a SignalWatchlistItem
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SignalWatchlistItem we want to update
   *   }
   * })
   */
  upsert<T extends SignalWatchlistItemUpsertArgs>(args: Prisma.SelectSubset<T, SignalWatchlistItemUpsertArgs<ExtArgs>>): Prisma.Prisma__SignalWatchlistItemClient<runtime.Types.Result.GetResult<Prisma.$SignalWatchlistItemPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SignalWatchlistItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SignalWatchlistItemCountArgs} args - Arguments to filter SignalWatchlistItems to count.
   * @example
   * // Count the number of SignalWatchlistItems
   * const count = await prisma.signalWatchlistItem.count({
   *   where: {
   *     // ... the filter for the SignalWatchlistItems we want to count
   *   }
   * })
  **/
  count<T extends SignalWatchlistItemCountArgs>(
    args?: Prisma.Subset<T, SignalWatchlistItemCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SignalWatchlistItemCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SignalWatchlistItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SignalWatchlistItemAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SignalWatchlistItemAggregateArgs>(args: Prisma.Subset<T, SignalWatchlistItemAggregateArgs>): Prisma.PrismaPromise<GetSignalWatchlistItemAggregateType<T>>

  /**
   * Group by SignalWatchlistItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SignalWatchlistItemGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SignalWatchlistItemGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SignalWatchlistItemGroupByArgs['orderBy'] }
      : { orderBy?: SignalWatchlistItemGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SignalWatchlistItemGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSignalWatchlistItemGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SignalWatchlistItem model
 */
readonly fields: SignalWatchlistItemFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SignalWatchlistItem.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SignalWatchlistItemClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  signal<T extends Prisma.SignalDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SignalDefaultArgs<ExtArgs>>): Prisma.Prisma__SignalClient<runtime.Types.Result.GetResult<Prisma.$SignalPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SignalWatchlistItem model
 */
export interface SignalWatchlistItemFieldRefs {
  readonly id: Prisma.FieldRef<"SignalWatchlistItem", 'String'>
  readonly userId: Prisma.FieldRef<"SignalWatchlistItem", 'String'>
  readonly signalId: Prisma.FieldRef<"SignalWatchlistItem", 'String'>
  readonly createdAt: Prisma.FieldRef<"SignalWatchlistItem", 'DateTime'>
}
    

// Custom InputTypes
/**
 * SignalWatchlistItem findUnique
 */
export type SignalWatchlistItemFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SignalWatchlistItem
   */
  select?: Prisma.SignalWatchlistItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SignalWatchlistItem
   */
  omit?: Prisma.SignalWatchlistItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SignalWatchlistItemInclude<ExtArgs> | null
  /**
   * Filter, which SignalWatchlistItem to fetch.
   */
  where: Prisma.SignalWatchlistItemWhereUniqueInput
}

/**
 * SignalWatchlistItem findUniqueOrThrow
 */
export type SignalWatchlistItemFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SignalWatchlistItem
   */
  select?: Prisma.SignalWatchlistItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SignalWatchlistItem
   */
  omit?: Prisma.SignalWatchlistItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SignalWatchlistItemInclude<ExtArgs> | null
  /**
   * Filter, which SignalWatchlistItem to fetch.
   */
  where: Prisma.SignalWatchlistItemWhereUniqueInput
}

/**
 * SignalWatchlistItem findFirst
 */
export type SignalWatchlistItemFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SignalWatchlistItem
   */
  select?: Prisma.SignalWatchlistItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SignalWatchlistItem
   */
  omit?: Prisma.SignalWatchlistItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SignalWatchlistItemInclude<ExtArgs> | null
  /**
   * Filter, which SignalWatchlistItem to fetch.
   */
  where?: Prisma.SignalWatchlistItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SignalWatchlistItems to fetch.
   */
  orderBy?: Prisma.SignalWatchlistItemOrderByWithRelationInput | Prisma.SignalWatchlistItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SignalWatchlistItems.
   */
  cursor?: Prisma.SignalWatchlistItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SignalWatchlistItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SignalWatchlistItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SignalWatchlistItems.
   */
  distinct?: Prisma.SignalWatchlistItemScalarFieldEnum | Prisma.SignalWatchlistItemScalarFieldEnum[]
}

/**
 * SignalWatchlistItem findFirstOrThrow
 */
export type SignalWatchlistItemFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SignalWatchlistItem
   */
  select?: Prisma.SignalWatchlistItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SignalWatchlistItem
   */
  omit?: Prisma.SignalWatchlistItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SignalWatchlistItemInclude<ExtArgs> | null
  /**
   * Filter, which SignalWatchlistItem to fetch.
   */
  where?: Prisma.SignalWatchlistItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SignalWatchlistItems to fetch.
   */
  orderBy?: Prisma.SignalWatchlistItemOrderByWithRelationInput | Prisma.SignalWatchlistItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SignalWatchlistItems.
   */
  cursor?: Prisma.SignalWatchlistItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SignalWatchlistItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SignalWatchlistItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SignalWatchlistItems.
   */
  distinct?: Prisma.SignalWatchlistItemScalarFieldEnum | Prisma.SignalWatchlistItemScalarFieldEnum[]
}

/**
 * SignalWatchlistItem findMany
 */
export type SignalWatchlistItemFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SignalWatchlistItem
   */
  select?: Prisma.SignalWatchlistItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SignalWatchlistItem
   */
  omit?: Prisma.SignalWatchlistItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SignalWatchlistItemInclude<ExtArgs> | null
  /**
   * Filter, which SignalWatchlistItems to fetch.
   */
  where?: Prisma.SignalWatchlistItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SignalWatchlistItems to fetch.
   */
  orderBy?: Prisma.SignalWatchlistItemOrderByWithRelationInput | Prisma.SignalWatchlistItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SignalWatchlistItems.
   */
  cursor?: Prisma.SignalWatchlistItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SignalWatchlistItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SignalWatchlistItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SignalWatchlistItems.
   */
  distinct?: Prisma.SignalWatchlistItemScalarFieldEnum | Prisma.SignalWatchlistItemScalarFieldEnum[]
}

/**
 * SignalWatchlistItem create
 */
export type SignalWatchlistItemCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SignalWatchlistItem
   */
  select?: Prisma.SignalWatchlistItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SignalWatchlistItem
   */
  omit?: Prisma.SignalWatchlistItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SignalWatchlistItemInclude<ExtArgs> | null
  /**
   * The data needed to create a SignalWatchlistItem.
   */
  data: Prisma.XOR<Prisma.SignalWatchlistItemCreateInput, Prisma.SignalWatchlistItemUncheckedCreateInput>
}

/**
 * SignalWatchlistItem createMany
 */
export type SignalWatchlistItemCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SignalWatchlistItems.
   */
  data: Prisma.SignalWatchlistItemCreateManyInput | Prisma.SignalWatchlistItemCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SignalWatchlistItem createManyAndReturn
 */
export type SignalWatchlistItemCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SignalWatchlistItem
   */
  select?: Prisma.SignalWatchlistItemSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SignalWatchlistItem
   */
  omit?: Prisma.SignalWatchlistItemOmit<ExtArgs> | null
  /**
   * The data used to create many SignalWatchlistItems.
   */
  data: Prisma.SignalWatchlistItemCreateManyInput | Prisma.SignalWatchlistItemCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SignalWatchlistItemIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * SignalWatchlistItem update
 */
export type SignalWatchlistItemUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SignalWatchlistItem
   */
  select?: Prisma.SignalWatchlistItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SignalWatchlistItem
   */
  omit?: Prisma.SignalWatchlistItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SignalWatchlistItemInclude<ExtArgs> | null
  /**
   * The data needed to update a SignalWatchlistItem.
   */
  data: Prisma.XOR<Prisma.SignalWatchlistItemUpdateInput, Prisma.SignalWatchlistItemUncheckedUpdateInput>
  /**
   * Choose, which SignalWatchlistItem to update.
   */
  where: Prisma.SignalWatchlistItemWhereUniqueInput
}

/**
 * SignalWatchlistItem updateMany
 */
export type SignalWatchlistItemUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SignalWatchlistItems.
   */
  data: Prisma.XOR<Prisma.SignalWatchlistItemUpdateManyMutationInput, Prisma.SignalWatchlistItemUncheckedUpdateManyInput>
  /**
   * Filter which SignalWatchlistItems to update
   */
  where?: Prisma.SignalWatchlistItemWhereInput
  /**
   * Limit how many SignalWatchlistItems to update.
   */
  limit?: number
}

/**
 * SignalWatchlistItem updateManyAndReturn
 */
export type SignalWatchlistItemUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SignalWatchlistItem
   */
  select?: Prisma.SignalWatchlistItemSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SignalWatchlistItem
   */
  omit?: Prisma.SignalWatchlistItemOmit<ExtArgs> | null
  /**
   * The data used to update SignalWatchlistItems.
   */
  data: Prisma.XOR<Prisma.SignalWatchlistItemUpdateManyMutationInput, Prisma.SignalWatchlistItemUncheckedUpdateManyInput>
  /**
   * Filter which SignalWatchlistItems to update
   */
  where?: Prisma.SignalWatchlistItemWhereInput
  /**
   * Limit how many SignalWatchlistItems to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SignalWatchlistItemIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * SignalWatchlistItem upsert
 */
export type SignalWatchlistItemUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SignalWatchlistItem
   */
  select?: Prisma.SignalWatchlistItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SignalWatchlistItem
   */
  omit?: Prisma.SignalWatchlistItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SignalWatchlistItemInclude<ExtArgs> | null
  /**
   * The filter to search for the SignalWatchlistItem to update in case it exists.
   */
  where: Prisma.SignalWatchlistItemWhereUniqueInput
  /**
   * In case the SignalWatchlistItem found by the `where` argument doesn't exist, create a new SignalWatchlistItem with this data.
   */
  create: Prisma.XOR<Prisma.SignalWatchlistItemCreateInput, Prisma.SignalWatchlistItemUncheckedCreateInput>
  /**
   * In case the SignalWatchlistItem was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SignalWatchlistItemUpdateInput, Prisma.SignalWatchlistItemUncheckedUpdateInput>
}

/**
 * SignalWatchlistItem delete
 */
export type SignalWatchlistItemDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SignalWatchlistItem
   */
  select?: Prisma.SignalWatchlistItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SignalWatchlistItem
   */
  omit?: Prisma.SignalWatchlistItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SignalWatchlistItemInclude<ExtArgs> | null
  /**
   * Filter which SignalWatchlistItem to delete.
   */
  where: Prisma.SignalWatchlistItemWhereUniqueInput
}

/**
 * SignalWatchlistItem deleteMany
 */
export type SignalWatchlistItemDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SignalWatchlistItems to delete
   */
  where?: Prisma.SignalWatchlistItemWhereInput
  /**
   * Limit how many SignalWatchlistItems to delete.
   */
  limit?: number
}

/**
 * SignalWatchlistItem without action
 */
export type SignalWatchlistItemDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SignalWatchlistItem
   */
  select?: Prisma.SignalWatchlistItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SignalWatchlistItem
   */
  omit?: Prisma.SignalWatchlistItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SignalWatchlistItemInclude<ExtArgs> | null
}
