
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Video` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Video
 * 
 */
export type VideoModel = runtime.Types.Result.DefaultSelection<Prisma.$VideoPayload>

export type AggregateVideo = {
  _count: VideoCountAggregateOutputType | null
  _avg: VideoAvgAggregateOutputType | null
  _sum: VideoSumAggregateOutputType | null
  _min: VideoMinAggregateOutputType | null
  _max: VideoMaxAggregateOutputType | null
}

export type VideoAvgAggregateOutputType = {
  durationSeconds: number | null
}

export type VideoSumAggregateOutputType = {
  durationSeconds: number | null
}

export type VideoMinAggregateOutputType = {
  id: string | null
  title: string | null
  description: string | null
  videoUrl: string | null
  provider: $Enums.VideoProviderKind | null
  thumbnailUrl: string | null
  durationSeconds: number | null
  categoryId: string | null
  isFeatured: boolean | null
  publishedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
}

export type VideoMaxAggregateOutputType = {
  id: string | null
  title: string | null
  description: string | null
  videoUrl: string | null
  provider: $Enums.VideoProviderKind | null
  thumbnailUrl: string | null
  durationSeconds: number | null
  categoryId: string | null
  isFeatured: boolean | null
  publishedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
}

export type VideoCountAggregateOutputType = {
  id: number
  title: number
  description: number
  videoUrl: number
  provider: number
  thumbnailUrl: number
  durationSeconds: number
  categoryId: number
  isFeatured: number
  publishedAt: number
  createdAt: number
  updatedAt: number
  deletedAt: number
  _all: number
}


export type VideoAvgAggregateInputType = {
  durationSeconds?: true
}

export type VideoSumAggregateInputType = {
  durationSeconds?: true
}

export type VideoMinAggregateInputType = {
  id?: true
  title?: true
  description?: true
  videoUrl?: true
  provider?: true
  thumbnailUrl?: true
  durationSeconds?: true
  categoryId?: true
  isFeatured?: true
  publishedAt?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
}

export type VideoMaxAggregateInputType = {
  id?: true
  title?: true
  description?: true
  videoUrl?: true
  provider?: true
  thumbnailUrl?: true
  durationSeconds?: true
  categoryId?: true
  isFeatured?: true
  publishedAt?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
}

export type VideoCountAggregateInputType = {
  id?: true
  title?: true
  description?: true
  videoUrl?: true
  provider?: true
  thumbnailUrl?: true
  durationSeconds?: true
  categoryId?: true
  isFeatured?: true
  publishedAt?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
  _all?: true
}

export type VideoAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Video to aggregate.
   */
  where?: Prisma.VideoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Videos to fetch.
   */
  orderBy?: Prisma.VideoOrderByWithRelationInput | Prisma.VideoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.VideoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Videos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Videos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Videos
  **/
  _count?: true | VideoCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: VideoAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: VideoSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: VideoMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: VideoMaxAggregateInputType
}

export type GetVideoAggregateType<T extends VideoAggregateArgs> = {
      [P in keyof T & keyof AggregateVideo]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateVideo[P]>
    : Prisma.GetScalarType<T[P], AggregateVideo[P]>
}




export type VideoGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.VideoWhereInput
  orderBy?: Prisma.VideoOrderByWithAggregationInput | Prisma.VideoOrderByWithAggregationInput[]
  by: Prisma.VideoScalarFieldEnum[] | Prisma.VideoScalarFieldEnum
  having?: Prisma.VideoScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: VideoCountAggregateInputType | true
  _avg?: VideoAvgAggregateInputType
  _sum?: VideoSumAggregateInputType
  _min?: VideoMinAggregateInputType
  _max?: VideoMaxAggregateInputType
}

export type VideoGroupByOutputType = {
  id: string
  title: string
  description: string
  videoUrl: string
  provider: $Enums.VideoProviderKind
  thumbnailUrl: string
  durationSeconds: number
  categoryId: string
  isFeatured: boolean
  publishedAt: Date
  createdAt: Date
  updatedAt: Date
  deletedAt: Date | null
  _count: VideoCountAggregateOutputType | null
  _avg: VideoAvgAggregateOutputType | null
  _sum: VideoSumAggregateOutputType | null
  _min: VideoMinAggregateOutputType | null
  _max: VideoMaxAggregateOutputType | null
}

export type GetVideoGroupByPayload<T extends VideoGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<VideoGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof VideoGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], VideoGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], VideoGroupByOutputType[P]>
      }
    >
  >



export type VideoWhereInput = {
  AND?: Prisma.VideoWhereInput | Prisma.VideoWhereInput[]
  OR?: Prisma.VideoWhereInput[]
  NOT?: Prisma.VideoWhereInput | Prisma.VideoWhereInput[]
  id?: Prisma.StringFilter<"Video"> | string
  title?: Prisma.StringFilter<"Video"> | string
  description?: Prisma.StringFilter<"Video"> | string
  videoUrl?: Prisma.StringFilter<"Video"> | string
  provider?: Prisma.EnumVideoProviderKindFilter<"Video"> | $Enums.VideoProviderKind
  thumbnailUrl?: Prisma.StringFilter<"Video"> | string
  durationSeconds?: Prisma.IntFilter<"Video"> | number
  categoryId?: Prisma.StringFilter<"Video"> | string
  isFeatured?: Prisma.BoolFilter<"Video"> | boolean
  publishedAt?: Prisma.DateTimeFilter<"Video"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"Video"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Video"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"Video"> | Date | string | null
  category?: Prisma.XOR<Prisma.CategoryScalarRelationFilter, Prisma.CategoryWhereInput>
}

export type VideoOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  videoUrl?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  thumbnailUrl?: Prisma.SortOrder
  durationSeconds?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  isFeatured?: Prisma.SortOrder
  publishedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  category?: Prisma.CategoryOrderByWithRelationInput
}

export type VideoWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.VideoWhereInput | Prisma.VideoWhereInput[]
  OR?: Prisma.VideoWhereInput[]
  NOT?: Prisma.VideoWhereInput | Prisma.VideoWhereInput[]
  title?: Prisma.StringFilter<"Video"> | string
  description?: Prisma.StringFilter<"Video"> | string
  videoUrl?: Prisma.StringFilter<"Video"> | string
  provider?: Prisma.EnumVideoProviderKindFilter<"Video"> | $Enums.VideoProviderKind
  thumbnailUrl?: Prisma.StringFilter<"Video"> | string
  durationSeconds?: Prisma.IntFilter<"Video"> | number
  categoryId?: Prisma.StringFilter<"Video"> | string
  isFeatured?: Prisma.BoolFilter<"Video"> | boolean
  publishedAt?: Prisma.DateTimeFilter<"Video"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"Video"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Video"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"Video"> | Date | string | null
  category?: Prisma.XOR<Prisma.CategoryScalarRelationFilter, Prisma.CategoryWhereInput>
}, "id">

export type VideoOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  videoUrl?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  thumbnailUrl?: Prisma.SortOrder
  durationSeconds?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  isFeatured?: Prisma.SortOrder
  publishedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.VideoCountOrderByAggregateInput
  _avg?: Prisma.VideoAvgOrderByAggregateInput
  _max?: Prisma.VideoMaxOrderByAggregateInput
  _min?: Prisma.VideoMinOrderByAggregateInput
  _sum?: Prisma.VideoSumOrderByAggregateInput
}

export type VideoScalarWhereWithAggregatesInput = {
  AND?: Prisma.VideoScalarWhereWithAggregatesInput | Prisma.VideoScalarWhereWithAggregatesInput[]
  OR?: Prisma.VideoScalarWhereWithAggregatesInput[]
  NOT?: Prisma.VideoScalarWhereWithAggregatesInput | Prisma.VideoScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Video"> | string
  title?: Prisma.StringWithAggregatesFilter<"Video"> | string
  description?: Prisma.StringWithAggregatesFilter<"Video"> | string
  videoUrl?: Prisma.StringWithAggregatesFilter<"Video"> | string
  provider?: Prisma.EnumVideoProviderKindWithAggregatesFilter<"Video"> | $Enums.VideoProviderKind
  thumbnailUrl?: Prisma.StringWithAggregatesFilter<"Video"> | string
  durationSeconds?: Prisma.IntWithAggregatesFilter<"Video"> | number
  categoryId?: Prisma.StringWithAggregatesFilter<"Video"> | string
  isFeatured?: Prisma.BoolWithAggregatesFilter<"Video"> | boolean
  publishedAt?: Prisma.DateTimeWithAggregatesFilter<"Video"> | Date | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Video"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Video"> | Date | string
  deletedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Video"> | Date | string | null
}

export type VideoCreateInput = {
  id?: string
  title: string
  description: string
  videoUrl: string
  provider?: $Enums.VideoProviderKind
  thumbnailUrl: string
  durationSeconds: number
  isFeatured?: boolean
  publishedAt: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  category: Prisma.CategoryCreateNestedOneWithoutVideoInput
}

export type VideoUncheckedCreateInput = {
  id?: string
  title: string
  description: string
  videoUrl: string
  provider?: $Enums.VideoProviderKind
  thumbnailUrl: string
  durationSeconds: number
  categoryId: string
  isFeatured?: boolean
  publishedAt: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type VideoUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  videoUrl?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.EnumVideoProviderKindFieldUpdateOperationsInput | $Enums.VideoProviderKind
  thumbnailUrl?: Prisma.StringFieldUpdateOperationsInput | string
  durationSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  isFeatured?: Prisma.BoolFieldUpdateOperationsInput | boolean
  publishedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  category?: Prisma.CategoryUpdateOneRequiredWithoutVideoNestedInput
}

export type VideoUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  videoUrl?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.EnumVideoProviderKindFieldUpdateOperationsInput | $Enums.VideoProviderKind
  thumbnailUrl?: Prisma.StringFieldUpdateOperationsInput | string
  durationSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  categoryId?: Prisma.StringFieldUpdateOperationsInput | string
  isFeatured?: Prisma.BoolFieldUpdateOperationsInput | boolean
  publishedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type VideoCreateManyInput = {
  id?: string
  title: string
  description: string
  videoUrl: string
  provider?: $Enums.VideoProviderKind
  thumbnailUrl: string
  durationSeconds: number
  categoryId: string
  isFeatured?: boolean
  publishedAt: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type VideoUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  videoUrl?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.EnumVideoProviderKindFieldUpdateOperationsInput | $Enums.VideoProviderKind
  thumbnailUrl?: Prisma.StringFieldUpdateOperationsInput | string
  durationSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  isFeatured?: Prisma.BoolFieldUpdateOperationsInput | boolean
  publishedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type VideoUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  videoUrl?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.EnumVideoProviderKindFieldUpdateOperationsInput | $Enums.VideoProviderKind
  thumbnailUrl?: Prisma.StringFieldUpdateOperationsInput | string
  durationSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  categoryId?: Prisma.StringFieldUpdateOperationsInput | string
  isFeatured?: Prisma.BoolFieldUpdateOperationsInput | boolean
  publishedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type VideoListRelationFilter = {
  every?: Prisma.VideoWhereInput
  some?: Prisma.VideoWhereInput
  none?: Prisma.VideoWhereInput
}

export type VideoOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type VideoCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  videoUrl?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  thumbnailUrl?: Prisma.SortOrder
  durationSeconds?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  isFeatured?: Prisma.SortOrder
  publishedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type VideoAvgOrderByAggregateInput = {
  durationSeconds?: Prisma.SortOrder
}

export type VideoMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  videoUrl?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  thumbnailUrl?: Prisma.SortOrder
  durationSeconds?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  isFeatured?: Prisma.SortOrder
  publishedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type VideoMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  videoUrl?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  thumbnailUrl?: Prisma.SortOrder
  durationSeconds?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  isFeatured?: Prisma.SortOrder
  publishedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type VideoSumOrderByAggregateInput = {
  durationSeconds?: Prisma.SortOrder
}

export type VideoCreateNestedManyWithoutCategoryInput = {
  create?: Prisma.XOR<Prisma.VideoCreateWithoutCategoryInput, Prisma.VideoUncheckedCreateWithoutCategoryInput> | Prisma.VideoCreateWithoutCategoryInput[] | Prisma.VideoUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.VideoCreateOrConnectWithoutCategoryInput | Prisma.VideoCreateOrConnectWithoutCategoryInput[]
  createMany?: Prisma.VideoCreateManyCategoryInputEnvelope
  connect?: Prisma.VideoWhereUniqueInput | Prisma.VideoWhereUniqueInput[]
}

export type VideoUncheckedCreateNestedManyWithoutCategoryInput = {
  create?: Prisma.XOR<Prisma.VideoCreateWithoutCategoryInput, Prisma.VideoUncheckedCreateWithoutCategoryInput> | Prisma.VideoCreateWithoutCategoryInput[] | Prisma.VideoUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.VideoCreateOrConnectWithoutCategoryInput | Prisma.VideoCreateOrConnectWithoutCategoryInput[]
  createMany?: Prisma.VideoCreateManyCategoryInputEnvelope
  connect?: Prisma.VideoWhereUniqueInput | Prisma.VideoWhereUniqueInput[]
}

export type VideoUpdateManyWithoutCategoryNestedInput = {
  create?: Prisma.XOR<Prisma.VideoCreateWithoutCategoryInput, Prisma.VideoUncheckedCreateWithoutCategoryInput> | Prisma.VideoCreateWithoutCategoryInput[] | Prisma.VideoUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.VideoCreateOrConnectWithoutCategoryInput | Prisma.VideoCreateOrConnectWithoutCategoryInput[]
  upsert?: Prisma.VideoUpsertWithWhereUniqueWithoutCategoryInput | Prisma.VideoUpsertWithWhereUniqueWithoutCategoryInput[]
  createMany?: Prisma.VideoCreateManyCategoryInputEnvelope
  set?: Prisma.VideoWhereUniqueInput | Prisma.VideoWhereUniqueInput[]
  disconnect?: Prisma.VideoWhereUniqueInput | Prisma.VideoWhereUniqueInput[]
  delete?: Prisma.VideoWhereUniqueInput | Prisma.VideoWhereUniqueInput[]
  connect?: Prisma.VideoWhereUniqueInput | Prisma.VideoWhereUniqueInput[]
  update?: Prisma.VideoUpdateWithWhereUniqueWithoutCategoryInput | Prisma.VideoUpdateWithWhereUniqueWithoutCategoryInput[]
  updateMany?: Prisma.VideoUpdateManyWithWhereWithoutCategoryInput | Prisma.VideoUpdateManyWithWhereWithoutCategoryInput[]
  deleteMany?: Prisma.VideoScalarWhereInput | Prisma.VideoScalarWhereInput[]
}

export type VideoUncheckedUpdateManyWithoutCategoryNestedInput = {
  create?: Prisma.XOR<Prisma.VideoCreateWithoutCategoryInput, Prisma.VideoUncheckedCreateWithoutCategoryInput> | Prisma.VideoCreateWithoutCategoryInput[] | Prisma.VideoUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.VideoCreateOrConnectWithoutCategoryInput | Prisma.VideoCreateOrConnectWithoutCategoryInput[]
  upsert?: Prisma.VideoUpsertWithWhereUniqueWithoutCategoryInput | Prisma.VideoUpsertWithWhereUniqueWithoutCategoryInput[]
  createMany?: Prisma.VideoCreateManyCategoryInputEnvelope
  set?: Prisma.VideoWhereUniqueInput | Prisma.VideoWhereUniqueInput[]
  disconnect?: Prisma.VideoWhereUniqueInput | Prisma.VideoWhereUniqueInput[]
  delete?: Prisma.VideoWhereUniqueInput | Prisma.VideoWhereUniqueInput[]
  connect?: Prisma.VideoWhereUniqueInput | Prisma.VideoWhereUniqueInput[]
  update?: Prisma.VideoUpdateWithWhereUniqueWithoutCategoryInput | Prisma.VideoUpdateWithWhereUniqueWithoutCategoryInput[]
  updateMany?: Prisma.VideoUpdateManyWithWhereWithoutCategoryInput | Prisma.VideoUpdateManyWithWhereWithoutCategoryInput[]
  deleteMany?: Prisma.VideoScalarWhereInput | Prisma.VideoScalarWhereInput[]
}

export type EnumVideoProviderKindFieldUpdateOperationsInput = {
  set?: $Enums.VideoProviderKind
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type VideoCreateWithoutCategoryInput = {
  id?: string
  title: string
  description: string
  videoUrl: string
  provider?: $Enums.VideoProviderKind
  thumbnailUrl: string
  durationSeconds: number
  isFeatured?: boolean
  publishedAt: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type VideoUncheckedCreateWithoutCategoryInput = {
  id?: string
  title: string
  description: string
  videoUrl: string
  provider?: $Enums.VideoProviderKind
  thumbnailUrl: string
  durationSeconds: number
  isFeatured?: boolean
  publishedAt: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type VideoCreateOrConnectWithoutCategoryInput = {
  where: Prisma.VideoWhereUniqueInput
  create: Prisma.XOR<Prisma.VideoCreateWithoutCategoryInput, Prisma.VideoUncheckedCreateWithoutCategoryInput>
}

export type VideoCreateManyCategoryInputEnvelope = {
  data: Prisma.VideoCreateManyCategoryInput | Prisma.VideoCreateManyCategoryInput[]
  skipDuplicates?: boolean
}

export type VideoUpsertWithWhereUniqueWithoutCategoryInput = {
  where: Prisma.VideoWhereUniqueInput
  update: Prisma.XOR<Prisma.VideoUpdateWithoutCategoryInput, Prisma.VideoUncheckedUpdateWithoutCategoryInput>
  create: Prisma.XOR<Prisma.VideoCreateWithoutCategoryInput, Prisma.VideoUncheckedCreateWithoutCategoryInput>
}

export type VideoUpdateWithWhereUniqueWithoutCategoryInput = {
  where: Prisma.VideoWhereUniqueInput
  data: Prisma.XOR<Prisma.VideoUpdateWithoutCategoryInput, Prisma.VideoUncheckedUpdateWithoutCategoryInput>
}

export type VideoUpdateManyWithWhereWithoutCategoryInput = {
  where: Prisma.VideoScalarWhereInput
  data: Prisma.XOR<Prisma.VideoUpdateManyMutationInput, Prisma.VideoUncheckedUpdateManyWithoutCategoryInput>
}

export type VideoScalarWhereInput = {
  AND?: Prisma.VideoScalarWhereInput | Prisma.VideoScalarWhereInput[]
  OR?: Prisma.VideoScalarWhereInput[]
  NOT?: Prisma.VideoScalarWhereInput | Prisma.VideoScalarWhereInput[]
  id?: Prisma.StringFilter<"Video"> | string
  title?: Prisma.StringFilter<"Video"> | string
  description?: Prisma.StringFilter<"Video"> | string
  videoUrl?: Prisma.StringFilter<"Video"> | string
  provider?: Prisma.EnumVideoProviderKindFilter<"Video"> | $Enums.VideoProviderKind
  thumbnailUrl?: Prisma.StringFilter<"Video"> | string
  durationSeconds?: Prisma.IntFilter<"Video"> | number
  categoryId?: Prisma.StringFilter<"Video"> | string
  isFeatured?: Prisma.BoolFilter<"Video"> | boolean
  publishedAt?: Prisma.DateTimeFilter<"Video"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"Video"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Video"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"Video"> | Date | string | null
}

export type VideoCreateManyCategoryInput = {
  id?: string
  title: string
  description: string
  videoUrl: string
  provider?: $Enums.VideoProviderKind
  thumbnailUrl: string
  durationSeconds: number
  isFeatured?: boolean
  publishedAt: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type VideoUpdateWithoutCategoryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  videoUrl?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.EnumVideoProviderKindFieldUpdateOperationsInput | $Enums.VideoProviderKind
  thumbnailUrl?: Prisma.StringFieldUpdateOperationsInput | string
  durationSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  isFeatured?: Prisma.BoolFieldUpdateOperationsInput | boolean
  publishedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type VideoUncheckedUpdateWithoutCategoryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  videoUrl?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.EnumVideoProviderKindFieldUpdateOperationsInput | $Enums.VideoProviderKind
  thumbnailUrl?: Prisma.StringFieldUpdateOperationsInput | string
  durationSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  isFeatured?: Prisma.BoolFieldUpdateOperationsInput | boolean
  publishedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type VideoUncheckedUpdateManyWithoutCategoryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  videoUrl?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.EnumVideoProviderKindFieldUpdateOperationsInput | $Enums.VideoProviderKind
  thumbnailUrl?: Prisma.StringFieldUpdateOperationsInput | string
  durationSeconds?: Prisma.IntFieldUpdateOperationsInput | number
  isFeatured?: Prisma.BoolFieldUpdateOperationsInput | boolean
  publishedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type VideoSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  videoUrl?: boolean
  provider?: boolean
  thumbnailUrl?: boolean
  durationSeconds?: boolean
  categoryId?: boolean
  isFeatured?: boolean
  publishedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  category?: boolean | Prisma.CategoryDefaultArgs<ExtArgs>
}, ExtArgs["result"]["video"]>

export type VideoSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  videoUrl?: boolean
  provider?: boolean
  thumbnailUrl?: boolean
  durationSeconds?: boolean
  categoryId?: boolean
  isFeatured?: boolean
  publishedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  category?: boolean | Prisma.CategoryDefaultArgs<ExtArgs>
}, ExtArgs["result"]["video"]>

export type VideoSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  videoUrl?: boolean
  provider?: boolean
  thumbnailUrl?: boolean
  durationSeconds?: boolean
  categoryId?: boolean
  isFeatured?: boolean
  publishedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  category?: boolean | Prisma.CategoryDefaultArgs<ExtArgs>
}, ExtArgs["result"]["video"]>

export type VideoSelectScalar = {
  id?: boolean
  title?: boolean
  description?: boolean
  videoUrl?: boolean
  provider?: boolean
  thumbnailUrl?: boolean
  durationSeconds?: boolean
  categoryId?: boolean
  isFeatured?: boolean
  publishedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
}

export type VideoOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "description" | "videoUrl" | "provider" | "thumbnailUrl" | "durationSeconds" | "categoryId" | "isFeatured" | "publishedAt" | "createdAt" | "updatedAt" | "deletedAt", ExtArgs["result"]["video"]>
export type VideoInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  category?: boolean | Prisma.CategoryDefaultArgs<ExtArgs>
}
export type VideoIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  category?: boolean | Prisma.CategoryDefaultArgs<ExtArgs>
}
export type VideoIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  category?: boolean | Prisma.CategoryDefaultArgs<ExtArgs>
}

export type $VideoPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Video"
  objects: {
    category: Prisma.$CategoryPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string
    description: string
    videoUrl: string
    provider: $Enums.VideoProviderKind
    thumbnailUrl: string
    durationSeconds: number
    categoryId: string
    isFeatured: boolean
    publishedAt: Date
    createdAt: Date
    updatedAt: Date
    deletedAt: Date | null
  }, ExtArgs["result"]["video"]>
  composites: {}
}

export type VideoGetPayload<S extends boolean | null | undefined | VideoDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$VideoPayload, S>

export type VideoCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<VideoFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: VideoCountAggregateInputType | true
  }

export interface VideoDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Video'], meta: { name: 'Video' } }
  /**
   * Find zero or one Video that matches the filter.
   * @param {VideoFindUniqueArgs} args - Arguments to find a Video
   * @example
   * // Get one Video
   * const video = await prisma.video.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends VideoFindUniqueArgs>(args: Prisma.SelectSubset<T, VideoFindUniqueArgs<ExtArgs>>): Prisma.Prisma__VideoClient<runtime.Types.Result.GetResult<Prisma.$VideoPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Video that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {VideoFindUniqueOrThrowArgs} args - Arguments to find a Video
   * @example
   * // Get one Video
   * const video = await prisma.video.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends VideoFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, VideoFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__VideoClient<runtime.Types.Result.GetResult<Prisma.$VideoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Video that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VideoFindFirstArgs} args - Arguments to find a Video
   * @example
   * // Get one Video
   * const video = await prisma.video.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends VideoFindFirstArgs>(args?: Prisma.SelectSubset<T, VideoFindFirstArgs<ExtArgs>>): Prisma.Prisma__VideoClient<runtime.Types.Result.GetResult<Prisma.$VideoPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Video that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VideoFindFirstOrThrowArgs} args - Arguments to find a Video
   * @example
   * // Get one Video
   * const video = await prisma.video.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends VideoFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, VideoFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__VideoClient<runtime.Types.Result.GetResult<Prisma.$VideoPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Videos that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VideoFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Videos
   * const videos = await prisma.video.findMany()
   * 
   * // Get first 10 Videos
   * const videos = await prisma.video.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const videoWithIdOnly = await prisma.video.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends VideoFindManyArgs>(args?: Prisma.SelectSubset<T, VideoFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VideoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Video.
   * @param {VideoCreateArgs} args - Arguments to create a Video.
   * @example
   * // Create one Video
   * const Video = await prisma.video.create({
   *   data: {
   *     // ... data to create a Video
   *   }
   * })
   * 
   */
  create<T extends VideoCreateArgs>(args: Prisma.SelectSubset<T, VideoCreateArgs<ExtArgs>>): Prisma.Prisma__VideoClient<runtime.Types.Result.GetResult<Prisma.$VideoPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Videos.
   * @param {VideoCreateManyArgs} args - Arguments to create many Videos.
   * @example
   * // Create many Videos
   * const video = await prisma.video.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends VideoCreateManyArgs>(args?: Prisma.SelectSubset<T, VideoCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Videos and returns the data saved in the database.
   * @param {VideoCreateManyAndReturnArgs} args - Arguments to create many Videos.
   * @example
   * // Create many Videos
   * const video = await prisma.video.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Videos and only return the `id`
   * const videoWithIdOnly = await prisma.video.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends VideoCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, VideoCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VideoPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Video.
   * @param {VideoDeleteArgs} args - Arguments to delete one Video.
   * @example
   * // Delete one Video
   * const Video = await prisma.video.delete({
   *   where: {
   *     // ... filter to delete one Video
   *   }
   * })
   * 
   */
  delete<T extends VideoDeleteArgs>(args: Prisma.SelectSubset<T, VideoDeleteArgs<ExtArgs>>): Prisma.Prisma__VideoClient<runtime.Types.Result.GetResult<Prisma.$VideoPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Video.
   * @param {VideoUpdateArgs} args - Arguments to update one Video.
   * @example
   * // Update one Video
   * const video = await prisma.video.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends VideoUpdateArgs>(args: Prisma.SelectSubset<T, VideoUpdateArgs<ExtArgs>>): Prisma.Prisma__VideoClient<runtime.Types.Result.GetResult<Prisma.$VideoPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Videos.
   * @param {VideoDeleteManyArgs} args - Arguments to filter Videos to delete.
   * @example
   * // Delete a few Videos
   * const { count } = await prisma.video.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends VideoDeleteManyArgs>(args?: Prisma.SelectSubset<T, VideoDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Videos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VideoUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Videos
   * const video = await prisma.video.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends VideoUpdateManyArgs>(args: Prisma.SelectSubset<T, VideoUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Videos and returns the data updated in the database.
   * @param {VideoUpdateManyAndReturnArgs} args - Arguments to update many Videos.
   * @example
   * // Update many Videos
   * const video = await prisma.video.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Videos and only return the `id`
   * const videoWithIdOnly = await prisma.video.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends VideoUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, VideoUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VideoPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Video.
   * @param {VideoUpsertArgs} args - Arguments to update or create a Video.
   * @example
   * // Update or create a Video
   * const video = await prisma.video.upsert({
   *   create: {
   *     // ... data to create a Video
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Video we want to update
   *   }
   * })
   */
  upsert<T extends VideoUpsertArgs>(args: Prisma.SelectSubset<T, VideoUpsertArgs<ExtArgs>>): Prisma.Prisma__VideoClient<runtime.Types.Result.GetResult<Prisma.$VideoPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Videos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VideoCountArgs} args - Arguments to filter Videos to count.
   * @example
   * // Count the number of Videos
   * const count = await prisma.video.count({
   *   where: {
   *     // ... the filter for the Videos we want to count
   *   }
   * })
  **/
  count<T extends VideoCountArgs>(
    args?: Prisma.Subset<T, VideoCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], VideoCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Video.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VideoAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends VideoAggregateArgs>(args: Prisma.Subset<T, VideoAggregateArgs>): Prisma.PrismaPromise<GetVideoAggregateType<T>>

  /**
   * Group by Video.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VideoGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends VideoGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: VideoGroupByArgs['orderBy'] }
      : { orderBy?: VideoGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, VideoGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetVideoGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Video model
 */
readonly fields: VideoFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Video.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__VideoClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  category<T extends Prisma.CategoryDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CategoryDefaultArgs<ExtArgs>>): Prisma.Prisma__CategoryClient<runtime.Types.Result.GetResult<Prisma.$CategoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Video model
 */
export interface VideoFieldRefs {
  readonly id: Prisma.FieldRef<"Video", 'String'>
  readonly title: Prisma.FieldRef<"Video", 'String'>
  readonly description: Prisma.FieldRef<"Video", 'String'>
  readonly videoUrl: Prisma.FieldRef<"Video", 'String'>
  readonly provider: Prisma.FieldRef<"Video", 'VideoProviderKind'>
  readonly thumbnailUrl: Prisma.FieldRef<"Video", 'String'>
  readonly durationSeconds: Prisma.FieldRef<"Video", 'Int'>
  readonly categoryId: Prisma.FieldRef<"Video", 'String'>
  readonly isFeatured: Prisma.FieldRef<"Video", 'Boolean'>
  readonly publishedAt: Prisma.FieldRef<"Video", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"Video", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Video", 'DateTime'>
  readonly deletedAt: Prisma.FieldRef<"Video", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Video findUnique
 */
export type VideoFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Video
   */
  select?: Prisma.VideoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Video
   */
  omit?: Prisma.VideoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoInclude<ExtArgs> | null
  /**
   * Filter, which Video to fetch.
   */
  where: Prisma.VideoWhereUniqueInput
}

/**
 * Video findUniqueOrThrow
 */
export type VideoFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Video
   */
  select?: Prisma.VideoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Video
   */
  omit?: Prisma.VideoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoInclude<ExtArgs> | null
  /**
   * Filter, which Video to fetch.
   */
  where: Prisma.VideoWhereUniqueInput
}

/**
 * Video findFirst
 */
export type VideoFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Video
   */
  select?: Prisma.VideoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Video
   */
  omit?: Prisma.VideoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoInclude<ExtArgs> | null
  /**
   * Filter, which Video to fetch.
   */
  where?: Prisma.VideoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Videos to fetch.
   */
  orderBy?: Prisma.VideoOrderByWithRelationInput | Prisma.VideoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Videos.
   */
  cursor?: Prisma.VideoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Videos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Videos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Videos.
   */
  distinct?: Prisma.VideoScalarFieldEnum | Prisma.VideoScalarFieldEnum[]
}

/**
 * Video findFirstOrThrow
 */
export type VideoFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Video
   */
  select?: Prisma.VideoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Video
   */
  omit?: Prisma.VideoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoInclude<ExtArgs> | null
  /**
   * Filter, which Video to fetch.
   */
  where?: Prisma.VideoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Videos to fetch.
   */
  orderBy?: Prisma.VideoOrderByWithRelationInput | Prisma.VideoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Videos.
   */
  cursor?: Prisma.VideoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Videos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Videos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Videos.
   */
  distinct?: Prisma.VideoScalarFieldEnum | Prisma.VideoScalarFieldEnum[]
}

/**
 * Video findMany
 */
export type VideoFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Video
   */
  select?: Prisma.VideoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Video
   */
  omit?: Prisma.VideoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoInclude<ExtArgs> | null
  /**
   * Filter, which Videos to fetch.
   */
  where?: Prisma.VideoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Videos to fetch.
   */
  orderBy?: Prisma.VideoOrderByWithRelationInput | Prisma.VideoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Videos.
   */
  cursor?: Prisma.VideoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Videos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Videos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Videos.
   */
  distinct?: Prisma.VideoScalarFieldEnum | Prisma.VideoScalarFieldEnum[]
}

/**
 * Video create
 */
export type VideoCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Video
   */
  select?: Prisma.VideoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Video
   */
  omit?: Prisma.VideoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoInclude<ExtArgs> | null
  /**
   * The data needed to create a Video.
   */
  data: Prisma.XOR<Prisma.VideoCreateInput, Prisma.VideoUncheckedCreateInput>
}

/**
 * Video createMany
 */
export type VideoCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Videos.
   */
  data: Prisma.VideoCreateManyInput | Prisma.VideoCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Video createManyAndReturn
 */
export type VideoCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Video
   */
  select?: Prisma.VideoSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Video
   */
  omit?: Prisma.VideoOmit<ExtArgs> | null
  /**
   * The data used to create many Videos.
   */
  data: Prisma.VideoCreateManyInput | Prisma.VideoCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Video update
 */
export type VideoUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Video
   */
  select?: Prisma.VideoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Video
   */
  omit?: Prisma.VideoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoInclude<ExtArgs> | null
  /**
   * The data needed to update a Video.
   */
  data: Prisma.XOR<Prisma.VideoUpdateInput, Prisma.VideoUncheckedUpdateInput>
  /**
   * Choose, which Video to update.
   */
  where: Prisma.VideoWhereUniqueInput
}

/**
 * Video updateMany
 */
export type VideoUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Videos.
   */
  data: Prisma.XOR<Prisma.VideoUpdateManyMutationInput, Prisma.VideoUncheckedUpdateManyInput>
  /**
   * Filter which Videos to update
   */
  where?: Prisma.VideoWhereInput
  /**
   * Limit how many Videos to update.
   */
  limit?: number
}

/**
 * Video updateManyAndReturn
 */
export type VideoUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Video
   */
  select?: Prisma.VideoSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Video
   */
  omit?: Prisma.VideoOmit<ExtArgs> | null
  /**
   * The data used to update Videos.
   */
  data: Prisma.XOR<Prisma.VideoUpdateManyMutationInput, Prisma.VideoUncheckedUpdateManyInput>
  /**
   * Filter which Videos to update
   */
  where?: Prisma.VideoWhereInput
  /**
   * Limit how many Videos to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Video upsert
 */
export type VideoUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Video
   */
  select?: Prisma.VideoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Video
   */
  omit?: Prisma.VideoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoInclude<ExtArgs> | null
  /**
   * The filter to search for the Video to update in case it exists.
   */
  where: Prisma.VideoWhereUniqueInput
  /**
   * In case the Video found by the `where` argument doesn't exist, create a new Video with this data.
   */
  create: Prisma.XOR<Prisma.VideoCreateInput, Prisma.VideoUncheckedCreateInput>
  /**
   * In case the Video was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.VideoUpdateInput, Prisma.VideoUncheckedUpdateInput>
}

/**
 * Video delete
 */
export type VideoDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Video
   */
  select?: Prisma.VideoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Video
   */
  omit?: Prisma.VideoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoInclude<ExtArgs> | null
  /**
   * Filter which Video to delete.
   */
  where: Prisma.VideoWhereUniqueInput
}

/**
 * Video deleteMany
 */
export type VideoDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Videos to delete
   */
  where?: Prisma.VideoWhereInput
  /**
   * Limit how many Videos to delete.
   */
  limit?: number
}

/**
 * Video without action
 */
export type VideoDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Video
   */
  select?: Prisma.VideoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Video
   */
  omit?: Prisma.VideoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VideoInclude<ExtArgs> | null
}
