
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports various common sort, input & filter types that are not directly linked to a particular model.
 *
 * 🟢 You can import this file directly.
 */

import type * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums"
import type * as Prisma from "./internal/prismaNamespace"


export type StringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringFilter<$PrismaModel> | string
}

export type EnumUserRoleKindFilter<$PrismaModel = never> = {
  equals?: $Enums.UserRoleKind | Prisma.EnumUserRoleKindFieldRefInput<$PrismaModel>
  in?: $Enums.UserRoleKind[] | Prisma.ListEnumUserRoleKindFieldRefInput<$PrismaModel>
  notIn?: $Enums.UserRoleKind[] | Prisma.ListEnumUserRoleKindFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumUserRoleKindFilter<$PrismaModel> | $Enums.UserRoleKind
}

export type EnumMembershipStatusKindFilter<$PrismaModel = never> = {
  equals?: $Enums.MembershipStatusKind | Prisma.EnumMembershipStatusKindFieldRefInput<$PrismaModel>
  in?: $Enums.MembershipStatusKind[] | Prisma.ListEnumMembershipStatusKindFieldRefInput<$PrismaModel>
  notIn?: $Enums.MembershipStatusKind[] | Prisma.ListEnumMembershipStatusKindFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumMembershipStatusKindFilter<$PrismaModel> | $Enums.MembershipStatusKind
}

export type DateTimeFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string
}

export type DateTimeNullableFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableFilter<$PrismaModel> | Date | string | null
}

export type SortOrderInput = {
  sort: Prisma.SortOrder
  nulls?: Prisma.NullsOrder
}

export type StringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedStringFilter<$PrismaModel>
  _max?: Prisma.NestedStringFilter<$PrismaModel>
}

export type EnumUserRoleKindWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.UserRoleKind | Prisma.EnumUserRoleKindFieldRefInput<$PrismaModel>
  in?: $Enums.UserRoleKind[] | Prisma.ListEnumUserRoleKindFieldRefInput<$PrismaModel>
  notIn?: $Enums.UserRoleKind[] | Prisma.ListEnumUserRoleKindFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumUserRoleKindWithAggregatesFilter<$PrismaModel> | $Enums.UserRoleKind
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumUserRoleKindFilter<$PrismaModel>
  _max?: Prisma.NestedEnumUserRoleKindFilter<$PrismaModel>
}

export type EnumMembershipStatusKindWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.MembershipStatusKind | Prisma.EnumMembershipStatusKindFieldRefInput<$PrismaModel>
  in?: $Enums.MembershipStatusKind[] | Prisma.ListEnumMembershipStatusKindFieldRefInput<$PrismaModel>
  notIn?: $Enums.MembershipStatusKind[] | Prisma.ListEnumMembershipStatusKindFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumMembershipStatusKindWithAggregatesFilter<$PrismaModel> | $Enums.MembershipStatusKind
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumMembershipStatusKindFilter<$PrismaModel>
  _max?: Prisma.NestedEnumMembershipStatusKindFilter<$PrismaModel>
}

export type DateTimeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel> | Date | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeFilter<$PrismaModel>
}

export type DateTimeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableWithAggregatesFilter<$PrismaModel> | Date | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
}

export type EnumVideoProviderKindFilter<$PrismaModel = never> = {
  equals?: $Enums.VideoProviderKind | Prisma.EnumVideoProviderKindFieldRefInput<$PrismaModel>
  in?: $Enums.VideoProviderKind[] | Prisma.ListEnumVideoProviderKindFieldRefInput<$PrismaModel>
  notIn?: $Enums.VideoProviderKind[] | Prisma.ListEnumVideoProviderKindFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumVideoProviderKindFilter<$PrismaModel> | $Enums.VideoProviderKind
}

export type IntFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntFilter<$PrismaModel> | number
}

export type BoolFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolFilter<$PrismaModel> | boolean
}

export type EnumVideoProviderKindWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.VideoProviderKind | Prisma.EnumVideoProviderKindFieldRefInput<$PrismaModel>
  in?: $Enums.VideoProviderKind[] | Prisma.ListEnumVideoProviderKindFieldRefInput<$PrismaModel>
  notIn?: $Enums.VideoProviderKind[] | Prisma.ListEnumVideoProviderKindFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumVideoProviderKindWithAggregatesFilter<$PrismaModel> | $Enums.VideoProviderKind
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumVideoProviderKindFilter<$PrismaModel>
  _max?: Prisma.NestedEnumVideoProviderKindFilter<$PrismaModel>
}

export type IntWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntWithAggregatesFilter<$PrismaModel> | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedIntFilter<$PrismaModel>
  _max?: Prisma.NestedIntFilter<$PrismaModel>
}

export type BoolWithAggregatesFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolWithAggregatesFilter<$PrismaModel> | boolean
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedBoolFilter<$PrismaModel>
  _max?: Prisma.NestedBoolFilter<$PrismaModel>
}

export type StringNullableFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringNullableFilter<$PrismaModel> | string | null
}

export type StringNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringNullableWithAggregatesFilter<$PrismaModel> | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedStringNullableFilter<$PrismaModel>
  _max?: Prisma.NestedStringNullableFilter<$PrismaModel>
}

export type EnumLiveSessionPlatformKindFilter<$PrismaModel = never> = {
  equals?: $Enums.LiveSessionPlatformKind | Prisma.EnumLiveSessionPlatformKindFieldRefInput<$PrismaModel>
  in?: $Enums.LiveSessionPlatformKind[] | Prisma.ListEnumLiveSessionPlatformKindFieldRefInput<$PrismaModel>
  notIn?: $Enums.LiveSessionPlatformKind[] | Prisma.ListEnumLiveSessionPlatformKindFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumLiveSessionPlatformKindFilter<$PrismaModel> | $Enums.LiveSessionPlatformKind
}

export type EnumLiveSessionStatusKindFilter<$PrismaModel = never> = {
  equals?: $Enums.LiveSessionStatusKind | Prisma.EnumLiveSessionStatusKindFieldRefInput<$PrismaModel>
  in?: $Enums.LiveSessionStatusKind[] | Prisma.ListEnumLiveSessionStatusKindFieldRefInput<$PrismaModel>
  notIn?: $Enums.LiveSessionStatusKind[] | Prisma.ListEnumLiveSessionStatusKindFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumLiveSessionStatusKindFilter<$PrismaModel> | $Enums.LiveSessionStatusKind
}

export type EnumLiveSessionPlatformKindWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.LiveSessionPlatformKind | Prisma.EnumLiveSessionPlatformKindFieldRefInput<$PrismaModel>
  in?: $Enums.LiveSessionPlatformKind[] | Prisma.ListEnumLiveSessionPlatformKindFieldRefInput<$PrismaModel>
  notIn?: $Enums.LiveSessionPlatformKind[] | Prisma.ListEnumLiveSessionPlatformKindFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumLiveSessionPlatformKindWithAggregatesFilter<$PrismaModel> | $Enums.LiveSessionPlatformKind
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumLiveSessionPlatformKindFilter<$PrismaModel>
  _max?: Prisma.NestedEnumLiveSessionPlatformKindFilter<$PrismaModel>
}

export type EnumLiveSessionStatusKindWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.LiveSessionStatusKind | Prisma.EnumLiveSessionStatusKindFieldRefInput<$PrismaModel>
  in?: $Enums.LiveSessionStatusKind[] | Prisma.ListEnumLiveSessionStatusKindFieldRefInput<$PrismaModel>
  notIn?: $Enums.LiveSessionStatusKind[] | Prisma.ListEnumLiveSessionStatusKindFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumLiveSessionStatusKindWithAggregatesFilter<$PrismaModel> | $Enums.LiveSessionStatusKind
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumLiveSessionStatusKindFilter<$PrismaModel>
  _max?: Prisma.NestedEnumLiveSessionStatusKindFilter<$PrismaModel>
}

export type NestedStringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringFilter<$PrismaModel> | string
}

export type NestedEnumUserRoleKindFilter<$PrismaModel = never> = {
  equals?: $Enums.UserRoleKind | Prisma.EnumUserRoleKindFieldRefInput<$PrismaModel>
  in?: $Enums.UserRoleKind[] | Prisma.ListEnumUserRoleKindFieldRefInput<$PrismaModel>
  notIn?: $Enums.UserRoleKind[] | Prisma.ListEnumUserRoleKindFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumUserRoleKindFilter<$PrismaModel> | $Enums.UserRoleKind
}

export type NestedEnumMembershipStatusKindFilter<$PrismaModel = never> = {
  equals?: $Enums.MembershipStatusKind | Prisma.EnumMembershipStatusKindFieldRefInput<$PrismaModel>
  in?: $Enums.MembershipStatusKind[] | Prisma.ListEnumMembershipStatusKindFieldRefInput<$PrismaModel>
  notIn?: $Enums.MembershipStatusKind[] | Prisma.ListEnumMembershipStatusKindFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumMembershipStatusKindFilter<$PrismaModel> | $Enums.MembershipStatusKind
}

export type NestedDateTimeFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string
}

export type NestedDateTimeNullableFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableFilter<$PrismaModel> | Date | string | null
}

export type NestedStringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedStringFilter<$PrismaModel>
  _max?: Prisma.NestedStringFilter<$PrismaModel>
}

export type NestedIntFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntFilter<$PrismaModel> | number
}

export type NestedEnumUserRoleKindWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.UserRoleKind | Prisma.EnumUserRoleKindFieldRefInput<$PrismaModel>
  in?: $Enums.UserRoleKind[] | Prisma.ListEnumUserRoleKindFieldRefInput<$PrismaModel>
  notIn?: $Enums.UserRoleKind[] | Prisma.ListEnumUserRoleKindFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumUserRoleKindWithAggregatesFilter<$PrismaModel> | $Enums.UserRoleKind
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumUserRoleKindFilter<$PrismaModel>
  _max?: Prisma.NestedEnumUserRoleKindFilter<$PrismaModel>
}

export type NestedEnumMembershipStatusKindWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.MembershipStatusKind | Prisma.EnumMembershipStatusKindFieldRefInput<$PrismaModel>
  in?: $Enums.MembershipStatusKind[] | Prisma.ListEnumMembershipStatusKindFieldRefInput<$PrismaModel>
  notIn?: $Enums.MembershipStatusKind[] | Prisma.ListEnumMembershipStatusKindFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumMembershipStatusKindWithAggregatesFilter<$PrismaModel> | $Enums.MembershipStatusKind
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumMembershipStatusKindFilter<$PrismaModel>
  _max?: Prisma.NestedEnumMembershipStatusKindFilter<$PrismaModel>
}

export type NestedDateTimeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel> | Date | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeFilter<$PrismaModel>
}

export type NestedDateTimeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableWithAggregatesFilter<$PrismaModel> | Date | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
}

export type NestedIntNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableFilter<$PrismaModel> | number | null
}

export type NestedEnumVideoProviderKindFilter<$PrismaModel = never> = {
  equals?: $Enums.VideoProviderKind | Prisma.EnumVideoProviderKindFieldRefInput<$PrismaModel>
  in?: $Enums.VideoProviderKind[] | Prisma.ListEnumVideoProviderKindFieldRefInput<$PrismaModel>
  notIn?: $Enums.VideoProviderKind[] | Prisma.ListEnumVideoProviderKindFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumVideoProviderKindFilter<$PrismaModel> | $Enums.VideoProviderKind
}

export type NestedBoolFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolFilter<$PrismaModel> | boolean
}

export type NestedEnumVideoProviderKindWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.VideoProviderKind | Prisma.EnumVideoProviderKindFieldRefInput<$PrismaModel>
  in?: $Enums.VideoProviderKind[] | Prisma.ListEnumVideoProviderKindFieldRefInput<$PrismaModel>
  notIn?: $Enums.VideoProviderKind[] | Prisma.ListEnumVideoProviderKindFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumVideoProviderKindWithAggregatesFilter<$PrismaModel> | $Enums.VideoProviderKind
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumVideoProviderKindFilter<$PrismaModel>
  _max?: Prisma.NestedEnumVideoProviderKindFilter<$PrismaModel>
}

export type NestedIntWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntWithAggregatesFilter<$PrismaModel> | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedIntFilter<$PrismaModel>
  _max?: Prisma.NestedIntFilter<$PrismaModel>
}

export type NestedFloatFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatFilter<$PrismaModel> | number
}

export type NestedBoolWithAggregatesFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolWithAggregatesFilter<$PrismaModel> | boolean
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedBoolFilter<$PrismaModel>
  _max?: Prisma.NestedBoolFilter<$PrismaModel>
}

export type NestedStringNullableFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringNullableFilter<$PrismaModel> | string | null
}

export type NestedStringNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringNullableWithAggregatesFilter<$PrismaModel> | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedStringNullableFilter<$PrismaModel>
  _max?: Prisma.NestedStringNullableFilter<$PrismaModel>
}

export type NestedEnumLiveSessionPlatformKindFilter<$PrismaModel = never> = {
  equals?: $Enums.LiveSessionPlatformKind | Prisma.EnumLiveSessionPlatformKindFieldRefInput<$PrismaModel>
  in?: $Enums.LiveSessionPlatformKind[] | Prisma.ListEnumLiveSessionPlatformKindFieldRefInput<$PrismaModel>
  notIn?: $Enums.LiveSessionPlatformKind[] | Prisma.ListEnumLiveSessionPlatformKindFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumLiveSessionPlatformKindFilter<$PrismaModel> | $Enums.LiveSessionPlatformKind
}

export type NestedEnumLiveSessionStatusKindFilter<$PrismaModel = never> = {
  equals?: $Enums.LiveSessionStatusKind | Prisma.EnumLiveSessionStatusKindFieldRefInput<$PrismaModel>
  in?: $Enums.LiveSessionStatusKind[] | Prisma.ListEnumLiveSessionStatusKindFieldRefInput<$PrismaModel>
  notIn?: $Enums.LiveSessionStatusKind[] | Prisma.ListEnumLiveSessionStatusKindFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumLiveSessionStatusKindFilter<$PrismaModel> | $Enums.LiveSessionStatusKind
}

export type NestedEnumLiveSessionPlatformKindWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.LiveSessionPlatformKind | Prisma.EnumLiveSessionPlatformKindFieldRefInput<$PrismaModel>
  in?: $Enums.LiveSessionPlatformKind[] | Prisma.ListEnumLiveSessionPlatformKindFieldRefInput<$PrismaModel>
  notIn?: $Enums.LiveSessionPlatformKind[] | Prisma.ListEnumLiveSessionPlatformKindFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumLiveSessionPlatformKindWithAggregatesFilter<$PrismaModel> | $Enums.LiveSessionPlatformKind
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumLiveSessionPlatformKindFilter<$PrismaModel>
  _max?: Prisma.NestedEnumLiveSessionPlatformKindFilter<$PrismaModel>
}

export type NestedEnumLiveSessionStatusKindWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.LiveSessionStatusKind | Prisma.EnumLiveSessionStatusKindFieldRefInput<$PrismaModel>
  in?: $Enums.LiveSessionStatusKind[] | Prisma.ListEnumLiveSessionStatusKindFieldRefInput<$PrismaModel>
  notIn?: $Enums.LiveSessionStatusKind[] | Prisma.ListEnumLiveSessionStatusKindFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumLiveSessionStatusKindWithAggregatesFilter<$PrismaModel> | $Enums.LiveSessionStatusKind
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumLiveSessionStatusKindFilter<$PrismaModel>
  _max?: Prisma.NestedEnumLiveSessionStatusKindFilter<$PrismaModel>
}


