
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const VideoProviderKind = {
  UPLOAD: 'UPLOAD',
  VIMEO: 'VIMEO',
  YOUTUBE: 'YOUTUBE',
  OTHER: 'OTHER'
} as const

export type VideoProviderKind = (typeof VideoProviderKind)[keyof typeof VideoProviderKind]


export const LiveSessionPlatformKind = {
  ZOOM: 'ZOOM',
  GOOGLE_MEET: 'GOOGLE_MEET',
  OTHER: 'OTHER'
} as const

export type LiveSessionPlatformKind = (typeof LiveSessionPlatformKind)[keyof typeof LiveSessionPlatformKind]


export const LiveSessionStatusKind = {
  SCHEDULED: 'SCHEDULED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
} as const

export type LiveSessionStatusKind = (typeof LiveSessionStatusKind)[keyof typeof LiveSessionStatusKind]


export const UserRoleKind = {
  MEMBER: 'MEMBER',
  ADMIN: 'ADMIN'
} as const

export type UserRoleKind = (typeof UserRoleKind)[keyof typeof UserRoleKind]


export const MembershipStatusKind = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  EXPIRED: 'EXPIRED'
} as const

export type MembershipStatusKind = (typeof MembershipStatusKind)[keyof typeof MembershipStatusKind]


export const SignalTypeKind = {
  SWING: 'SWING',
  TRADING: 'TRADING',
  POSITION: 'POSITION'
} as const

export type SignalTypeKind = (typeof SignalTypeKind)[keyof typeof SignalTypeKind]


export const SignalStatusKind = {
  ACTIVE: 'ACTIVE',
  TP1_HIT: 'TP1_HIT',
  TP2_HIT: 'TP2_HIT',
  STOP_LOSS: 'STOP_LOSS',
  CLOSED: 'CLOSED'
} as const

export type SignalStatusKind = (typeof SignalStatusKind)[keyof typeof SignalStatusKind]


export const SignalEventKind = {
  ENTRY: 'ENTRY',
  UPDATE: 'UPDATE',
  TARGET: 'TARGET',
  STOP_LOSS: 'STOP_LOSS'
} as const

export type SignalEventKind = (typeof SignalEventKind)[keyof typeof SignalEventKind]


export const SignalEventStateKind = {
  DONE: 'DONE',
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE'
} as const

export type SignalEventStateKind = (typeof SignalEventStateKind)[keyof typeof SignalEventStateKind]
