
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  Category: 'Category',
  Video: 'Video',
  News: 'News',
  Announcement: 'Announcement',
  LiveSession: 'LiveSession',
  Signal: 'Signal',
  SignalEvent: 'SignalEvent',
  SignalWatchlistItem: 'SignalWatchlistItem',
  Stock: 'Stock',
  IdxDisclosure: 'IdxDisclosure',
  CalendarEvent: 'CalendarEvent',
  DiscussionThread: 'DiscussionThread',
  DiscussionReply: 'DiscussionReply',
  BrokerSummary: 'BrokerSummary',
  StockSummary: 'StockSummary',
  IndexSummary: 'IndexSummary',
  MarketIndexSnapshot: 'MarketIndexSnapshot'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  name: 'name',
  password: 'password',
  role: 'role',
  membershipStatus: 'membershipStatus',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const CategoryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CategoryScalarFieldEnum = (typeof CategoryScalarFieldEnum)[keyof typeof CategoryScalarFieldEnum]


export const VideoScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  videoUrl: 'videoUrl',
  provider: 'provider',
  thumbnailUrl: 'thumbnailUrl',
  durationSeconds: 'durationSeconds',
  categoryId: 'categoryId',
  isFeatured: 'isFeatured',
  publishedAt: 'publishedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
} as const

export type VideoScalarFieldEnum = (typeof VideoScalarFieldEnum)[keyof typeof VideoScalarFieldEnum]


export const NewsScalarFieldEnum = {
  id: 'id',
  title: 'title',
  summary: 'summary',
  content: 'content',
  imageUrl: 'imageUrl',
  categoryId: 'categoryId',
  isFeatured: 'isFeatured',
  publishedAt: 'publishedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
} as const

export type NewsScalarFieldEnum = (typeof NewsScalarFieldEnum)[keyof typeof NewsScalarFieldEnum]


export const AnnouncementScalarFieldEnum = {
  id: 'id',
  title: 'title',
  content: 'content',
  ctaLabel: 'ctaLabel',
  ctaUrl: 'ctaUrl',
  isFeatured: 'isFeatured',
  publishedAt: 'publishedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
} as const

export type AnnouncementScalarFieldEnum = (typeof AnnouncementScalarFieldEnum)[keyof typeof AnnouncementScalarFieldEnum]


export const LiveSessionScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  scheduledAt: 'scheduledAt',
  platform: 'platform',
  joinUrl: 'joinUrl',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
} as const

export type LiveSessionScalarFieldEnum = (typeof LiveSessionScalarFieldEnum)[keyof typeof LiveSessionScalarFieldEnum]


export const SignalScalarFieldEnum = {
  id: 'id',
  ticker: 'ticker',
  companyName: 'companyName',
  type: 'type',
  entryLow: 'entryLow',
  entryHigh: 'entryHigh',
  currentPrice: 'currentPrice',
  target1: 'target1',
  target2: 'target2',
  stopLoss: 'stopLoss',
  status: 'status',
  riskReward: 'riskReward',
  timeHorizon: 'timeHorizon',
  thesis: 'thesis',
  chartImages: 'chartImages',
  keyCatalysts: 'keyCatalysts',
  issuedAt: 'issuedAt',
  closedAt: 'closedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
} as const

export type SignalScalarFieldEnum = (typeof SignalScalarFieldEnum)[keyof typeof SignalScalarFieldEnum]


export const SignalEventScalarFieldEnum = {
  id: 'id',
  signalId: 'signalId',
  kind: 'kind',
  state: 'state',
  title: 'title',
  detail: 'detail',
  occurredAt: 'occurredAt',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type SignalEventScalarFieldEnum = (typeof SignalEventScalarFieldEnum)[keyof typeof SignalEventScalarFieldEnum]


export const SignalWatchlistItemScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  signalId: 'signalId',
  createdAt: 'createdAt'
} as const

export type SignalWatchlistItemScalarFieldEnum = (typeof SignalWatchlistItemScalarFieldEnum)[keyof typeof SignalWatchlistItemScalarFieldEnum]


export const StockScalarFieldEnum = {
  id: 'id',
  ticker: 'ticker',
  name: 'name',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type StockScalarFieldEnum = (typeof StockScalarFieldEnum)[keyof typeof StockScalarFieldEnum]


export const IdxDisclosureScalarFieldEnum = {
  id: 'id',
  ticker: 'ticker',
  companyName: 'companyName',
  kind: 'kind',
  title: 'title',
  summary: 'summary',
  documentUrl: 'documentUrl',
  disclosedAt: 'disclosedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
} as const

export type IdxDisclosureScalarFieldEnum = (typeof IdxDisclosureScalarFieldEnum)[keyof typeof IdxDisclosureScalarFieldEnum]


export const CalendarEventScalarFieldEnum = {
  id: 'id',
  ticker: 'ticker',
  title: 'title',
  kind: 'kind',
  detail: 'detail',
  eventDate: 'eventDate',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
} as const

export type CalendarEventScalarFieldEnum = (typeof CalendarEventScalarFieldEnum)[keyof typeof CalendarEventScalarFieldEnum]


export const DiscussionThreadScalarFieldEnum = {
  id: 'id',
  authorId: 'authorId',
  title: 'title',
  body: 'body',
  ticker: 'ticker',
  isPinned: 'isPinned',
  isLocked: 'isLocked',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
} as const

export type DiscussionThreadScalarFieldEnum = (typeof DiscussionThreadScalarFieldEnum)[keyof typeof DiscussionThreadScalarFieldEnum]


export const DiscussionReplyScalarFieldEnum = {
  id: 'id',
  threadId: 'threadId',
  authorId: 'authorId',
  body: 'body',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
} as const

export type DiscussionReplyScalarFieldEnum = (typeof DiscussionReplyScalarFieldEnum)[keyof typeof DiscussionReplyScalarFieldEnum]


export const BrokerSummaryScalarFieldEnum = {
  id: 'id',
  date: 'date',
  ticker: 'ticker',
  broker: 'broker',
  isForeign: 'isForeign',
  action: 'action',
  avgPx: 'avgPx',
  volume: 'volume',
  value: 'value',
  isNet: 'isNet',
  txnType: 'txnType',
  createdAt: 'createdAt',
  frequency: 'frequency'
} as const

export type BrokerSummaryScalarFieldEnum = (typeof BrokerSummaryScalarFieldEnum)[keyof typeof BrokerSummaryScalarFieldEnum]


export const StockSummaryScalarFieldEnum = {
  id: 'id',
  date: 'date',
  ticker: 'ticker',
  previousClose: 'previousClose',
  openPrice: 'openPrice',
  high: 'high',
  low: 'low',
  close: 'close',
  change: 'change',
  volume: 'volume',
  value: 'value',
  frequency: 'frequency',
  foreignSell: 'foreignSell',
  foreignBuy: 'foreignBuy',
  listedShares: 'listedShares',
  tradeableShares: 'tradeableShares',
  bid: 'bid',
  bidVolume: 'bidVolume',
  offer: 'offer',
  offerVolume: 'offerVolume',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type StockSummaryScalarFieldEnum = (typeof StockSummaryScalarFieldEnum)[keyof typeof StockSummaryScalarFieldEnum]


export const IndexSummaryScalarFieldEnum = {
  id: 'id',
  date: 'date',
  close: 'close',
  volume: 'volume',
  value: 'value',
  marketCapital: 'marketCapital',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type IndexSummaryScalarFieldEnum = (typeof IndexSummaryScalarFieldEnum)[keyof typeof IndexSummaryScalarFieldEnum]


export const MarketIndexSnapshotScalarFieldEnum = {
  id: 'id',
  indexName: 'indexName',
  value: 'value',
  changePercent: 'changePercent',
  turnoverIdr: 'turnoverIdr',
  foreignFlowIdr: 'foreignFlowIdr',
  advancers: 'advancers',
  decliners: 'decliners',
  capturedAt: 'capturedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type MarketIndexSnapshotScalarFieldEnum = (typeof MarketIndexSnapshotScalarFieldEnum)[keyof typeof MarketIndexSnapshotScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

