-- Market data tables mirrored from the upstream market-data project. Their
-- names are kept unprefixed (not `t_`) so queries and importers can be shared
-- with that project unchanged.
--
-- Hand-written rather than generated, because Prisma cannot express declarative
-- partitioning. Prisma only ever sees the parent table, so the partitions below
-- are invisible to `migrate diff` and will not be dropped as drift.

-- CreateTable
CREATE TABLE "public"."broker_summaries" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "date" DATE NOT NULL,
    "ticker" VARCHAR(12) NOT NULL,
    "broker" VARCHAR(4) NOT NULL,
    "is_foreign" BOOLEAN NOT NULL,
    "action" VARCHAR(4) NOT NULL,
    "avg_px" DECIMAL(15,2),
    "volume" BIGINT,
    "value" BIGINT,
    "is_net" BOOLEAN NOT NULL,
    "txn_type" VARCHAR(2) NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT now(),
    "frequency" INTEGER DEFAULT 0,

    -- The partition key has to be part of every unique constraint, hence the
    -- composite key rather than "id" alone.
    CONSTRAINT "broker_summaries_pkey" PRIMARY KEY ("id", "date"),
    CONSTRAINT "broker_summaries_uniq" UNIQUE ("date", "ticker", "broker", "is_foreign", "action", "is_net", "txn_type")
) PARTITION BY RANGE ("date");

-- CreatePartitions
-- 84 monthly partitions, 2020-01 through 2026-12. There is deliberately no
-- DEFAULT partition: a row dated outside this window should fail loudly rather
-- than land in a catch-all that is painful to split back out later. Extend the
-- range with a follow-up migration before 2027 data arrives.
DO $$
DECLARE
    month_start DATE;
BEGIN
    FOR month_start IN
        SELECT generate_series(DATE '2020-01-01', DATE '2026-12-01', INTERVAL '1 month')::date
    LOOP
        EXECUTE format(
            'CREATE TABLE %I PARTITION OF "public"."broker_summaries" FOR VALUES FROM (%L) TO (%L)',
            'broker_summaries_' || to_char(month_start, 'YYYY_MM'),
            month_start,
            (month_start + INTERVAL '1 month')::date
        );
    END LOOP;
END
$$;

-- CreateIndex
CREATE INDEX "idx_broker_summaries_broker" ON "public"."broker_summaries" ("broker");
CREATE INDEX "idx_broker_summaries_date" ON "public"."broker_summaries" ("date" DESC);
CREATE INDEX "idx_broker_summaries_date_broker" ON "public"."broker_summaries" ("date" DESC, "broker");
CREATE INDEX "idx_broker_summaries_date_ticker" ON "public"."broker_summaries" ("date" DESC, "ticker");
CREATE INDEX "idx_broker_summaries_is_net" ON "public"."broker_summaries" ("is_net");
CREATE INDEX "idx_broker_summaries_ticker" ON "public"."broker_summaries" ("ticker");
CREATE INDEX "idx_broker_summaries_txn_type" ON "public"."broker_summaries" ("txn_type");

-- CreateTable
CREATE TABLE "public"."stock_summaries" (
    "id" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    "date" DATE NOT NULL,
    "ticker" VARCHAR(10) NOT NULL,
    "previous_close" DECIMAL(15,2),
    "open_price" DECIMAL(15,2),
    "high" DECIMAL(15,2),
    "low" DECIMAL(15,2),
    "close" DECIMAL(15,2) NOT NULL,
    "change" DECIMAL(15,2),
    "volume" BIGINT DEFAULT 0,
    "value" BIGINT DEFAULT 0,
    "frequency" INTEGER DEFAULT 0,
    "foreign_sell" BIGINT DEFAULT 0,
    "foreign_buy" BIGINT DEFAULT 0,
    "listed_shares" BIGINT,
    "tradeable_shares" BIGINT,
    "bid" DECIMAL(15,2),
    "bid_volume" BIGINT,
    "offer" DECIMAL(15,2),
    "offer_volume" BIGINT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT now(),
    -- No time zone, matching the upstream table.
    "updated_at" TIMESTAMP(6),

    CONSTRAINT "stock_summaries_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "uq_stock_summary_date_ticker" UNIQUE ("date", "ticker")
);

-- CreateIndex
CREATE INDEX "idx_stock_summary_date" ON "public"."stock_summaries" ("date");
CREATE INDEX "idx_stock_summary_ticker" ON "public"."stock_summaries" ("ticker");
CREATE INDEX "idx_stock_summary_ticker_date" ON "public"."stock_summaries" ("ticker", "date");
